/**
 * Core Package - Offsets
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

/**
 * FNameEntry Offsets
 * Size: 0x0020 (header only, Name is variable length)
 */
export const FNameEntry = {
  HashNext: 0x0000n, // 0x0000 (0x0008) [FPointer]
  Index: 0x0008n, // 0x0008 (0x0008) [uint64]
  Flags: 0x0010n, // 0x0010 (0x0008) [uint64]
  Name: 0x0018n, // 0x0018 (variable) [wchar_t*] null-terminated, max ~1024 chars
} as const;

/**
 * TArray Offsets
 * Size: 0x0010
 */
export const TArray = {
  Data: 0x0000n, // 0x0000 (0x0008) [void*]
  Count: 0x0008n, // 0x0008 (0x0004) [int32]
  Max: 0x000cn, // 0x000c (0x0004) [int32]
} as const;

export const TArraySize = 0x10n;

/**
 * Core.Object Offsets
 * Size: 0x0060
 */
export const Object_ = {
  VfTableObject: 0x0000n, // 0x0000 (0x0008) [FPointer]
  HashNext: 0x0008n, // 0x0008 (0x0008) [FPointer]
  ObjectFlags: 0x0010n, // 0x0010 (0x0008) [uint64]
  HashOuterNext: 0x0018n, // 0x0018 (0x0008) [FPointer]
  StateFrame: 0x0020n, // 0x0020 (0x0008) [FPointer]
  Linker: 0x0028n, // 0x0028 (0x0008) [UObject*]
  LinkerIndex: 0x0030n, // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: 0x0038n, // 0x0038 (0x0004) [int32]
  NetIndex: 0x003cn, // 0x003c (0x0004) [int32]
  Outer: 0x0040n, // 0x0040 (0x0008) [UObject*]
  Name: 0x0048n, // 0x0048 (0x0008) [FName]
  Class: 0x0050n, // 0x0050 (0x0008) [UObject*]
  ObjectArchetype: 0x0058n, // 0x0058 (0x0008) [UObject*]
} as const;

/**
 * Core.__AsyncTask__All_0x1 Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const __AsyncTask__All_0x1 = {
  DependentsCount: 0x0060n, // 0x0060 (0x0004) [int32]
  Parent: 0x0068n, // 0x0068 (0x0008) [UAsyncTask*]
  ...Object_,
} as const;

/**
 * Core._LoggingDoc Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const _LoggingDoc = {
  ...Object_,
} as const;

/**
 * Core._Types_Core Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const _Types_Core = {
  ...Object_,
} as const;

/**
 * Core._Types_Generated Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const _Types_Generated = {
  ...Object_,
} as const;

/**
 * Core.ErrorList Offsets
 * Size: 0x0080
 * Extends: Object_
 */
export const ErrorList = {
  LocalizationPackage: 0x0060n, // 0x0060 (0x0010) [FString]
  LocalizationSection: 0x0070n, // 0x0070 (0x0010) [FString]
  ...Object_,
} as const;

/**
 * Core.ArrayErrors Offsets
 * Size: 0x0090
 * Extends: ErrorList
 */
export const ArrayErrors = {
  Remove_NegativeNumberOfElements: 0x0080n, // 0x0080 (0x0008) [UErrorType*]
  Remove_OutOfBounds: 0x0088n, // 0x0088 (0x0008) [UErrorType*]
  ...ErrorList,
} as const;

/**
 * Core.ArrayFuncs Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const ArrayFuncs = {
  ...Object_,
} as const;

/**
 * Core.Field Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const Field = {
  ...Object_,
} as const;

/**
 * Core.Property Offsets
 * Size: 0x00c8
 * Extends: Field
 */
export const Property = {
  ...Field,
} as const;

/**
 * Core.ArrayProperty Offsets
 * Size: 0x00d0
 * Extends: Property
 */
export const ArrayProperty = {
  ...Property,
} as const;

/**
 * Core.AsyncTask Offsets
 * Size: 0x00d0
 * Extends: Object_
 */
export const AsyncTask = {
  bComplete: 0x0060n, // 0x0060 (0x0004) [bool : 0x1]
  bDisposed: 0x0060n, // 0x0060 (0x0004) [bool : 0x2]
  Error: 0x0068n, // 0x0068 (0x0008) [UError*]
  __EventAsyncTaskSuccess__Delegate: 0x0070n, // 0x0070 (0x0018) [FScriptDelegate]
  __EventAsyncTaskFail__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __EventAsyncTaskComplete__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  __EventDisposed__Delegate: 0x00b8n, // 0x00b8 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Core.AsyncResult Offsets
 * Size: 0x00d0
 * Extends: AsyncTask
 */
export const AsyncResult = {
  ...AsyncTask,
} as const;

/**
 * Core.AutomationTest Offsets
 * Size: 0x00a0
 * Extends: Object_
 */
export const AutomationTest = {
  MaterialsCompiled: 0x0060n, // 0x0060 (0x0010) [TArray<FString>]
  MaterialsFailedCompile: 0x0070n, // 0x0070 (0x0010) [TArray<FString>]
  AsyncPreloadPackagesMissing: 0x0080n, // 0x0080 (0x0010) [TArray<FString>]
  ScriptWarnings: 0x0090n, // 0x0090 (0x0010) [TArray<FScriptWarning>]
  ...Object_,
} as const;

/**
 * Core.Base64 Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const Base64 = {
  ...Object_,
} as const;

/**
 * Core.BoolProperty Offsets
 * Size: 0x00d0
 * Extends: Property
 */
export const BoolProperty = {
  ...Property,
} as const;

/**
 * Core.Breadcrumbs Offsets
 * Size: 0x0068
 * Extends: Object_
 */
export const Breadcrumbs = {
  BreadcrumbInstance: 0x0060n, // 0x0060 (0x0008) [FPointer]
  ...Object_,
} as const;

/**
 * Core.ByteProperty Offsets
 * Size: 0x00d0
 * Extends: Property
 */
export const ByteProperty = {
  ...Property,
} as const;

/**
 * Core.Struct Offsets
 * Size: 0x0130
 * Extends: Field
 */
export const Struct = {
  ...Field,
} as const;

/**
 * Core.State Offsets
 * Size: 0x0190
 * Extends: Struct
 */
export const State = {
  ...Struct,
} as const;

/**
 * Core.Class Offsets
 * Size: 0x03b8
 * Extends: State
 */
export const Class = {
  ...State,
} as const;

/**
 * Core.ObjectProperty Offsets
 * Size: 0x00d8
 * Extends: Property
 */
export const ObjectProperty = {
  ...Property,
} as const;

/**
 * Core.ClassProperty Offsets
 * Size: 0x00e0
 * Extends: ObjectProperty
 */
export const ClassProperty = {
  ...ObjectProperty,
} as const;

/**
 * Core.ClassTuple_ORS Offsets
 * Size: 0x00c8
 * Extends: Object_
 */
export const ClassTuple_ORS = {
  ...Object_,
} as const;

/**
 * Core.ClassTupleCollection_ORS Offsets
 * Size: 0x00c0
 * Extends: Object_
 */
export const ClassTupleCollection_ORS = {
  ...Object_,
} as const;

/**
 * Core.Commandlet Offsets
 * Size: 0x00b4
 * Extends: Object_
 */
export const Commandlet = {
  HelpDescription: 0x0060n, // 0x0060 (0x0010) [FString]
  HelpUsage: 0x0070n, // 0x0070 (0x0010) [FString]
  HelpWebLink: 0x0080n, // 0x0080 (0x0010) [FString]
  HelpParamNames: 0x0090n, // 0x0090 (0x0010) [TArray<FString>]
  HelpParamDescriptions: 0x00a0n, // 0x00a0 (0x0010) [TArray<FString>]
  IsServer: 0x00b0n, // 0x00b0 (0x0004) [bool : 0x1]
  IsClient: 0x00b0n, // 0x00b0 (0x0004) [bool : 0x2]
  IsEditor: 0x00b0n, // 0x00b0 (0x0004) [bool : 0x4]
  LogToConsole: 0x00b0n, // 0x00b0 (0x0004) [bool : 0x8]
  ShowErrorCount: 0x00b0n, // 0x00b0 (0x0004) [bool : 0x10]
  ...Object_,
} as const;

/**
 * Core.Component Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const Component = {
  TemplateOwnerClass: 0x0060n, // 0x0060 (0x0008) [UObject*]
  TemplateName: 0x0068n, // 0x0068 (0x0008) [FName]
  ...Object_,
} as const;

/**
 * Core.ComponentProperty Offsets
 * Size: 0x00d8
 * Extends: ObjectProperty
 */
export const ComponentProperty = {
  ...ObjectProperty,
} as const;

/**
 * Core.Compression Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const Compression = {
  ...Object_,
} as const;

/**
 * Core.Config_ORS Offsets
 * Size: 0x00c0
 * Extends: Object_
 */
export const Config_ORS = {
  ...Object_,
} as const;

/**
 * Core.Const Offsets
 * Size: 0x0080
 * Extends: Field
 */
export const Const = {
  ...Field,
} as const;

/**
 * Core.DebugDrawer Offsets
 * Size: 0x00c0
 * Extends: Object_
 */
export const DebugDrawer = {
  DefaultTextColor: 0x0060n, // 0x0060 (0x0004) [FColor]
  bSilent: 0x0064n, // 0x0064 (0x0004) [bool : 0x1]
  bPrintActorsInline: 0x0064n, // 0x0064 (0x0004) [bool : 0x2]
  Indentation: 0x0068n, // 0x0068 (0x0004) [int32]
  IndentationString: 0x0070n, // 0x0070 (0x0010) [FString]
  PrintedObjects: 0x0080n, // 0x0080 (0x0010) [TArray<UObject*>]
  QueuedObjects: 0x0090n, // 0x0090 (0x0010) [TArray<UObject*>]
  PrintObjectCount: 0x00a0n, // 0x00a0 (0x0004) [int32]
  __LogFunc__Delegate: 0x00a8n, // 0x00a8 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Core.DelegateProperty Offsets
 * Size: 0x00d8
 * Extends: Property
 */
export const DelegateProperty = {
  ...Property,
} as const;

/**
 * Core.DelegateTracker Offsets
 * Size: 0x0088
 * Extends: Object_
 */
export const DelegateTracker = {
  AsyncDelegates: 0x0060n, // 0x0060 (0x0010) [TArray<FAsyncDelegateInfo>]
  __PlaceholderDelegate__Delegate: 0x0070n, // 0x0070 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Core.DistributionFloat Offsets
 * Size: 0x007c
 * Extends: Component
 */
export const DistributionFloat = {
  VfTable_FCurveEdInterface: 0x0070n, // 0x0070 (0x0008) [FPointer]
  bCanBeBaked: 0x0078n, // 0x0078 (0x0004) [bool : 0x1]
  bIsDirty: 0x0078n, // 0x0078 (0x0004) [bool : 0x2]
  ...Component,
} as const;

/**
 * Core.DistributionVector Offsets
 * Size: 0x007c
 * Extends: Component
 */
export const DistributionVector = {
  VfTable_FCurveEdInterface: 0x0070n, // 0x0070 (0x0008) [FPointer]
  bCanBeBaked: 0x0078n, // 0x0078 (0x0004) [bool : 0x1]
  bIsDirty: 0x0078n, // 0x0078 (0x0004) [bool : 0x2]
  ...Component,
} as const;

/**
 * Core.Enum Offsets
 * Size: 0x0080
 * Extends: Field
 */
export const Enum = {
  ...Field,
} as const;

/**
 * Core.Error Offsets
 * Size: 0x0084
 * Extends: Object_
 */
export const Error_ = {
  Type: 0x0060n, // 0x0060 (0x0008) [UErrorType*]
  Message: 0x0068n, // 0x0068 (0x0010) [FString]
  Code: 0x0078n, // 0x0078 (0x0004) [int32]
  RetryKey: 0x007cn, // 0x007c (0x0008) [FName]
  ...Object_,
} as const;

/**
 * Core.ErrorType Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const ErrorType = {
  LocalizationKey: 0x0060n, // 0x0060 (0x0010) [FString]
  ...Object_,
} as const;

/**
 * Core.Exporter Offsets
 * Size: 0x0098
 * Extends: Object_
 */
export const Exporter = {
  FormatExtension: 0x0068n, // 0x0068 (0x0010) [TArray<FString>]
  FormatDescription: 0x0078n, // 0x0078 (0x0010) [TArray<FString>]
  ...Object_,
} as const;

/**
 * Core.Factory Offsets
 * Size: 0x00b8
 * Extends: Object_
 */
export const Factory = {
  Category: 0x0060n, // 0x0060 (0x0010) [FString]
  SupportedClass: 0x0070n, // 0x0070 (0x0008) [UObject*]
  ContextClass: 0x0078n, // 0x0078 (0x0008) [UObject*]
  Description: 0x0080n, // 0x0080 (0x0010) [FString]
  Formats: 0x0090n, // 0x0090 (0x0010) [TArray<FString>]
  bCreateNew: 0x00a0n, // 0x00a0 (0x0004) [bool : 0x1]
  bEditAfterNew: 0x00a0n, // 0x00a0 (0x0004) [bool : 0x2]
  bEditorImport: 0x00a0n, // 0x00a0 (0x0004) [bool : 0x4]
  bText: 0x00a0n, // 0x00a0 (0x0004) [bool : 0x8]
  bAssetNameMatchesPackageName: 0x00a0n, // 0x00a0 (0x0004) [bool : 0x10]
  AutoPriority: 0x00a4n, // 0x00a4 (0x0004) [int32]
  ValidGameNames: 0x00a8n, // 0x00a8 (0x0010) [TArray<FString>]
  ...Object_,
} as const;

/**
 * Core.Object.Array_Mirror Offsets
 * Size: 0x0010
 */
export const FArray_Mirror = {
  Data: 0x0000n, // 0x0000 (0x0008) [FPointer]
  ArrayNum: 0x0008n, // 0x0008 (0x0004) [int32]
  ArrayMax: 0x000cn, // 0x000c (0x0004) [int32]
} as const;

/**
 * Core.DelegateTracker.AsyncDelegateInfo Offsets
 * Size: 0x0020
 */
export const FAsyncDelegateInfo = {
  CallbackId: 0x0000n, // 0x0000 (0x0004) [int32]
  AsyncDelegate: 0x0008n, // 0x0008 (0x0018) [FScriptDelegate]
} as const;

/**
 * Core.Object.BitArray_Mirror Offsets
 * Size: 0x0020
 */
export const FBitArray_Mirror = {
  IndirectData: 0x0000n, // 0x0000 (0x0008) [FPointer]
  InlineData: 0x0008n, // 0x0008 (0x0010) [int32]
  NumBits: 0x0018n, // 0x0018 (0x0004) [int32]
  MaxBits: 0x001cn, // 0x001c (0x0004) [int32]
} as const;

/**
 * Core.Object.BoneAtom Offsets
 * Size: 0x0020
 */
export const FBoneAtom = {
  Rotation: 0x0000n, // 0x0000 (0x0010) [FQuat]
  Translation: 0x0010n, // 0x0010 (0x000c) [FVector]
  Scale: 0x001cn, // 0x001c (0x0004) [float]
} as const;

/**
 * Core.Object.Box Offsets
 * Size: 0x0019
 */
export const FBox = {
  Min: 0x0000n, // 0x0000 (0x000c) [FVector]
  Max: 0x000cn, // 0x000c (0x000c) [FVector]
  IsValid: 0x0018n, // 0x0018 (0x0001) [uint8]
} as const;

/**
 * Core.Object.BoxSphereBounds Offsets
 * Size: 0x001c
 */
export const FBoxSphereBounds = {
  Origin: 0x0000n, // 0x0000 (0x000c) [FVector]
  BoxExtent: 0x000cn, // 0x000c (0x000c) [FVector]
  SphereRadius: 0x0018n, // 0x0018 (0x0004) [float]
} as const;

/**
 * Core.Breadcrumbs.BreadcrumbEntry Offsets
 * Size: 0x0020
 */
export const FBreadcrumbEntry = {
  Category: 0x0000n, // 0x0000 (0x0010) [FString]
  Value: 0x0010n, // 0x0010 (0x0010) [FString]
} as const;

/**
 * Core.Object.Color Offsets
 * Size: 0x0004
 */
export const FColor = {
  B: 0x0000n, // 0x0000 (0x0001) [uint8]
  G: 0x0001n, // 0x0001 (0x0001) [uint8]
  R: 0x0002n, // 0x0002 (0x0001) [uint8]
  A: 0x0003n, // 0x0003 (0x0001) [uint8]
} as const;

/**
 * Core.Object.Cylinder Offsets
 * Size: 0x0008
 */
export const FCylinder = {
  Radius: 0x0000n, // 0x0000 (0x0004) [float]
  Height: 0x0004n, // 0x0004 (0x0004) [float]
} as const;

/**
 * Core.Object.Double Offsets
 * Size: 0x0008
 */
export const FDouble = {
  A: 0x0000n, // 0x0000 (0x0004) [int32]
  B: 0x0004n, // 0x0004 (0x0004) [int32]
} as const;

/**
 * Core.FeatureSystem Offsets
 * Size: 0x0080
 * Extends: Object_
 */
export const FeatureSystem = {
  Prime: 0x0068n, // 0x0068 (0x0004) [bool : 0x2]
  Matchmaking: 0x0068n, // 0x0068 (0x0004) [bool : 0x8]
  PrivateMatch: 0x0068n, // 0x0068 (0x0004) [bool : 0x10]
  SplitscreenMatch: 0x0068n, // 0x0068 (0x0004) [bool : 0x20]
  SplitscreenJoin: 0x0068n, // 0x0068 (0x0004) [bool : 0x40]
  SeasonMode: 0x0068n, // 0x0068 (0x0004) [bool : 0x80]
  Tutorial: 0x0068n, // 0x0068 (0x0004) [bool : 0x100]
  Garage: 0x0068n, // 0x0068 (0x0004) [bool : 0x200]
  Options: 0x0068n, // 0x0068 (0x0004) [bool : 0x400]
  ReplaySaves: 0x0068n, // 0x0068 (0x0004) [bool : 0x800]
  MainMenu: 0x0068n, // 0x0068 (0x0004) [bool : 0x1000]
  MidgameMenu: 0x0068n, // 0x0068 (0x0004) [bool : 0x2000]
  Party: 0x0068n, // 0x0068 (0x0004) [bool : 0x4000]
  PsyNetParty: 0x0068n, // 0x0068 (0x0004) [bool : 0x8000]
  Achievements: 0x0068n, // 0x0068 (0x0004) [bool : 0x10000]
  Stats: 0x0068n, // 0x0068 (0x0004) [bool : 0x20000]
  Leaderboards: 0x0068n, // 0x0068 (0x0004) [bool : 0x40000]
  XP: 0x0068n, // 0x0068 (0x0004) [bool : 0x80000]
  Chat: 0x0068n, // 0x0068 (0x0004) [bool : 0x100000]
  TrainingDifficulties: 0x0068n, // 0x0068 (0x0004) [bool : 0x200000]
  Spectator: 0x0068n, // 0x0068 (0x0004) [bool : 0x400000]
  CrossPlatformPrivateMatch: 0x0068n, // 0x0068 (0x0004) [bool : 0x800000]
  Lan: 0x0068n, // 0x0068 (0x0004) [bool : 0x1000000]
  PlayerReporting: 0x0068n, // 0x0068 (0x0004) [bool : 0x2000000]
  OnlineServices: 0x0068n, // 0x0068 (0x0004) [bool : 0x40000000]
  RemoveCrossPlatformProducts: 0x0068n, // 0x0068 (0x0004) [bool : 0x80000000]
  ProductValidation: 0x006cn, // 0x006c (0x0004) [bool : 0x1]
  MapPrefs: 0x006cn, // 0x006c (0x0004) [bool : 0x2]
  PreMatchLobby: 0x006cn, // 0x006c (0x0004) [bool : 0x8]
  Challenges: 0x006cn, // 0x006c (0x0004) [bool : 0x10]
  AntiAddiction: 0x006cn, // 0x006c (0x0004) [bool : 0x20]
  TrainingEditor: 0x006cn, // 0x006c (0x0004) [bool : 0x40]
  VoiceChat: 0x006cn, // 0x006c (0x0004) [bool : 0x80]
  SplitScreen: 0x006cn, // 0x006c (0x0004) [bool : 0x100]
  Clubs: 0x006cn, // 0x006c (0x0004) [bool : 0x200]
  FilterContent: 0x006cn, // 0x006c (0x0004) [bool : 0x400]
  EncryptContent: 0x006cn, // 0x006c (0x0004) [bool : 0x800]
  EsportsCamera: 0x006cn, // 0x006c (0x0004) [bool : 0x4000]
  OnlineXP: 0x006cn, // 0x006c (0x0004) [bool : 0x8000]
  ClanforgeReservation: 0x006cn, // 0x006c (0x0004) [bool : 0x20000]
  UserSettingObserver: 0x006cn, // 0x006c (0x0004) [bool : 0x40000]
  Metrics: 0x006cn, // 0x006c (0x0004) [bool : 0x80000]
  EOSMetrics: 0x006cn, // 0x006c (0x0004) [bool : 0x100000]
  MusicPlaylistSelection: 0x006cn, // 0x006c (0x0004) [bool : 0x200000]
  SpecialEvents: 0x006cn, // 0x006c (0x0004) [bool : 0x400000]
  PlayerBannerCustomization: 0x006cn, // 0x006c (0x0004) [bool : 0x800000]
  SecureUDP: 0x006cn, // 0x006c (0x0004) [bool : 0x1000000]
  PsyNet: 0x006cn, // 0x006c (0x0004) [bool : 0x2000000]
  OnlinePlayerStorage: 0x006cn, // 0x006c (0x0004) [bool : 0x4000000]
  LocalSaveData: 0x006cn, // 0x006c (0x0004) [bool : 0x8000000]
  CrowdV2: 0x006cn, // 0x006c (0x0004) [bool : 0x10000000]
  ChatBan: 0x006cn, // 0x006c (0x0004) [bool : 0x20000000]
  BacktraceCrashDumps: 0x006cn, // 0x006c (0x0004) [bool : 0x40000000]
  SpotifyButton: 0x006cn, // 0x006c (0x0004) [bool : 0x80000000]
  SeasonRewards: 0x0070n, // 0x0070 (0x0004) [bool : 0x1]
  FaceIt: 0x0070n, // 0x0070 (0x0004) [bool : 0x2]
  KnockOut: 0x0070n, // 0x0070 (0x0004) [bool : 0x4]
  OnlinePlayerTitles: 0x0070n, // 0x0070 (0x0004) [bool : 0x8]
  RestrictByRegion: 0x0070n, // 0x0070 (0x0004) [bool : 0x10]
  FirstTimeExperience: 0x0070n, // 0x0070 (0x0004) [bool : 0x40]
  RLBot: 0x0070n, // 0x0070 (0x0004) [bool : 0x80]
  UserBugReport: 0x0070n, // 0x0070 (0x0004) [bool : 0x100]
  SteamInput: 0x0070n, // 0x0070 (0x0004) [bool : 0x200]
  ReplayFXControls: 0x0070n, // 0x0070 (0x0004) [bool : 0x4000]
  ESportsShop: 0x0070n, // 0x0070 (0x0004) [bool : 0x8000]
  MatchHistory: 0x0070n, // 0x0070 (0x0004) [bool : 0x10000]
  DynamicRangeAudioSettings: 0x0070n, // 0x0070 (0x0004) [bool : 0x80000]
  QuickPlay: 0x0070n, // 0x0070 (0x0004) [bool : 0x100000]
  NewsPanelV2: 0x0070n, // 0x0070 (0x0004) [bool : 0x200000]
  Blueprints: 0x0070n, // 0x0070 (0x0004) [bool : 0x400000]
  RocketBucks: 0x0070n, // 0x0070 (0x0004) [bool : 0x1000000]
  Tritip: 0x0070n, // 0x0070 (0x0004) [bool : 0x4000000]
  DiscordRichPresence: 0x0070n, // 0x0070 (0x0004) [bool : 0x10000000]
  SupportACreator: 0x0070n, // 0x0070 (0x0004) [bool : 0x20000000]
  CinematicIntro: 0x0070n, // 0x0070 (0x0004) [bool : 0x40000000]
  TinyCrowd: 0x0070n, // 0x0070 (0x0004) [bool : 0x80000000]
  CrumbTrail: 0x0074n, // 0x0074 (0x0004) [bool : 0x1]
  EpicGameStoreBuild: 0x0074n, // 0x0074 (0x0004) [bool : 0x2]
  XPGatedPlaylists: 0x0074n, // 0x0074 (0x0004) [bool : 0x4]
  TradeInV2: 0x0074n, // 0x0074 (0x0004) [bool : 0x10]
  Football: 0x0074n, // 0x0074 (0x0004) [bool : 0x20]
  RumbleSelection: 0x0074n, // 0x0074 (0x0004) [bool : 0x40]
  UndersizedParty: 0x0074n, // 0x0074 (0x0004) [bool : 0x80]
  StreamerSafeAudio: 0x0074n, // 0x0074 (0x0004) [bool : 0x100]
  FreeplayCommands: 0x0074n, // 0x0074 (0x0004) [bool : 0x200]
  Rumble_BM: 0x0074n, // 0x0074 (0x0004) [bool : 0x400]
  PlayerReportingV2: 0x0074n, // 0x0074 (0x0004) [bool : 0x800]
  EOSVoice: 0x0074n, // 0x0074 (0x0004) [bool : 0x2000]
  QuickPostMatchRequeue: 0x0074n, // 0x0074 (0x0004) [bool : 0x4000]
  TrainingNavigation: 0x0074n, // 0x0074 (0x0004) [bool : 0x20000]
  TrainingManipulation: 0x0074n, // 0x0074 (0x0004) [bool : 0x40000]
  FilterByColor: 0x0074n, // 0x0074 (0x0004) [bool : 0x100000]
  Scoreboard: 0x0074n, // 0x0074 (0x0004) [bool : 0x200000]
  DynamicMapEvents: 0x0074n, // 0x0074 (0x0004) [bool : 0x400000]
  NameplateBoost: 0x0074n, // 0x0074 (0x0004) [bool : 0x1000000]
  EOSGameClips: 0x0074n, // 0x0074 (0x0004) [bool : 0x2000000]
  DynamicLogos: 0x0074n, // 0x0074 (0x0004) [bool : 0x4000000]
  XETagging: 0x0074n, // 0x0074 (0x0004) [bool : 0x8000000]
  PlayMenuV4: 0x0074n, // 0x0074 (0x0004) [bool : 0x10000000]
  QuickChatTimeStamp: 0x0074n, // 0x0074 (0x0004) [bool : 0x20000000]
  SoccarPong: 0x0074n, // 0x0074 (0x0004) [bool : 0x40000000]
  OnlineFreeplay: 0x0074n, // 0x0074 (0x0004) [bool : 0x80000000]
  MatchmakingSubRegion: 0x0078n, // 0x0078 (0x0004) [bool : 0x2]
  CrossbarSFX: 0x0078n, // 0x0078 (0x0004) [bool : 0x4]
  RugbyIteration: 0x0078n, // 0x0078 (0x0004) [bool : 0x8]
  ChallengesV2: 0x0078n, // 0x0078 (0x0004) [bool : 0x20]
  PossessionExpanded: 0x0078n, // 0x0078 (0x0004) [bool : 0x40]
  TargetFind: 0x0078n, // 0x0078 (0x0004) [bool : 0x80]
  KeepUp: 0x0078n, // 0x0078 (0x0004) [bool : 0x200]
  RocketPassUpgrades: 0x0078n, // 0x0078 (0x0004) [bool : 0x800]
  PentathlonTournaments: 0x0078n, // 0x0078 (0x0004) [bool : 0x1000]
  DemolishUpdates: 0x0078n, // 0x0078 (0x0004) [bool : 0x2000]
  ViralItem: 0x0078n, // 0x0078 (0x0004) [bool : 0x4000]
  ThankYouMessage: 0x0078n, // 0x0078 (0x0004) [bool : 0x8000]
  AttackerDemoFX: 0x0078n, // 0x0078 (0x0004) [bool : 0x10000]
  NewDriverChallengesV2: 0x0078n, // 0x0078 (0x0004) [bool : 0x20000]
  TextModeration: 0x0078n, // 0x0078 (0x0004) [bool : 0x100000]
  FilterToggle: 0x0078n, // 0x0078 (0x0004) [bool : 0x200000]
  DdosPrevention: 0x0078n, // 0x0078 (0x0004) [bool : 0x400000]
  OunceEnhancements: 0x0078n, // 0x0078 (0x0004) [bool : 0x800000]
  FastFreeplay: 0x0078n, // 0x0078 (0x0004) [bool : 0x1000000]
  MatchAdminMutator: 0x0078n, // 0x0078 (0x0004) [bool : 0x2000000]
  Thistle: 0x0078n, // 0x0078 (0x0004) [bool : 0x4000000]
  DemoFXMutator: 0x0078n, // 0x0078 (0x0004) [bool : 0x8000000]
  OffProdHandling: 0x0078n, // 0x0078 (0x0004) [bool : 0x10000000]
  CustomTrainingSettings: 0x0078n, // 0x0078 (0x0004) [bool : 0x20000000]
  FlipResetIndicator: 0x0078n, // 0x0078 (0x0004) [bool : 0x80000000]
  NewsOverhaul: 0x007cn, // 0x007c (0x0004) [bool : 0x1]
  QueueMenuChanges: 0x007cn, // 0x007c (0x0004) [bool : 0x2]
  VisibleMMR: 0x007cn, // 0x007c (0x0004) [bool : 0x4]
  EasyAntiCheat: 0x007cn, // 0x007c (0x0004) [bool : 0x8]
  OverrideBoostSound: 0x007cn, // 0x007c (0x0004) [bool : 0x10]
  SettingsExport: 0x007cn, // 0x007c (0x0004) [bool : 0x20]
  FreeplayTeamColors: 0x007cn, // 0x007c (0x0004) [bool : 0x400]
  StatsAPI: 0x007cn, // 0x007c (0x0004) [bool : 0x1000]
  ...Object_,
} as const;

/**
 * Core._Types_Core.EncryptedKeyIndex Offsets
 * Size: 0x0004
 */
export const FEncryptedKeyIndex = {
  Index: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * Core.Object.FColorVertexBuffer_Mirror Offsets
 * Size: 0x001c
 */
export const FFColorVertexBuffer_Mirror = {
  VfTable: 0x0000n, // 0x0000 (0x0008) [FPointer]
  VertexData: 0x0008n, // 0x0008 (0x0008) [FPointer]
  Data: 0x0010n, // 0x0010 (0x0004) [int32]
  Stride: 0x0014n, // 0x0014 (0x0004) [int32]
  NumVertices: 0x0018n, // 0x0018 (0x0004) [int32]
} as const;

/**
 * Core.Object.Guid Offsets
 * Size: 0x0010
 */
export const FGuid = {
  A: 0x0000n, // 0x0000 (0x0004) [int32]
  B: 0x0004n, // 0x0004 (0x0004) [int32]
  C: 0x0008n, // 0x0008 (0x0004) [int32]
  D: 0x000cn, // 0x000c (0x0004) [int32]
} as const;

/**
 * Core.Object.HatPointer Offsets
 * Size: 0x0008
 */
export const FHatPointer = {
  Dummy: 0x0000n, // 0x0000 (0x0008) [uint64]
} as const;

/**
 * Core.FileSystem Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const FileSystem = {
  ...Object_,
} as const;

/**
 * Core.Object.IndirectArray_Mirror Offsets
 * Size: 0x0010
 */
export const FIndirectArray_Mirror = {
  Data: 0x0000n, // 0x0000 (0x0008) [FPointer]
  ArrayNum: 0x0008n, // 0x0008 (0x0004) [int32]
  ArrayMax: 0x000cn, // 0x000c (0x0004) [int32]
} as const;

/**
 * Core.Object.InlinePointerArray_Mirror Offsets
 * Size: 0x0018
 */
export const FInlinePointerArray_Mirror = {
  InlineData: 0x0000n, // 0x0000 (0x0008) [FPointer]
  SecondaryData: 0x0008n, // 0x0008 (0x0010) [FArray_Mirror]
} as const;

/**
 * Core.ObjectProvider.InterfacePropertyInjection Offsets
 * Size: 0x0010
 */
export const FInterfacePropertyInjection = {
  Subscriber: 0x0000n, // 0x0000 (0x0008) [UObject*]
  Property: 0x0008n, // 0x0008 (0x0008) [UInterfaceProperty*]
} as const;

/**
 * Core.Object.InterpCurveFloat Offsets
 * Size: 0x0011
 */
export const FInterpCurveFloat = {
  Points: 0x0000n, // 0x0000 (0x0010) [TArray<FInterpCurvePointFloat>]
  InterpMethod: 0x0010n, // 0x0010 (0x0001) [EInterpMethodType]
} as const;

/**
 * Core.Object.InterpCurveLinearColor Offsets
 * Size: 0x0011
 */
export const FInterpCurveLinearColor = {
  Points: 0x0000n, // 0x0000 (0x0010) [TArray<FInterpCurvePointLinearColor>]
  InterpMethod: 0x0010n, // 0x0010 (0x0001) [EInterpMethodType]
} as const;

/**
 * Core.Object.InterpCurvePointFloat Offsets
 * Size: 0x0019
 */
export const FInterpCurvePointFloat = {
  InVal: 0x0000n, // 0x0000 (0x0004) [float]
  OutVal: 0x0004n, // 0x0004 (0x0004) [float]
  ArriveTangent: 0x0008n, // 0x0008 (0x0004) [float]
  LeaveTangent: 0x000cn, // 0x000c (0x0004) [float]
  ArriveWeight: 0x0010n, // 0x0010 (0x0004) [float]
  LeaveWeight: 0x0014n, // 0x0014 (0x0004) [float]
  InterpMode: 0x0018n, // 0x0018 (0x0001) [EInterpCurveMode]
} as const;

/**
 * Core.Object.InterpCurvePointLinearColor Offsets
 * Size: 0x0055
 */
export const FInterpCurvePointLinearColor = {
  InVal: 0x0000n, // 0x0000 (0x0004) [float]
  OutVal: 0x0004n, // 0x0004 (0x0010) [FLinearColor]
  ArriveTangent: 0x0014n, // 0x0014 (0x0010) [FLinearColor]
  LeaveTangent: 0x0024n, // 0x0024 (0x0010) [FLinearColor]
  ArriveWeight: 0x0034n, // 0x0034 (0x0010) [FLinearColor]
  LeaveWeight: 0x0044n, // 0x0044 (0x0010) [FLinearColor]
  InterpMode: 0x0054n, // 0x0054 (0x0001) [EInterpCurveMode]
} as const;

/**
 * Core.Object.InterpCurvePointQuat Offsets
 * Size: 0x0061
 */
export const FInterpCurvePointQuat = {
  InVal: 0x0000n, // 0x0000 (0x0004) [float]
  OutVal: 0x0010n, // 0x0010 (0x0010) [FQuat]
  ArriveTangent: 0x0020n, // 0x0020 (0x0010) [FQuat]
  LeaveTangent: 0x0030n, // 0x0030 (0x0010) [FQuat]
  ArriveWeight: 0x0040n, // 0x0040 (0x0010) [FQuat]
  LeaveWeight: 0x0050n, // 0x0050 (0x0010) [FQuat]
  InterpMode: 0x0060n, // 0x0060 (0x0001) [EInterpCurveMode]
} as const;

/**
 * Core.Object.InterpCurvePointTwoVectors Offsets
 * Size: 0x007d
 */
export const FInterpCurvePointTwoVectors = {
  InVal: 0x0000n, // 0x0000 (0x0004) [float]
  OutVal: 0x0004n, // 0x0004 (0x0018) [FTwoVectors]
  ArriveTangent: 0x001cn, // 0x001c (0x0018) [FTwoVectors]
  LeaveTangent: 0x0034n, // 0x0034 (0x0018) [FTwoVectors]
  ArriveWeight: 0x004cn, // 0x004c (0x0018) [FTwoVectors]
  LeaveWeight: 0x0064n, // 0x0064 (0x0018) [FTwoVectors]
  InterpMode: 0x007cn, // 0x007c (0x0001) [EInterpCurveMode]
} as const;

/**
 * Core.Object.InterpCurvePointVector Offsets
 * Size: 0x0041
 */
export const FInterpCurvePointVector = {
  InVal: 0x0000n, // 0x0000 (0x0004) [float]
  OutVal: 0x0004n, // 0x0004 (0x000c) [FVector]
  ArriveTangent: 0x0010n, // 0x0010 (0x000c) [FVector]
  LeaveTangent: 0x001cn, // 0x001c (0x000c) [FVector]
  ArriveWeight: 0x0028n, // 0x0028 (0x000c) [FVector]
  LeaveWeight: 0x0034n, // 0x0034 (0x000c) [FVector]
  InterpMode: 0x0040n, // 0x0040 (0x0001) [EInterpCurveMode]
} as const;

/**
 * Core.Object.InterpCurvePointVector2D Offsets
 * Size: 0x002d
 */
export const FInterpCurvePointVector2D = {
  InVal: 0x0000n, // 0x0000 (0x0004) [float]
  OutVal: 0x0004n, // 0x0004 (0x0008) [FVector2D]
  ArriveTangent: 0x000cn, // 0x000c (0x0008) [FVector2D]
  LeaveTangent: 0x0014n, // 0x0014 (0x0008) [FVector2D]
  ArriveWeight: 0x001cn, // 0x001c (0x0008) [FVector2D]
  LeaveWeight: 0x0024n, // 0x0024 (0x0008) [FVector2D]
  InterpMode: 0x002cn, // 0x002c (0x0001) [EInterpCurveMode]
} as const;

/**
 * Core.Object.InterpCurveQuat Offsets
 * Size: 0x0011
 */
export const FInterpCurveQuat = {
  Points: 0x0000n, // 0x0000 (0x0010) [TArray<FInterpCurvePointQuat>]
  InterpMethod: 0x0010n, // 0x0010 (0x0001) [EInterpMethodType]
} as const;

/**
 * Core.Object.InterpCurveTwoVectors Offsets
 * Size: 0x0011
 */
export const FInterpCurveTwoVectors = {
  Points: 0x0000n, // 0x0000 (0x0010) [TArray<FInterpCurvePointTwoVectors>]
  InterpMethod: 0x0010n, // 0x0010 (0x0001) [EInterpMethodType]
} as const;

/**
 * Core.Object.InterpCurveVector Offsets
 * Size: 0x0011
 */
export const FInterpCurveVector = {
  Points: 0x0000n, // 0x0000 (0x0010) [TArray<FInterpCurvePointVector>]
  InterpMethod: 0x0010n, // 0x0010 (0x0001) [EInterpMethodType]
} as const;

/**
 * Core.Object.InterpCurveVector2D Offsets
 * Size: 0x0011
 */
export const FInterpCurveVector2D = {
  Points: 0x0000n, // 0x0000 (0x0010) [TArray<FInterpCurvePointVector2D>]
  InterpMethod: 0x0010n, // 0x0010 (0x0001) [EInterpMethodType]
} as const;

/**
 * Core.Object.IntPoint Offsets
 * Size: 0x0008
 */
export const FIntPoint = {
  X: 0x0000n, // 0x0000 (0x0004) [int32]
  Y: 0x0004n, // 0x0004 (0x0004) [int32]
} as const;

/**
 * Core.Object.IpAddr Offsets
 * Size: 0x0014
 */
export const FIpAddr = {
  AddrA: 0x0000n, // 0x0000 (0x0004) [int32]
  AddrB: 0x0004n, // 0x0004 (0x0004) [int32]
  AddrC: 0x0008n, // 0x0008 (0x0004) [int32]
  AddrD: 0x000cn, // 0x000c (0x0004) [int32]
  Port: 0x0010n, // 0x0010 (0x0004) [int32]
} as const;

/**
 * Core.Object.LinearColor Offsets
 * Size: 0x0010
 */
export const FLinearColor = {
  R: 0x0000n, // 0x0000 (0x0004) [float]
  G: 0x0004n, // 0x0004 (0x0004) [float]
  B: 0x0008n, // 0x0008 (0x0004) [float]
  A: 0x000cn, // 0x000c (0x0004) [float]
} as const;

/**
 * Core.FloatProperty Offsets
 * Size: 0x00c8
 * Extends: Property
 */
export const FloatProperty = {
  ...Property,
} as const;

/**
 * Core.Object.Map_Mirror Offsets
 * Size: 0x0050
 */
export const FMap_Mirror = {
  Pairs: 0x0000n, // 0x0000 (0x0050) [FSet_Mirror]
} as const;

/**
 * Core.Object.RawDistribution Offsets
 * Size: 0x0020
 */
export const FRawDistribution = {
  Type: 0x0000n, // 0x0000 (0x0001) [uint8]
  Op: 0x0001n, // 0x0001 (0x0001) [uint8]
  LookupTableNumElements: 0x0002n, // 0x0002 (0x0001) [uint8]
  LookupTableChunkSize: 0x0003n, // 0x0003 (0x0001) [uint8]
  LookupTable: 0x0008n, // 0x0008 (0x0010) [TArray<float>]
  LookupTableTimeScale: 0x0018n, // 0x0018 (0x0004) [float]
  LookupTableStartTime: 0x001cn, // 0x001c (0x0004) [float]
} as const;

/**
 * Core.DistributionFloat.RawDistributionFloat Offsets
 * Size: 0x0028
 * Extends: FRawDistribution
 */
export const FRawDistributionFloat = {
  Distribution: 0x0020n, // 0x0020 (0x0008) [UDistributionFloat*]
  ...FRawDistribution,
} as const;

/**
 * Core.DistributionFloat.MatineeRawDistributionFloat Offsets
 * Size: 0x0030
 * Extends: FRawDistributionFloat
 */
export const FMatineeRawDistributionFloat = {
  MatineeValue: 0x0028n, // 0x0028 (0x0004) [float]
  bInMatinee: 0x002cn, // 0x002c (0x0004) [bool : 0x1]
  ...FRawDistributionFloat,
} as const;

/**
 * Core.Object.Matrix Offsets
 * Size: 0x0040
 */
export const FMatrix = {
  XPlane: 0x0000n, // 0x0000 (0x0010) [FPlane]
  YPlane: 0x0010n, // 0x0010 (0x0010) [FPlane]
  ZPlane: 0x0020n, // 0x0020 (0x0010) [FPlane]
  WPlane: 0x0030n, // 0x0030 (0x0010) [FPlane]
} as const;

/**
 * Core.Object.MultiMap_Mirror Offsets
 * Size: 0x0050
 */
export const FMultiMap_Mirror = {
  Pairs: 0x0000n, // 0x0000 (0x0050) [FSet_Mirror]
} as const;

/**
 * Core.ObjectProvider.ObjectPropertyInjection Offsets
 * Size: 0x0010
 */
export const FObjectPropertyInjection = {
  Subscriber: 0x0000n, // 0x0000 (0x0008) [UObject*]
  Property: 0x0008n, // 0x0008 (0x0008) [UObjectProperty*]
} as const;

/**
 * Core.ObjectProvider.ObjectProviderPendingCallback Offsets
 * Size: 0x0020
 */
export const FObjectProviderPendingCallback = {
  Callback: 0x0000n, // 0x0000 (0x0018) [FScriptDelegate]
  Value: 0x0018n, // 0x0018 (0x0008) [UObject*]
} as const;

/**
 * Core.ObjectProvider.ObjectProviderSubscription Offsets
 * Size: 0x0024
 */
export const FObjectProviderSubscription = {
  ObjClass: 0x0000n, // 0x0000 (0x0008) [UObject*]
  Callback: 0x0008n, // 0x0008 (0x0018) [FScriptDelegate]
  bFireOnce: 0x0020n, // 0x0020 (0x0004) [bool : 0x1]
} as const;

/**
 * Core.Object.OctreeElementId Offsets
 * Size: 0x000c
 */
export const FOctreeElementId = {
  Node: 0x0000n, // 0x0000 (0x0008) [FPointer]
  ElementIndex: 0x0008n, // 0x0008 (0x0004) [int32]
} as const;

/**
 * Core.Object.PackedNormal Offsets
 * Size: 0x0004
 */
export const FPackedNormal = {
  X: 0x0000n, // 0x0000 (0x0001) [uint8]
  Y: 0x0001n, // 0x0001 (0x0001) [uint8]
  Z: 0x0002n, // 0x0002 (0x0001) [uint8]
  W: 0x0003n, // 0x0003 (0x0001) [uint8]
} as const;

/**
 * Core.Object.Vector Offsets
 * Size: 0x000c
 */
export const FVector = {
  X: 0x0000n, // 0x0000 (0x0004) [float]
  Y: 0x0004n, // 0x0004 (0x0004) [float]
  Z: 0x0008n, // 0x0008 (0x0004) [float]
} as const;

/**
 * Core.Object.Plane Offsets
 * Size: 0x0010
 * Extends: FVector
 */
export const FPlane = {
  W: 0x000cn, // 0x000c (0x0004) [float]
  ...FVector,
} as const;

/**
 * Core.Object.Pointer Offsets
 * Size: 0x0008
 */
export const FPointer = {
  Dummy: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * Core._Types_Core.ProductHashID Offsets
 * Size: 0x0004
 */
export const FProductHashID = {
  Id: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * Core._Types_Core.ProductInstanceID Offsets
 * Size: 0x0010
 */
export const FProductInstanceID = {
  UpperBits: 0x0000n, // 0x0000 (0x0008) [uint64]
  LowerBits: 0x0008n, // 0x0008 (0x0008) [uint64]
} as const;

/**
 * Core.Object.Quat Offsets
 * Size: 0x0010
 */
export const FQuat = {
  X: 0x0000n, // 0x0000 (0x0004) [float]
  Y: 0x0004n, // 0x0004 (0x0004) [float]
  Z: 0x0008n, // 0x0008 (0x0004) [float]
  W: 0x000cn, // 0x000c (0x0004) [float]
} as const;

/**
 * Core.DistributionVector.RawDistributionVector Offsets
 * Size: 0x0028
 * Extends: FRawDistribution
 */
export const FRawDistributionVector = {
  Distribution: 0x0020n, // 0x0020 (0x0008) [UDistributionVector*]
  ...FRawDistribution,
} as const;

/**
 * Core.Object.RenderCommandFence Offsets
 * Size: 0x0004
 */
export const FRenderCommandFence = {
  NumPendingFences: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * Core.Object.RenderCommandFence_Mirror Offsets
 * Size: 0x0004
 */
export const FRenderCommandFence_Mirror = {
  NumPendingFences: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * Core.Object.Rotator Offsets
 * Size: 0x000c
 */
export const FRotator = {
  Pitch: 0x0000n, // 0x0000 (0x0004) [int32]
  Yaw: 0x0004n, // 0x0004 (0x0004) [int32]
  Roll: 0x0008n, // 0x0008 (0x0004) [int32]
} as const;

/**
 * Core.RotatorConversions.RotatorDegrees Offsets
 * Size: 0x000c
 */
export const FRotatorDegrees = {
  Pitch: 0x0000n, // 0x0000 (0x0004) [float]
  Yaw: 0x0004n, // 0x0004 (0x0004) [float]
  Roll: 0x0008n, // 0x0008 (0x0004) [float]
} as const;

/**
 * Core.RotatorConversions.RotatorRadians Offsets
 * Size: 0x000c
 */
export const FRotatorRadians = {
  Pitch: 0x0000n, // 0x0000 (0x0004) [float]
  Yaw: 0x0004n, // 0x0004 (0x0004) [float]
  Roll: 0x0008n, // 0x0008 (0x0004) [float]
} as const;

/**
 * Core._Types_Core.SceNpId Offsets
 * Size: 0x0028
 */
export const FSceNpId = {
  Handle: 0x0000n, // 0x0000 (0x0018) [FSceNpOnlineId]
  Opt: 0x0018n, // 0x0018 (0x0008) [uint64]
  Reserved: 0x0020n, // 0x0020 (0x0008) [uint64]
} as const;

/**
 * Core._Types_Core.SceNpOnlineId Offsets
 * Size: 0x0014
 */
export const FSceNpOnlineId = {
  Data: 0x0000n, // 0x0000 (0x0010) [uint64]
  Term: 0x0010n, // 0x0010 (0x0001) [uint8]
  Dummy: 0x0011n, // 0x0011 (0x0003) [uint8]
} as const;

/**
 * Core.AutomationTest.ScriptWarning Offsets
 * Size: 0x0034
 */
export const FScriptWarning = {
  Node: 0x0000n, // 0x0000 (0x0010) [FString]
  Message: 0x0010n, // 0x0010 (0x0010) [FString]
  StackTrace: 0x0020n, // 0x0020 (0x0010) [FString]
  ScriptPosition: 0x0030n, // 0x0030 (0x0004) [int32]
} as const;

/**
 * Core.Object.Set_Mirror Offsets
 * Size: 0x004c
 */
export const FSet_Mirror = {
  Elements: 0x0000n, // 0x0000 (0x0038) [FSparseArray_Mirror]
  InlineHash: 0x0038n, // 0x0038 (0x0004) [int32]
  Hash: 0x0040n, // 0x0040 (0x0008) [FPointer]
  HashSize: 0x0048n, // 0x0048 (0x0004) [int32]
} as const;

/**
 * Core.Object.SHVector Offsets
 * Size: 0x0030
 */
export const FSHVector = {
  V: 0x0000n, // 0x0000 (0x0024) [float]
  Padding: 0x0024n, // 0x0024 (0x000c) [float]
} as const;

/**
 * Core.Object.SHVectorRGB Offsets
 * Size: 0x0090
 */
export const FSHVectorRGB = {
  R: 0x0000n, // 0x0000 (0x0030) [FSHVector]
  G: 0x0030n, // 0x0030 (0x0030) [FSHVector]
  B: 0x0060n, // 0x0060 (0x0030) [FSHVector]
} as const;

/**
 * Core.Object.SparseArray_Mirror Offsets
 * Size: 0x0038
 */
export const FSparseArray_Mirror = {
  Elements: 0x0000n, // 0x0000 (0x0010) [TArray<int32>]
  AllocationFlags: 0x0010n, // 0x0010 (0x0020) [FBitArray_Mirror]
  FirstFreeIndex: 0x0030n, // 0x0030 (0x0004) [int32]
  NumFreeIndices: 0x0034n, // 0x0034 (0x0004) [int32]
} as const;

/**
 * Core.Object.TAlphaBlend Offsets
 * Size: 0x0015
 */
export const FTAlphaBlend = {
  AlphaIn: 0x0000n, // 0x0000 (0x0004) [float]
  AlphaOut: 0x0004n, // 0x0004 (0x0004) [float]
  AlphaTarget: 0x0008n, // 0x0008 (0x0004) [float]
  BlendTime: 0x000cn, // 0x000c (0x0004) [float]
  BlendTimeToGo: 0x0010n, // 0x0010 (0x0004) [float]
  BlendType: 0x0014n, // 0x0014 (0x0001) [AlphaBlendType]
} as const;

/**
 * Core.Object.ThreadSafeCounter Offsets
 * Size: 0x0004
 */
export const FThreadSafeCounter = {
  Value: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * Core.Object.TPOV Offsets
 * Size: 0x001c
 */
export const FTPOV = {
  Location: 0x0000n, // 0x0000 (0x000c) [FVector]
  Rotation: 0x000cn, // 0x000c (0x000c) [FRotator]
  FOV: 0x0018n, // 0x0018 (0x0004) [float]
} as const;

/**
 * Core.Object.TwoVectors Offsets
 * Size: 0x0018
 */
export const FTwoVectors = {
  v1: 0x0000n, // 0x0000 (0x000c) [FVector]
  v2: 0x000cn, // 0x000c (0x000c) [FVector]
} as const;

/**
 * Core.Function Offsets
 * Size: 0x0160
 * Extends: Struct
 */
export const Function_ = {
  ...Struct,
} as const;

/**
 * Core._Types_Core.UniqueNetId Offsets
 * Size: 0x0042
 */
export const FUniqueNetId = {
  Uid: 0x0000n, // 0x0000 (0x0008) [uint64]
  NpId: 0x0008n, // 0x0008 (0x0028) [FSceNpId]
  EpicAccountId: 0x0030n, // 0x0030 (0x0010) [FString]
  Platform: 0x0040n, // 0x0040 (0x0001) [OnlinePlatform]
  SplitscreenID: 0x0041n, // 0x0041 (0x0001) [uint8]
} as const;

/**
 * Core.Object.UntypedBulkData_Mirror Offsets
 * Size: 0x0054
 */
export const FUntypedBulkData_Mirror = {
  VfTable: 0x0000n, // 0x0000 (0x0008) [FPointer]
  BulkDataFlags: 0x0008n, // 0x0008 (0x0004) [int32]
  ElementCount: 0x000cn, // 0x000c (0x0004) [int32]
  BulkDataOffsetInFile: 0x0010n, // 0x0010 (0x0008) [uint64]
  BulkDataSizeOnDisk: 0x0018n, // 0x0018 (0x0004) [int32]
  SavedBulkDataFlags: 0x001cn, // 0x001c (0x0004) [int32]
  SavedElementCount: 0x0020n, // 0x0020 (0x0004) [int32]
  SavedBulkDataOffsetInFile: 0x0028n, // 0x0028 (0x0008) [uint64]
  SavedBulkDataSizeOnDisk: 0x0030n, // 0x0030 (0x0004) [int32]
  BulkData: 0x0038n, // 0x0038 (0x0008) [FPointer]
  LockStatus: 0x0040n, // 0x0040 (0x0004) [int32]
  AttachedAr: 0x0048n, // 0x0048 (0x0008) [FPointer]
  bShouldFreeOnEmpty: 0x0050n, // 0x0050 (0x0004) [int32]
} as const;

/**
 * Core.Object.Vector2D Offsets
 * Size: 0x0008
 */
export const FVector2D = {
  X: 0x0000n, // 0x0000 (0x0004) [float]
  Y: 0x0004n, // 0x0004 (0x0004) [float]
} as const;

/**
 * Core.Object.Vector4 Offsets
 * Size: 0x0010
 */
export const FVector4 = {
  X: 0x0000n, // 0x0000 (0x0004) [float]
  Y: 0x0004n, // 0x0004 (0x0004) [float]
  Z: 0x0008n, // 0x0008 (0x0004) [float]
  W: 0x000cn, // 0x000c (0x0004) [float]
} as const;

/**
 * Core._Types_Core.VoiceAudioDevice Offsets
 * Size: 0x0024
 */
export const FVoiceAudioDevice = {
  Id: 0x0000n, // 0x0000 (0x0010) [FString]
  Name: 0x0010n, // 0x0010 (0x0010) [FString]
  bDefault: 0x0020n, // 0x0020 (0x0004) [bool : 0x1]
} as const;

/**
 * Core._Types_Core.VoiceRoomMemberStatus Offsets
 * Size: 0x0004
 */
export const FVoiceRoomMemberStatus = {
  bLocal: 0x0000n, // 0x0000 (0x0004) [bool : 0x1]
  bSpeaking: 0x0000n, // 0x0000 (0x0004) [bool : 0x2]
  bSelfMuted: 0x0000n, // 0x0000 (0x0004) [bool : 0x4]
  bLocalMuted: 0x0000n, // 0x0000 (0x0004) [bool : 0x8]
  bAdminMuted: 0x0000n, // 0x0000 (0x0004) [bool : 0x10]
  bBlocked: 0x0000n, // 0x0000 (0x0004) [bool : 0x20]
} as const;

/**
 * Core.Global_ORS Offsets
 * Size: 0x0078
 * Extends: Object_
 */
export const Global_ORS = {
  ...Object_,
} as const;

/**
 * Engine.ScriptGroup_ORS Offsets
 * Size: 0x0068
 * Extends: Object_
 */
export const ScriptGroup_ORS = {
  GroupOwner: 0x0060n, // 0x0060 (0x0008) [UObject*]
  ...Object_,
} as const;

/**
 * Core.Group_ORS Offsets
 * Size: 0x0138
 * Extends: ScriptGroup_ORS
 */
export const Group_ORS = {
  ...ScriptGroup_ORS,
} as const;

/**
 * Core.HelpCommandlet Offsets
 * Size: 0x00b8
 * Extends: Commandlet
 */
export const HelpCommandlet = {
  ...Commandlet,
} as const;

/**
 * Core.Interface Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const Interface = {
  ...Object_,
} as const;

/**
 * Core.IDisposable Offsets
 * Size: 0x0060
 * Extends: Interface
 */
export const IDisposable = {
  ...Interface,
} as const;

/**
 * Core.Instance_ORS Offsets
 * Size: 0x0110
 * Extends: Object_
 */
export const Instance_ORS = {
  ...Object_,
} as const;

/**
 * Core.InterfaceProperty Offsets
 * Size: 0x00d8
 * Extends: Property
 */
export const InterfaceProperty = {
  ...Property,
} as const;

/**
 * Core.IntProperty Offsets
 * Size: 0x00c8
 * Extends: Property
 */
export const IntProperty = {
  ...Property,
} as const;

/**
 * Core.Linker Offsets
 * Size: 0x01e8
 * Extends: Object_
 */
export const Linker = {
  ...Object_,
} as const;

/**
 * Core.LinkerLoad Offsets
 * Size: 0x0810
 * Extends: Linker
 */
export const LinkerLoad = {
  ...Linker,
} as const;

/**
 * Core.LinkerSave Offsets
 * Size: 0x02a8
 * Extends: Linker
 */
export const LinkerSave = {
  ...Linker,
} as const;

/**
 * Core.MapProperty Offsets
 * Size: 0x00d8
 * Extends: Property
 */
export const MapProperty = {
  ...Property,
} as const;

/**
 * Core.MetaData Offsets
 * Size: 0x00b0
 * Extends: Object_
 */
export const MetaData = {
  ...Object_,
} as const;

/**
 * Core.NameProperty Offsets
 * Size: 0x00c8
 * Extends: Property
 */
export const NameProperty = {
  ...Property,
} as const;

/**
 * Core.ObjectProvider Offsets
 * Size: 0x01e0
 * Extends: Component
 */
export const ObjectProvider = {
  VfTable_FObjectDestructionSubscriber: 0x0070n, // 0x0070 (0x0008) [FPointer]
  MyObjects: 0x0078n, // 0x0078 (0x0010) [TArray<UObject*>]
  ObjectRefs: 0x0088n, // 0x0088 (0x0050) [FMap_Mirror]
  TreeObjects: 0x00d8n, // 0x00d8 (0x0010) [TArray<UObject*>]
  SubscribedToAdds: 0x00e8n, // 0x00e8 (0x0010) [TArray<FObjectProviderSubscription>]
  SubscribedToRemoves: 0x00f8n, // 0x00f8 (0x0010) [TArray<FObjectProviderSubscription>]
  SubscribedToLists: 0x0108n, // 0x0108 (0x0010) [TArray<FObjectProviderSubscription>]
  Injections: 0x0118n, // 0x0118 (0x0010) [FArray_Mirror]
  InterfaceInjections: 0x0128n, // 0x0128 (0x0010) [FArray_Mirror]
  PendingInjectionClasses: 0x0138n, // 0x0138 (0x0010) [TArray<UObject*>]
  PendingCallbacks: 0x0148n, // 0x0148 (0x0010) [TArray<FObjectProviderPendingCallback>]
  bTriggeringCallbacks: 0x0158n, // 0x0158 (0x0001) [uint8]
  Parent: 0x0160n, // 0x0160 (0x0008) [UObjectProvider*]
  Children: 0x0168n, // 0x0168 (0x0010) [TArray<UObjectProvider*>]
  Proxies: 0x0178n, // 0x0178 (0x0010) [TArray<UObjectProvider*>]
  PendingInjectionCallbacks: 0x0188n, // 0x0188 (0x0010) [TArray<FObjectProviderPendingCallback>]
  __ObjectSubscriptionCallback__Delegate: 0x0198n, // 0x0198 (0x0018) [FScriptDelegate]
  __ObjectListSubscriptionCallback__Delegate: 0x01b0n, // 0x01b0 (0x0018) [FScriptDelegate]
  __ObjectChangeCallback__Delegate: 0x01c8n, // 0x01c8 (0x0018) [FScriptDelegate]
  ...Component,
} as const;

/**
 * Core.ObjectRedirector Offsets
 * Size: 0x0068
 * Extends: Object_
 */
export const ObjectRedirector = {
  ...Object_,
} as const;

/**
 * Core.ObjectSerializer Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const ObjectSerializer = {
  ...Object_,
} as const;

/**
 * Core.ObjectUtil Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const ObjectUtil = {
  ...Object_,
} as const;

/**
 * Core.Package Offsets
 * Size: 0x0148
 * Extends: Object_
 */
export const Package = {
  ...Object_,
} as const;

/**
 * Core.PackageMap Offsets
 * Size: 0x0118
 * Extends: Object_
 */
export const PackageMap = {
  ...Object_,
} as const;

/**
 * Core.PropertyChangeDispatcher Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const PropertyChangeDispatcher = {
  ...Object_,
} as const;

/**
 * Core.QWordProperty Offsets
 * Size: 0x00c8
 * Extends: Property
 */
export const QWordProperty = {
  ...Property,
} as const;

/**
 * Core.RotatorConversions Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const RotatorConversions = {
  ...Object_,
} as const;

/**
 * Core.ScriptStruct Offsets
 * Size: 0x0158
 * Extends: Struct
 */
export const ScriptStruct = {
  ...Struct,
} as const;

/**
 * Core.SQWordProperty Offsets
 * Size: 0x00c8
 * Extends: Property
 */
export const SQWordProperty = {
  ...Property,
} as const;

/**
 * Core.StringMap Offsets
 * Size: 0x00d8
 * Extends: Component
 */
export const StringMap = {
  Map: 0x0070n, // 0x0070 (0x0050) [FMap_Mirror]
  __PairCallback__Delegate: 0x00c0n, // 0x00c0 (0x0018) [FScriptDelegate]
  ...Component,
} as const;

/**
 * Core.StringObjectMap Offsets
 * Size: 0x00c0
 * Extends: Component
 */
export const StringObjectMap = {
  Map: 0x0070n, // 0x0070 (0x0050) [FMap_Mirror]
  ...Component,
} as const;

/**
 * Core.StrProperty Offsets
 * Size: 0x00c8
 * Extends: Property
 */
export const StrProperty = {
  ...Property,
} as const;

/**
 * Core.StructProperty Offsets
 * Size: 0x00d0
 * Extends: Property
 */
export const StructProperty = {
  ...Property,
} as const;

/**
 * Core.Subscription Offsets
 * Size: 0x0078
 * Extends: Object_
 */
export const Subscription = {
  __SubscriberCallback__Delegate: 0x0060n, // 0x0060 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Core.SubscriptionCollection_ORS Offsets
 * Size: 0x0080
 * Extends: Object_
 */
export const SubscriptionCollection_ORS = {
  ...Object_,
} as const;

/**
 * Core.Subsystem Offsets
 * Size: 0x0068
 * Extends: Object_
 */
export const Subsystem = {
  VfTable_FExec: 0x0060n, // 0x0060 (0x0008) [FPointer]
  ...Object_,
} as const;

/**
 * Core.System Offsets
 * Size: 0x0160
 * Extends: Subsystem
 */
export const System = {
  StaleCacheDays: 0x0068n, // 0x0068 (0x0004) [int32]
  MaxStaleCacheSize: 0x006cn, // 0x006c (0x0004) [int32]
  MaxOverallCacheSize: 0x0070n, // 0x0070 (0x0004) [int32]
  PackageSizeSoftLimit: 0x0074n, // 0x0074 (0x0004) [int32]
  AsyncIOBandwidthLimit: 0x0078n, // 0x0078 (0x0004) [float]
  SavePath: 0x0080n, // 0x0080 (0x0010) [FString]
  CachePath: 0x0090n, // 0x0090 (0x0010) [FString]
  CacheExt: 0x00a0n, // 0x00a0 (0x0010) [FString]
  Paths: 0x00b0n, // 0x00b0 (0x0010) [TArray<FString>]
  SeekFreePCPaths: 0x00c0n, // 0x00c0 (0x0010) [TArray<FString>]
  ScriptPaths: 0x00d0n, // 0x00d0 (0x0010) [TArray<FString>]
  FRScriptPaths: 0x00e0n, // 0x00e0 (0x0010) [TArray<FString>]
  CutdownPaths: 0x00f0n, // 0x00f0 (0x0010) [TArray<FString>]
  Suppress: 0x0100n, // 0x0100 (0x0010) [TArray<FName>]
  SuppressPublic: 0x0110n, // 0x0110 (0x0010) [TArray<FName>]
  Extensions: 0x0120n, // 0x0120 (0x0010) [TArray<FString>]
  SeekFreePCExtensions: 0x0130n, // 0x0130 (0x0010) [TArray<FString>]
  LocalizationPaths: 0x0140n, // 0x0140 (0x0010) [TArray<FString>]
  TextureFileCacheExtension: 0x0150n, // 0x0150 (0x0010) [FString]
  ...Subsystem,
} as const;

/**
 * Core.TAsyncResult Offsets
 * Size: 0x00d0
 * Extends: AsyncTask
 */
export const TAsyncResult = {
  ...AsyncTask,
} as const;

/**
 * Core.TextBuffer Offsets
 * Size: 0x0090
 * Extends: Object_
 */
export const TextBuffer = {
  ...Object_,
} as const;

/**
 * Core.TextBufferFactory Offsets
 * Size: 0x00b8
 * Extends: Factory
 */
export const TextBufferFactory = {
  ...Factory,
} as const;

/**
 * Core.UTF8 Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const UTF8 = {
  ...Object_,
} as const;
