/**
 * Global Offsets
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 *
 * These offsets are hardcoded from the SDK generation process.
 * They may need to be updated when the game is patched.
 */

/** GNames offset from module base */
export const GNames = 0x24170e8n;

/** GObjects offset from module base */
export const GObjects = 0x2417130n;
