/**
 * WinDrv Package - Offsets
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

/**
 * Core.Object Offsets
 * Size: 0x0060
 */
export const Object_ = {
  VfTableObject: 0x0000n, // 0x0000 (0x0008) [FPointer]
  HashNext: 0x0008n, // 0x0008 (0x0008) [FPointer]
  ObjectFlags: 0x0010n, // 0x0010 (0x0008) [uint64]
  HashOuterNext: 0x0018n, // 0x0018 (0x0008) [FPointer]
  StateFrame: 0x0020n, // 0x0020 (0x0008) [FPointer]
  Linker: 0x0028n, // 0x0028 (0x0008) [UObject*]
  LinkerIndex: 0x0030n, // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: 0x0038n, // 0x0038 (0x0004) [int32]
  NetIndex: 0x003cn, // 0x003c (0x0004) [int32]
  Outer: 0x0040n, // 0x0040 (0x0008) [UObject*]
  Name: 0x0048n, // 0x0048 (0x0008) [FName]
  Class: 0x0050n, // 0x0050 (0x0008) [UObject*]
  ObjectArchetype: 0x0058n, // 0x0058 (0x0008) [UObject*]
} as const;

/**
 * Engine.PlatformInterfaceBase Offsets
 * Size: 0x0088
 * Extends: Object_
 */
export const PlatformInterfaceBase = {
  AllDelegates: 0x0060n, // 0x0060 (0x0010) [TArray<FDelegateArray>]
  __PlatformInterfaceDelegate__Delegate: 0x0070n, // 0x0070 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Engine.FacebookIntegration Offsets
 * Size: 0x00e8
 * Extends: PlatformInterfaceBase
 */
export const FacebookIntegration = {
  AppID: 0x0088n, // 0x0088 (0x0010) [FString]
  Permissions: 0x0098n, // 0x0098 (0x0010) [TArray<FString>]
  Username: 0x00a8n, // 0x00a8 (0x0010) [FString]
  UserId: 0x00b8n, // 0x00b8 (0x0010) [FString]
  AccessToken: 0x00c8n, // 0x00c8 (0x0010) [FString]
  FriendsList: 0x00d8n, // 0x00d8 (0x0010) [TArray<FFacebookFriend>]
  ...PlatformInterfaceBase,
} as const;

/**
 * WinDrv.FacebookWindows Offsets
 * Size: 0x00f8
 * Extends: FacebookIntegration
 */
export const FacebookWindows = {
  VfTable_FTickableObject: 0x00e8n, // 0x00e8 (0x0008) [FPointer]
  ChildProcHandle: 0x00f0n, // 0x00f0 (0x0008) [FPointer]
  ...FacebookIntegration,
} as const;

/**
 * Engine.HttpBaseInterface Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const HttpBaseInterface = {
  ...Object_,
} as const;

/**
 * Engine.HttpRequestInterface Offsets
 * Size: 0x0078
 * Extends: HttpBaseInterface
 */
export const HttpRequestInterface = {
  __OnProcessRequestComplete__Delegate: 0x0060n, // 0x0060 (0x0018) [FScriptDelegate]
  ...HttpBaseInterface,
} as const;

/**
 * WinDrv.HttpRequestWindows Offsets
 * Size: 0x00a8
 * Extends: HttpRequestInterface
 */
export const HttpRequestWindows = {
  Request: 0x0078n, // 0x0078 (0x0008) [FPointer]
  RequestVerb: 0x0080n, // 0x0080 (0x0010) [FString]
  RequestURL: 0x0090n, // 0x0090 (0x0008) [FPointer]
  Payload: 0x0098n, // 0x0098 (0x0010) [TArray<uint8>]
  ...HttpRequestInterface,
} as const;

/**
 * WinDrv.HttpRequestWindowsMcp Offsets
 * Size: 0x00c8
 * Extends: HttpRequestWindows
 */
export const HttpRequestWindowsMcp = {
  AppID: 0x00a8n, // 0x00a8 (0x0010) [FString]
  AppSecret: 0x00b8n, // 0x00b8 (0x0010) [FString]
  ...HttpRequestWindows,
} as const;

/**
 * Engine.HttpResponseInterface Offsets
 * Size: 0x0060
 * Extends: HttpBaseInterface
 */
export const HttpResponseInterface = {
  ...HttpBaseInterface,
} as const;

/**
 * WinDrv.HttpResponseWindows Offsets
 * Size: 0x0078
 * Extends: HttpResponseInterface
 */
export const HttpResponseWindows = {
  Response: 0x0060n, // 0x0060 (0x0008) [FPointer]
  Payload: 0x0068n, // 0x0068 (0x0010) [TArray<uint8>]
  ...HttpResponseInterface,
} as const;

/**
 * Engine.Client Offsets
 * Size: 0x0078
 * Extends: Object_
 */
export const Client = {
  MinDesiredFrameRate: 0x0068n, // 0x0068 (0x0004) [float]
  DisplayGamma: 0x006cn, // 0x006c (0x0004) [float]
  InitialButtonRepeatDelay: 0x0070n, // 0x0070 (0x0004) [float]
  ButtonRepeatDelay: 0x0074n, // 0x0074 (0x0004) [float]
  ...Object_,
} as const;

/**
 * WinDrv.WindowsClient Offsets
 * Size: 0x03c0
 * Extends: Client
 */
export const WindowsClient = {
  AudioDeviceClass: 0x0278n, // 0x0278 (0x0008) [UAudioDevice*]
  AllowJoystickInput: 0x02b8n, // 0x02b8 (0x0004) [int32]
  ...Client,
} as const;

/**
 * Engine.ForceFeedbackManager Offsets
 * Size: 0x0098
 * Extends: Object_
 */
export const ForceFeedbackManager = {
  bAllowsForceFeedback: 0x0060n, // 0x0060 (0x0004) [bool : 0x1]
  bIsPaused: 0x0060n, // 0x0060 (0x0004) [bool : 0x2]
  FFWaveform: 0x0068n, // 0x0068 (0x0008) [UForceFeedbackWaveform*]
  CurrentSample: 0x0070n, // 0x0070 (0x0004) [int32]
  ElapsedTime: 0x0074n, // 0x0074 (0x0004) [float]
  ScaleAllWaveformsBy: 0x0078n, // 0x0078 (0x0004) [float]
  WaveformInstigator: 0x0080n, // 0x0080 (0x0008) [UActor*]
  ShakeLeft: 0x0088n, // 0x0088 (0x0004) [int32]
  ShakeRight: 0x008cn, // 0x008c (0x0004) [int32]
  EnableTime: 0x0090n, // 0x0090 (0x0004) [float]
  EnabledTimeRemaining: 0x0094n, // 0x0094 (0x0004) [float]
  ...Object_,
} as const;

/**
 * WinDrv.XnaForceFeedbackManager Offsets
 * Size: 0x00b0
 * Extends: ForceFeedbackManager
 */
export const XnaForceFeedbackManager = {
  ...ForceFeedbackManager,
} as const;
