/**
 * XAudio2 Package - Offsets
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

/**
 * Core.Object Offsets
 * Size: 0x0060
 */
export const Object_ = {
  VfTableObject: 0x0000n, // 0x0000 (0x0008) [FPointer]
  HashNext: 0x0008n, // 0x0008 (0x0008) [FPointer]
  ObjectFlags: 0x0010n, // 0x0010 (0x0008) [uint64]
  HashOuterNext: 0x0018n, // 0x0018 (0x0008) [FPointer]
  StateFrame: 0x0020n, // 0x0020 (0x0008) [FPointer]
  Linker: 0x0028n, // 0x0028 (0x0008) [UObject*]
  LinkerIndex: 0x0030n, // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: 0x0038n, // 0x0038 (0x0004) [int32]
  NetIndex: 0x003cn, // 0x003c (0x0004) [int32]
  Outer: 0x0040n, // 0x0040 (0x0008) [UObject*]
  Name: 0x0048n, // 0x0048 (0x0008) [FName]
  Class: 0x0050n, // 0x0050 (0x0008) [UObject*]
  ObjectArchetype: 0x0058n, // 0x0058 (0x0008) [UObject*]
} as const;

/**
 * Core.Subsystem Offsets
 * Size: 0x0068
 * Extends: Object_
 */
export const Subsystem = {
  VfTable_FExec: 0x0060n, // 0x0060 (0x0008) [FPointer]
  ...Object_,
} as const;

/**
 * Engine.AudioDevice Offsets
 * Size: 0x03a4
 * Extends: Subsystem
 */
export const AudioDevice = {
  MaxChannels: 0x0068n, // 0x0068 (0x0004) [int32]
  CommonAudioPoolSize: 0x006cn, // 0x006c (0x0004) [int32]
  LowPassFilterResonance: 0x0070n, // 0x0070 (0x0004) [float]
  MinCompressedDurationEditor: 0x0074n, // 0x0074 (0x0004) [float]
  MinCompressedDurationGame: 0x0078n, // 0x0078 (0x0004) [float]
  ChirpInSoundNodeWaveName: 0x0080n, // 0x0080 (0x0010) [FString]
  ChirpInSoundNodeWave: 0x0090n, // 0x0090 (0x0008) [USoundNodeWave*]
  ChirpOutSoundNodeWaveName: 0x0098n, // 0x0098 (0x0010) [FString]
  ChirpOutSoundNodeWave: 0x00a8n, // 0x00a8 (0x0008) [USoundNodeWave*]
  CommonAudioPool: 0x00b0n, // 0x00b0 (0x0008) [FPointer]
  CommonAudioPoolFreeBytes: 0x00b8n, // 0x00b8 (0x0004) [int32]
  AudioComponents: 0x00c0n, // 0x00c0 (0x0010) [TArray<UAudioComponent*>]
  Sources: 0x00d0n, // 0x00d0 (0x0010) [TArray<FPointer>]
  FreeSources: 0x00e0n, // 0x00e0 (0x0010) [TArray<FPointer>]
  WaveInstanceSourceMap: 0x00f0n, // 0x00f0 (0x0050) [FMap_Mirror]
  bGameWasTicking: 0x0140n, // 0x0140 (0x0004) [bool : 0x1]
  bSoundSpawningEnabled: 0x0140n, // 0x0140 (0x0004) [bool : 0x2]
  Listeners: 0x0148n, // 0x0148 (0x0010) [TArray<FListener>]
  CurrentTick: 0x0158n, // 0x0158 (0x0008) [uint64]
  SoundClasses: 0x0160n, // 0x0160 (0x0050) [FMap_Mirror]
  SourceSoundClasses: 0x01b0n, // 0x01b0 (0x0050) [FMap_Mirror]
  CurrentSoundClasses: 0x0200n, // 0x0200 (0x0050) [FMap_Mirror]
  DestinationSoundClasses: 0x0250n, // 0x0250 (0x0050) [FMap_Mirror]
  SoundModes: 0x02a0n, // 0x02a0 (0x0050) [FMap_Mirror]
  Effects: 0x02f0n, // 0x02f0 (0x0008) [FPointer]
  BaseSoundModeName: 0x02f8n, // 0x02f8 (0x0008) [FName]
  CurrentMode: 0x0300n, // 0x0300 (0x0008) [USoundMode*]
  SoundModeStartTime: 0x0308n, // 0x0308 (0x0008) [FDouble]
  SoundModeFadeInStartTime: 0x0310n, // 0x0310 (0x0008) [FDouble]
  SoundModeFadeInEndTime: 0x0318n, // 0x0318 (0x0008) [FDouble]
  SoundModeEndTime: 0x0320n, // 0x0320 (0x0008) [FDouble]
  ListenerVolumeIndex: 0x0328n, // 0x0328 (0x0004) [int32]
  ListenerInteriorSettings: 0x032cn, // 0x032c (0x0024) [FInteriorSettings]
  InteriorStartTime: 0x0350n, // 0x0350 (0x0008) [FDouble]
  InteriorEndTime: 0x0358n, // 0x0358 (0x0008) [FDouble]
  ExteriorEndTime: 0x0360n, // 0x0360 (0x0008) [FDouble]
  InteriorLPFEndTime: 0x0368n, // 0x0368 (0x0008) [FDouble]
  ExteriorLPFEndTime: 0x0370n, // 0x0370 (0x0008) [FDouble]
  InteriorVolumeInterp: 0x0378n, // 0x0378 (0x0004) [float]
  InteriorLPFInterp: 0x037cn, // 0x037c (0x0004) [float]
  ExteriorVolumeInterp: 0x0380n, // 0x0380 (0x0004) [float]
  ExteriorLPFInterp: 0x0384n, // 0x0384 (0x0004) [float]
  TestAudioComponent: 0x0388n, // 0x0388 (0x0008) [UAudioComponent*]
  TextToSpeech: 0x0390n, // 0x0390 (0x0008) [FPointer]
  DebugState: 0x0398n, // 0x0398 (0x0001) [EDebugState]
  TransientMasterVolume: 0x039cn, // 0x039c (0x0004) [float]
  LastUpdateTime: 0x03a0n, // 0x03a0 (0x0004) [float]
  ...Subsystem,
} as const;

/**
 * XAudio2.XAudio2Device Offsets
 * Size: 0x0460
 * Extends: AudioDevice
 */
export const XAudio2Device = {
  ...AudioDevice,
} as const;
