/**
 * OnlineSubsystemEOS Package - Structs
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

import type { FScriptDelegate } from '../types/GameDefines';

/**
 * ScriptStruct OnlineSubsystemEOS.OnlinePlayerInterfaceEOS.LoginDelegates
 * Size: 0x0010
 */
export type FLoginDelegates = {
  Delegates: FScriptDelegate[]; // 0x0000 (0x0010) [TArray<FScriptDelegate>]
};

/**
 * ScriptStruct OnlineSubsystemEOS.OnlinePlayerInterfaceEOS.OnlineStatusMappingEOS
 * Size: 0x0018
 */
export type FOnlineStatusMappingEOS = {
  StatusId: number; // 0x0000 (0x0004) [int32]
  StatusString: string; // 0x0008 (0x0010) [FString]
};
