/**
 * OnlineSubsystemSteamworks Package - Structs
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

import type { FName, FScriptDelegate } from '../types/GameDefines';
import type { UHttpRequestInterface, UOnlineGameSearch, UOnlineGameSettings, UOnlineProfileSettings } from '../classes/Engine';
import type { EOnlineGameSearchEntryType } from '../enums/Engine';
import type { ELeaderboardFormat, ELeaderboardSortType, ELeaderboardUpdateType, EMuteType, ESteamMatchmakingType } from '../enums/OnlineSubsystemSteamworks';
import type { FMultiMap_Mirror, FPointer, FUniqueNetId } from './Core';
import type { FEmsFile, FLocalTalker, FOnlinePlayerScore, FSettingsData, FTitleFile } from './Engine';

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.AchievementMappingInfo
 * Size: 0x001C
 */
export type FAchievementMappingInfo = {
  AchievementId: number; // 0x0000 (0x0004) [int32]
  AchievementName: FName; // 0x0004 (0x0008) [FName]
  ViewId: number; // 0x000c (0x0004) [int32]
  ProgressCount: number; // 0x0010 (0x0004) [int32]
  MaxProgress: number; // 0x0014 (0x0004) [int32]
  bAutoUnlock: boolean; // 0x0018 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.AchievementProgressStat
 * Size: 0x0010
 */
export type FAchievementProgressStat = {
  AchievementId: number; // 0x0000 (0x0004) [int32]
  Progress: number; // 0x0004 (0x0004) [int32]
  MaxProgress: number; // 0x0008 (0x0004) [int32]
  bUnlock: boolean; // 0x000c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlinePurchaseInterfaceSteamworks.AppPriceInfoRequest
 * Size: 0x0030
 */
export type FAppPriceInfoRequest = {
  HTTPRequest: UHttpRequestInterface; // 0x0000 (0x0008) [UHttpRequestInterface*]
  AppNames: FName[]; // 0x0008 (0x0010) [TArray<FName>]
  Callback: FScriptDelegate; // 0x0018 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineGameInterfaceSteamworks.ClientFilterORClause
 * Size: 0x0050
 */
export type FClientFilterORClause = {
  OrParams: FMultiMap_Mirror; // 0x0000 (0x0050) [FMultiMap_Mirror]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ControllerConnectionState
 * Size: 0x0008
 */
export type FControllerConnectionState = {
  bIsControllerConnected: number; // 0x0000 (0x0004) [int32]
  bLastIsControllerConnected: number; // 0x0004 (0x0004) [int32]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.DeferredLeaderboardRead
 * Size: 0x0030
 */
export type FDeferredLeaderboardRead = {
  LeaderboardName: string; // 0x0000 (0x0010) [FString]
  RequestType: number; // 0x0010 (0x0001) [uint8]
  Start: number; // 0x0014 (0x0004) [int32]
  End: number; // 0x0018 (0x0004) [int32]
  PlayerList: FUniqueNetId[]; // 0x0020 (0x0010) [TArray<FUniqueNetId>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.DeferredLeaderboardWrite
 * Size: 0x0028
 */
export type FDeferredLeaderboardWrite = {
  LeaderboardName: string; // 0x0000 (0x0010) [FString]
  Score: number; // 0x0010 (0x0004) [int32]
  LeaderboardData: number[]; // 0x0018 (0x0010) [TArray<int32>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.DeviceIdCache
 * Size: 0x0030
 */
export type FDeviceIdCache = {
  DeviceID: number; // 0x0000 (0x0004) [int32]
  DeviceSelectionMulticast: FScriptDelegate; // 0x0008 (0x0018) [FScriptDelegate]
  DeviceSelectionDelegates: FScriptDelegate[]; // 0x0020 (0x0010) [TArray<FScriptDelegate>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineGameInterfaceSteamworks.FilterKeyToSteamKeyMapping
 * Size: 0x0040
 */
export type FFilterKeyToSteamKeyMapping = {
  KeyId: number; // 0x0000 (0x0004) [int32]
  KeyType: EOnlineGameSearchEntryType; // 0x0004 (0x0001) [EOnlineGameSearchEntryType]
  RawKey: string; // 0x0008 (0x0010) [FString]
  SteamKey: string; // 0x0018 (0x0010) [FString]
  bReverseFilter: boolean; // 0x0028 (0x0004) [bool : 0x1]
  IgnoreValue: string; // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.LeaderboardEntry
 * Size: 0x0060
 */
export type FLeaderboardEntry = {
  PlayerUID: FUniqueNetId; // 0x0000 (0x0048) [FUniqueNetId]
  Rank: number; // 0x0048 (0x0004) [int32]
  Score: number; // 0x004c (0x0004) [int32]
  LeaderboardData: number[]; // 0x0050 (0x0010) [TArray<int32>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.LeaderboardHandle
 * Size: 0x0008
 */
export type FLeaderboardHandle = {
  Dud: bigint; // 0x0000 (0x0008) [uint64]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.LeaderboardTemplate
 * Size: 0x002C
 */
export type FLeaderboardTemplate = {
  LeaderboardName: string; // 0x0000 (0x0010) [FString]
  UpdateType: ELeaderboardUpdateType; // 0x0010 (0x0001) [ELeaderboardUpdateType]
  LeaderboardSize: number; // 0x0014 (0x0004) [int32]
  SortType: ELeaderboardSortType; // 0x0018 (0x0001) [ELeaderboardSortType]
  DisplayFormat: ELeaderboardFormat; // 0x0019 (0x0001) [ELeaderboardFormat]
  LeaderboardRef: FLeaderboardHandle; // 0x0020 (0x0008) [FLeaderboardHandle]
  bLeaderboardInitializing: boolean; // 0x0028 (0x0004) [bool : 0x1]
  bLeaderboardInitiated: boolean; // 0x0028 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.LocalTalkerSteam
 * Size: 0x0051
 */
export type FLocalTalkerSteam = FLocalTalker & {
  MuteType: EMuteType; // 0x0050 (0x0001) [EMuteType]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineGameInterfaceSteamworks.MatchmakingQueryState
 * Size: 0x0078
 */
export type FMatchmakingQueryState = {
  GameSearch: UOnlineGameSearch; // 0x0000 (0x0008) [UOnlineGameSearch*]
  QueryToRulesResponseMap: FServerQueryToRulesResponseMapping[]; // 0x0008 (0x0010) [TArray<FServerQueryToRulesResponseMapping>]
  QueryToPingResponseMap: FServerQueryToPingResponseMapping[]; // 0x0018 (0x0010) [TArray<FServerQueryToPingResponseMapping>]
  ServerListResponse: FPointer; // 0x0028 (0x0008) [FPointer]
  CurrentMatchmakingType: ESteamMatchmakingType; // 0x0030 (0x0001) [ESteamMatchmakingType]
  CurrentMatchmakingQuery: FPointer; // 0x0038 (0x0008) [FPointer]
  ActiveClientsideFilters: FClientFilterORClause[]; // 0x0040 (0x0010) [TArray<FClientFilterORClause>]
  PendingRulesSearchSettings: UOnlineGameSettings[]; // 0x0050 (0x0010) [TArray<UOnlineGameSettings*>]
  PendingPingSearchSettings: UOnlineGameSettings[]; // 0x0060 (0x0010) [TArray<UOnlineGameSettings*>]
  bIgnoreRefreshComplete: boolean; // 0x0070 (0x0004) [bool : 0x1]
  LastActivityTimestamp: number; // 0x0074 (0x0004) [float]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.OnlineStatusMapping
 * Size: 0x0018
 */
export type FOnlineStatusMapping = {
  StatusId: number; // 0x0000 (0x0004) [int32]
  StatusString: string; // 0x0008 (0x0010) [FString]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.PendingPlayerStats
 * Size: 0x00D8
 */
export type FPendingPlayerStats = {
  Player: FUniqueNetId; // 0x0000 (0x0048) [FUniqueNetId]
  PlayerName: string; // 0x0048 (0x0010) [FString]
  StatGuid: string; // 0x0058 (0x0010) [FString]
  Stats: FPlayerStat[]; // 0x0068 (0x0010) [TArray<FPlayerStat>]
  Score: FOnlinePlayerScore; // 0x0078 (0x0050) [FOnlinePlayerScore]
  Place: string; // 0x00c8 (0x0010) [FString]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.PlayerStat
 * Size: 0x0018
 */
export type FPlayerStat = {
  ViewId: number; // 0x0000 (0x0004) [int32]
  ColumnId: number; // 0x0004 (0x0004) [int32]
  Data: FSettingsData; // 0x0008 (0x0010) [FSettingsData]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ProfileSettingsCache
 * Size: 0x0038
 */
export type FProfileSettingsCache = {
  Profile: UOnlineProfileSettings; // 0x0000 (0x0008) [UOnlineProfileSettings*]
  ReadDelegates: FScriptDelegate[]; // 0x0008 (0x0010) [TArray<FScriptDelegate>]
  WriteDelegates: FScriptDelegate[]; // 0x0018 (0x0010) [TArray<FScriptDelegate>]
  ProfileDataChangedDelegates: FScriptDelegate[]; // 0x0028 (0x0010) [TArray<FScriptDelegate>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.QueuedAvatarRequest
 * Size: 0x0070
 */
export type FQueuedAvatarRequest = {
  CheckTime: number; // 0x0000 (0x0004) [float]
  NumberOfAttempts: number; // 0x0004 (0x0004) [int32]
  PlayerNetId: FUniqueNetId; // 0x0008 (0x0048) [FUniqueNetId]
  Size: number; // 0x0050 (0x0004) [int32]
  ReadOnlineAvatarCompleteDelegate: FScriptDelegate; // 0x0058 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineGameInterfaceSteamworks.ServerQueryToPingResponseMapping
 * Size: 0x0010
 */
export type FServerQueryToPingResponseMapping = {
  Query: number; // 0x0000 (0x0004) [int32]
  Response: FPointer; // 0x0008 (0x0008) [FPointer]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineGameInterfaceSteamworks.ServerQueryToRulesResponseMapping
 * Size: 0x0010
 */
export type FServerQueryToRulesResponseMapping = {
  Query: number; // 0x0000 (0x0004) [int32]
  Response: FPointer; // 0x0008 (0x0008) [FPointer]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.SteamPlayerClanData
 * Size: 0x0020
 */
export type FSteamPlayerClanData = {
  ClanName: string; // 0x0000 (0x0010) [FString]
  ClanTag: string; // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.SteamUserCloud
 * Size: 0x0020
 */
export type FSteamUserCloud = {
  UserId: string; // 0x0000 (0x0010) [FString]
  UserCloudFileData: FTitleFile[]; // 0x0010 (0x0010) [TArray<FTitleFile>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.SteamUserCloudMetadata
 * Size: 0x0020
 */
export type FSteamUserCloudMetadata = {
  UserId: string; // 0x0000 (0x0010) [FString]
  UserCloudMetadata: FEmsFile[]; // 0x0010 (0x0010) [TArray<FEmsFile>]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ViewIdToLeaderboardName
 * Size: 0x0018
 */
export type FViewIdToLeaderboardName = {
  ViewId: number; // 0x0000 (0x0004) [int32]
  LeaderboardName: string; // 0x0008 (0x0010) [FString]
};

/**
 * ScriptStruct OnlineSubsystemSteamworks.OnlineCommunityContentInterfaceSteamworks.WorkshopItemData
 * Size: 0x00A0
 */
export type FWorkshopItemData = {
  Title: string; // 0x0000 (0x0010) [FString]
  Description: string; // 0x0010 (0x0010) [FString]
  MetaData: string; // 0x0020 (0x0010) [FString]
  Content: string; // 0x0030 (0x0010) [FString]
  Preview: string; // 0x0040 (0x0010) [FString]
  Tags: string; // 0x0050 (0x0010) [FString]
  AddPairs: string; // 0x0060 (0x0010) [FString]
  RemovePairs: string; // 0x0070 (0x0010) [FString]
  Visibility: number; // 0x0080 (0x0004) [int32]
  ItemID: bigint; // 0x0088 (0x0008) [uint64]
  bIsUploading: boolean; // 0x0090 (0x0004) [bool : 0x1]
  UpdateHandle: bigint; // 0x0098 (0x0008) [uint64]
};
