/**
 * AkAudio Package - Function Parameters
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

import type { FName, FScriptDelegate } from '../types/GameDefines';
import type { UAkEnvironments, UAkMusicAnalysis, UAkRevPhysicsSimulation, UAkSoundBanksInfo, UAkSoundCue, UAkSoundSource, USeqEvent_AkMusicCue } from '../classes/AkAudio';
import type { UDebugDrawer, UObject } from '../classes/Core';
import type { UActor, ULocalPlayer, USeqAct_Toggle, UWorldInfo } from '../classes/Engine';
import type { EAkDynamicRangeType, EAkEnvironmentType, EAkListenerSpacialization, EAkOutputType, EAttenuationType, EBusEmitterType, EPinnedAxisType } from '../enums/AkAudio';
import type { FAkEnvironment, FAkRevSimFrame, FAkRevSimUpdateParams, FMusicAnalysisInfo } from '../structs/AkAudio';
import type { FLinearColor, FRotator, FVector } from '../structs/Core';

/**
 * Function AkAudio.AkAmbientSoundActor.OnToggle
 */
export type AkAmbientSoundActor_OnToggle_Params = {
  Action: USeqAct_Toggle; // 0x0000 (0x0008) [USeqAct_Toggle*] [CPF_Parm]
};

/**
 * Function AkAudio.AkBusActor.RegisterReflectionEmitter
 */
export type AkBusActor_RegisterReflectionEmitter_Params = {
  BusName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  BusType: EBusEmitterType; // 0x0008 (0x0001) [EBusEmitterType] [CPF_Parm]
};

/**
 * Function AkAudio.AkBusActor.SetPinnedAxis
 */
export type AkBusActor_SetPinnedAxis_Params = {
  AxisToPin: EPinnedAxisType; // 0x0000 (0x0001) [EPinnedAxisType] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.EventInitialized
 */
export type AkDevice_EventInitialized_Params = {};

/**
 * Function AkAudio.AkDevice.GetEnvironments
 */
export type AkDevice_GetEnvironments_Params = {
  ReturnValue: UAkEnvironments; // 0x0000 (0x0008) [UAkEnvironments*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkDevice.GetSoundSource
 */
export type AkDevice_GetSoundSource_Params = {
  SourceActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  Translation: FVector; // 0x0008 (0x000c) [FVector] [CPF_Parm | CPF_OptionalParm]
  Rotation: FRotator; // 0x0014 (0x000c) [FRotator] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UAkSoundSource; // 0x0020 (0x0008) [UAkSoundSource*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkDevice.NotifyWhenInitialized
 */
export type AkDevice_NotifyWhenInitialized_Params = {
  Callback: FScriptDelegate; // 0x0000 (0x0018) [FScriptDelegate] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.PlayGlobalSound
 */
export type AkDevice_PlayGlobalSound_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.PlaySound
 */
export type AkDevice_PlaySound_Params = {
  SourceActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  Sound: UAkSoundCue; // 0x0008 (0x0008) [UAkSoundCue*] [CPF_Parm]
  Translation: FVector; // 0x0010 (0x000c) [FVector] [CPF_Parm | CPF_OptionalParm]
  Rotation: FRotator; // 0x001c (0x000c) [FRotator] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UAkSoundSource; // 0x0028 (0x0008) [UAkSoundSource*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkDevice.PrintData
 */
export type AkDevice_PrintData_Params = {};

/**
 * Function AkAudio.AkDevice.ProfileStart
 */
export type AkDevice_ProfileStart_Params = {};

/**
 * Function AkAudio.AkDevice.ProfileStop
 */
export type AkDevice_ProfileStop_Params = {};

/**
 * Function AkAudio.AkDevice.ResetSlapbackObjects
 */
export type AkDevice_ResetSlapbackObjects_Params = {};

/**
 * Function AkAudio.AkDevice.SetBusEffect
 */
export type AkDevice_SetBusEffect_Params = {
  BusName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  EffectSetting: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  EffectSlot: number; // 0x0010 (0x0004) [int32] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function AkAudio.AkDevice.SetDynamicRange
 */
export type AkDevice_SetDynamicRange_Params = {
  Type: EAkDynamicRangeType; // 0x0000 (0x0001) [EAkDynamicRangeType] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetGlobalRTCP
 */
export type AkDevice_SetGlobalRTCP_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetListenerSpatialization
 */
export type AkDevice_SetListenerSpatialization_Params = {
  Player: ULocalPlayer; // 0x0000 (0x0008) [ULocalPlayer*] [CPF_Parm]
  Value: EAkListenerSpacialization; // 0x0008 (0x0001) [EAkListenerSpacialization] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetOutputType
 */
export type AkDevice_SetOutputType_Params = {
  Type: EAkOutputType; // 0x0000 (0x0001) [EAkOutputType] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetRTCP
 */
export type AkDevice_SetRTCP_Params = {
  SourceActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  Key: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0010 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSoundEnvironment
 */
export type AkDevice_SetSoundEnvironment_Params = {
  Actor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  EnvironmentType: EAkEnvironmentType; // 0x0008 (0x0001) [EAkEnvironmentType] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSplitScreenListenerEnabled
 */
export type AkDevice_SetSplitScreenListenerEnabled_Params = {
  bEnable: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSplitScreenListenerPosition
 */
export type AkDevice_SetSplitScreenListenerPosition_Params = {
  Location: FVector; // 0x0000 (0x000c) [FVector] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetState
 */
export type AkDevice_SetState_Params = {
  InStateGroup: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  InState: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSwitch
 */
export type AkDevice_SetSwitch_Params = {
  SourceActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  Key: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  Value: FName; // 0x0010 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.StopAllSounds
 */
export type AkDevice_StopAllSounds_Params = {
  SourceActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.StopGlobalSound
 */
export type AkDevice_StopGlobalSound_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.StopSound
 */
export type AkDevice_StopSound_Params = {
  SourceActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  Sound: UAkSoundCue; // 0x0008 (0x0008) [UAkSoundCue*] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.UpdateSecondaryOutputs
 */
export type AkDevice_UpdateSecondaryOutputs_Params = {};

/**
 * Function AkAudio.AkEnvironments.AddActorEnvironment
 */
export type AkEnvironments_AddActorEnvironment_Params = {
  TargetActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  Environment: FAkEnvironment; // 0x0008 (0x0020) [FAkEnvironment] [CPF_Parm | CPF_OutParm]
};

/**
 * Function AkAudio.AkEnvironments.AddLevelDefault
 */
export type AkEnvironments_AddLevelDefault_Params = {
  Environment: FAkEnvironment; // 0x0000 (0x0020) [FAkEnvironment] [CPF_Parm | CPF_OutParm]
};

/**
 * Function AkAudio.AkEnvironments.RemoveActorEnvironment
 */
export type AkEnvironments_RemoveActorEnvironment_Params = {
  TargetActor: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  EnvironmentID: string; // 0x0008 (0x0010) [FString] [CPF_Parm | CPF_OutParm]
};

/**
 * Function AkAudio.AkMusicAnalysis.EventMusicBar
 */
export type AkMusicAnalysis_EventMusicBar_Params = {};

/**
 * Function AkAudio.AkMusicAnalysis.EventMusicBeat
 */
export type AkMusicAnalysis_EventMusicBeat_Params = {};

/**
 * Function AkAudio.AkMusicAnalysis.EventNewMusicTrack
 */
export type AkMusicAnalysis_EventNewMusicTrack_Params = {
  PlayingID: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  NewBPM: number; // 0x0004 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicAnalysis.GetInstance
 */
export type AkMusicAnalysis_GetInstance_Params = {
  ReturnValue: UAkMusicAnalysis; // 0x0000 (0x0008) [UAkMusicAnalysis*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkMusicAnalysis.OnNewTrack
 */
export type AkMusicAnalysis_OnNewTrack_Params = {
  NewBPM: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicAnalysis.UpdateMusicInfo
 */
export type AkMusicAnalysis_UpdateMusicInfo_Params = {
  NewValues: FMusicAnalysisInfo; // 0x0000 (0x0020) [FMusicAnalysisInfo] [CPF_Parm | CPF_OutParm]
};

/**
 * Function AkAudio.AkMusicAnalysis.UpdateSmoothedMusicInfo
 */
export type AkMusicAnalysis_UpdateSmoothedMusicInfo_Params = {
  DeltaTime: number; // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.EventTrackEnd
 */
export type AkMusicDevice_EventTrackEnd_Params = {
  PlayingID: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.EventTrackStart
 */
export type AkMusicDevice_EventTrackStart_Params = {
  PlayingID: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  FileMarker: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.Play
 */
export type AkMusicDevice_Play_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
  ReturnValue: number; // 0x0008 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkMusicDevice.Seek
 */
export type AkMusicDevice_Seek_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
  PositionSeconds: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.SetRTCP
 */
export type AkMusicDevice_SetRTCP_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.Stop
 */
export type AkMusicDevice_Stop_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.StopPlayingID
 */
export type AkMusicDevice_StopPlayingID_Params = {
  PlayingID: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.DisableObjectAttenuation
 */
export type AkParamGroup_DisableObjectAttenuation_Params = {};

/**
 * Function AkAudio.AkParamGroup.EnableObjectAttenuation
 */
export type AkParamGroup_EnableObjectAttenuation_Params = {};

/**
 * Function AkAudio.AkParamGroup.GetDebugData
 */
export type AkParamGroup_GetDebugData_Params = {
  RTCPKeys: FName[]; // 0x0000 (0x0010) [TArray<FName>] [CPF_Parm | CPF_OutParm]
  RTCPValues: number[]; // 0x0010 (0x0010) [TArray<float>] [CPF_Parm | CPF_OutParm]
  SwitchKeys: FName[]; // 0x0020 (0x0010) [TArray<FName>] [CPF_Parm | CPF_OutParm]
  SwitchValues: FName[]; // 0x0030 (0x0010) [TArray<FName>] [CPF_Parm | CPF_OutParm]
};

/**
 * Function AkAudio.AkParamGroup.PlaySound
 */
export type AkParamGroup_PlaySound_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
  Translation: FVector; // 0x0008 (0x000c) [FVector] [CPF_Parm | CPF_OptionalParm]
  Rotation: FRotator; // 0x0014 (0x000c) [FRotator] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UAkSoundSource; // 0x0020 (0x0008) [UAkSoundSource*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkParamGroup.PrintDebugInfo
 */
export type AkParamGroup_PrintDebugInfo_Params = {
  Drawer: UDebugDrawer; // 0x0000 (0x0008) [UDebugDrawer*] [CPF_Parm]
  RTCPKeys: FName[]; // 0x0008 (0x0010) [TArray<FName>]
  RTCPValues: number[]; // 0x0018 (0x0010) [TArray<float>]
  SwitchKeys: FName[]; // 0x0028 (0x0010) [TArray<FName>]
  SwitchValues: FName[]; // 0x0038 (0x0010) [TArray<FName>]
  Idx: number; // 0x0048 (0x0004) [int32]
};

/**
 * Function AkAudio.AkParamGroup.SetActorParameter
 */
export type AkParamGroup_SetActorParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: UActor; // 0x0008 (0x0008) [UActor*] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetControllerId
 */
export type AkParamGroup_SetControllerId_Params = {
  InID: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetFloatParameter
 */
export type AkParamGroup_SetFloatParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetLinearColorParameter
 */
export type AkParamGroup_SetLinearColorParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FLinearColor; // 0x0008 (0x0010) [FLinearColor] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetNameParameter
 */
export type AkParamGroup_SetNameParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetRTCP
 */
export type AkParamGroup_SetRTCP_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetSendToSlapbacks
 */
export type AkParamGroup_SetSendToSlapbacks_Params = {
  bSend: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetSwitch
 */
export type AkParamGroup_SetSwitch_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetVectorParameter
 */
export type AkParamGroup_SetVectorParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FVector; // 0x0008 (0x000c) [FVector] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.StopSound
 */
export type AkParamGroup_StopSound_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.UpdateSoundSourceAttenuationScaling
 */
export type AkParamGroup_UpdateSoundSourceAttenuationScaling_Params = {};

/**
 * Function AkAudio.AkPlaySoundComponent.IsPlaying
 */
export type AkPlaySoundComponent_IsPlaying_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.Play
 */
export type AkPlaySoundComponent_Play_Params = {};

/**
 * Function AkAudio.AkPlaySoundComponent.SetActorParameter
 */
export type AkPlaySoundComponent_SetActorParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: UActor; // 0x0008 (0x0008) [UActor*] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetFloatParameter
 */
export type AkPlaySoundComponent_SetFloatParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetLinearColorParameter
 */
export type AkPlaySoundComponent_SetLinearColorParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FLinearColor; // 0x0008 (0x0010) [FLinearColor] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetNameParameter
 */
export type AkPlaySoundComponent_SetNameParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetRTCP
 */
export type AkPlaySoundComponent_SetRTCP_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetSwitch
 */
export type AkPlaySoundComponent_SetSwitch_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetVectorParameter
 */
export type AkPlaySoundComponent_SetVectorParameter_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FVector; // 0x0008 (0x000c) [FVector] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.Stop
 */
export type AkPlaySoundComponent_Stop_Params = {};

/**
 * Function AkAudio.AkRevPhysicsSimulation.CalcRPM
 */
export type AkRevPhysicsSimulation_CalcRPM_Params = {
  GearRatio: number; // 0x0000 (0x0004) [float] [CPF_Parm]
  Velocity: number; // 0x0004 (0x0004) [float] [CPF_Parm]
  ReturnValue: number; // 0x0008 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.CalcVelocity
 */
export type AkRevPhysicsSimulation_CalcVelocity_Params = {
  GearRatio: number; // 0x0000 (0x0004) [float] [CPF_Parm]
  RPM: number; // 0x0004 (0x0004) [float] [CPF_Parm]
  ReturnValue: number; // 0x0008 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.EventGearChange
 */
export type AkRevPhysicsSimulation_EventGearChange_Params = {
  Simulation: UAkRevPhysicsSimulation; // 0x0000 (0x0008) [UAkRevPhysicsSimulation*] [CPF_Parm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.GetGearRatio
 */
export type AkRevPhysicsSimulation_GetGearRatio_Params = {
  SimUpdate: FAkRevSimUpdateParams; // 0x0000 (0x0048) [FAkRevSimUpdateParams] [CPF_Parm | CPF_OutParm]
  ReturnValue: number; // 0x0048 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.InterpGearRatio
 */
export type AkRevPhysicsSimulation_InterpGearRatio_Params = {
  SimUpdate: FAkRevSimUpdateParams; // 0x0000 (0x0048) [FAkRevSimUpdateParams] [CPF_Parm | CPF_OutParm]
  Gear: number; // 0x0048 (0x0004) [int32] [CPF_Parm]
  ReturnValue: number; // 0x004c (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.PrintDebugInfo
 */
export type AkRevPhysicsSimulation_PrintDebugInfo_Params = {
  Drawer: UDebugDrawer; // 0x0000 (0x0008) [UDebugDrawer*] [CPF_Parm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.Step
 */
export type AkRevPhysicsSimulation_Step_Params = {
  DeltaTime: number; // 0x0000 (0x0004) [float] [CPF_Parm]
  Params: FAkRevSimUpdateParams; // 0x0008 (0x0048) [FAkRevSimUpdateParams] [CPF_Parm | CPF_OutParm]
  ReturnValue: FAkRevSimFrame; // 0x0050 (0x0010) [FAkRevSimFrame] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundBanksInfo.LoadForNativePlatform
 */
export type AkSoundBanksInfo_LoadForNativePlatform_Params = {
  ReturnValue: UAkSoundBanksInfo; // 0x0000 (0x0008) [UAkSoundBanksInfo*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundBanksInfo.Parse
 */
export type AkSoundBanksInfo_Parse_Params = {
  Text: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: UAkSoundBanksInfo; // 0x0010 (0x0008) [UAkSoundBanksInfo*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.EventDuration
 */
export type AkSoundSource_EventDuration_Params = {
  Source: UAkSoundSource; // 0x0000 (0x0008) [UAkSoundSource*] [CPF_Parm]
  PlayingID: number; // 0x0008 (0x0004) [int32] [CPF_Parm]
  DurationMS: number; // 0x000c (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.EventFinished
 */
export type AkSoundSource_EventFinished_Params = {
  Source: UAkSoundSource; // 0x0000 (0x0008) [UAkSoundSource*] [CPF_Parm]
  PlayingID: number; // 0x0008 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.EventMarker
 */
export type AkSoundSource_EventMarker_Params = {
  Source: UAkSoundSource; // 0x0000 (0x0008) [UAkSoundSource*] [CPF_Parm]
  PlayingID: number; // 0x0008 (0x0004) [int32] [CPF_Parm]
  Marker: string; // 0x0010 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.ForceUpdatePosition
 */
export type AkSoundSource_ForceUpdatePosition_Params = {};

/**
 * Function AkAudio.AkSoundSource.IsPlaying
 */
export type AkSoundSource_IsPlaying_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
  ReturnValue: boolean; // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.IsPlayingAny
 */
export type AkSoundSource_IsPlayingAny_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.Play
 */
export type AkSoundSource_Play_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
  ReturnValue: number; // 0x0008 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.RegisterReflectionEmitter
 */
export type AkSoundSource_RegisterReflectionEmitter_Params = {
  BusName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  BusType: EBusEmitterType; // 0x0008 (0x0001) [EBusEmitterType] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.Seek
 */
export type AkSoundSource_Seek_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
  SeekSeconds: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.SetAttenuationScaling
 */
export type AkSoundSource_SetAttenuationScaling_Params = {
  AttenuationType: EAttenuationType; // 0x0000 (0x0001) [EAttenuationType] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.SetSubtitlesEnabled
 */
export type AkSoundSource_SetSubtitlesEnabled_Params = {
  bValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.Stop
 */
export type AkSoundSource_Stop_Params = {
  Sound: UAkSoundCue; // 0x0000 (0x0008) [UAkSoundCue*] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.StopAll
 */
export type AkSoundSource_StopAll_Params = {};

/**
 * Function AkAudio.SeqAct_AkPlayMusicWithCues.TriggerEvents
 */
export type SeqAct_AkPlayMusicWithCues_TriggerEvents_Params = {
  CueName: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  CurWorldInfo: UWorldInfo; // 0x0010 (0x0008) [UWorldInfo*]
  Evt: USeqEvent_AkMusicCue; // 0x0018 (0x0008) [USeqEvent_AkMusicCue*]
};

/**
 * Function AkAudio.SeqAct_AkPlaySound.Activated
 */
export type SeqAct_AkPlaySound_Activated_Params = {};

/**
 * Function AkAudio.SeqAct_AkPlaySound.ToggleSound
 */
export type SeqAct_AkPlaySound_ToggleSound_Params = {
  bPlay: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
  O: UObject; // 0x0008 (0x0008) [UObject*]
  A: UActor; // 0x0010 (0x0008) [UActor*]
};

/**
 * Function AkAudio.SeqAct_AkPlaySound.ToggleSoundFor
 */
export type SeqAct_AkPlaySound_ToggleSoundFor_Params = {
  A: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  bPlay: boolean; // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPlaySoundAndSeek.Activated
 */
export type SeqAct_AkPlaySoundAndSeek_Activated_Params = {};

/**
 * Function AkAudio.SeqAct_AkPlaySoundAndSeek.ToggleSound
 */
export type SeqAct_AkPlaySoundAndSeek_ToggleSound_Params = {
  bPlay: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
  O: UObject; // 0x0008 (0x0008) [UObject*]
  A: UActor; // 0x0010 (0x0008) [UActor*]
};

/**
 * Function AkAudio.SeqAct_AkPlaySoundAndSeek.ToggleSoundFor
 */
export type SeqAct_AkPlaySoundAndSeek_ToggleSoundFor_Params = {
  A: UActor; // 0x0000 (0x0008) [UActor*] [CPF_Parm]
  bPlay: boolean; // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPostEvent.HandleSoundCueFinished
 */
export type SeqAct_AkPostEvent_HandleSoundCueFinished_Params = {
  Source: UAkSoundSource; // 0x0000 (0x0008) [UAkSoundSource*] [CPF_Parm]
  PlayingID: number; // 0x0008 (0x0004) [int32] [CPF_Parm]
};
