/**
 * GFxUI Package - Function Parameters
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

import type { FName, FScriptDelegate } from '../types/GameDefines';
import type { UObject } from '../classes/Core';
import type { UEngine, UGameViewportClient, ULocalPlayer, UPlayerController, UTexture, UTranslationContext, UUISoundTheme } from '../classes/Engine';
import type { UGFxEvent_FSCommand, UGFxMoviePlayer, UGFxObject, USwfMovie } from '../classes/GFxUI';
import type { EInputEvent } from '../enums/Core';
import type { GFxAlign, GFxCollectionMode, GFxScaleMode, GFxTimingMode } from '../enums/GFxUI';
import type { FMatrix } from '../structs/Core';
import type { FASColorTransform, FASDisplayInfo, FASValue, FEventData, FLoadingMovieMapInfo } from '../structs/GFxUI';

/**
 * Function GFxUI.GFxAction_CloseMovie.IsValidLevelSequenceObject
 */
export type GFxAction_CloseMovie_IsValidLevelSequenceObject_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxAction_GetVariable.IsValidLevelSequenceObject
 */
export type GFxAction_GetVariable_IsValidLevelSequenceObject_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxAction_Invoke.IsValidLevelSequenceObject
 */
export type GFxAction_Invoke_IsValidLevelSequenceObject_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxAction_OpenMovie.IsValidLevelSequenceObject
 */
export type GFxAction_OpenMovie_IsValidLevelSequenceObject_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxAction_SetVariable.IsValidLevelSequenceObject
 */
export type GFxAction_SetVariable_IsValidLevelSequenceObject_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxClikWidget.AddEventListener
 */
export type GFxClikWidget_AddEventListener_Params = {
  Type: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  Listener: FScriptDelegate; // 0x0008 (0x0018) [FScriptDelegate] [CPF_Parm]
  useCapture: boolean; // 0x0020 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
  listenerPriority: number; // 0x0024 (0x0004) [int32] [CPF_Parm | CPF_OptionalParm]
  useWeakReference: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
  O: UGFxObject; // 0x0030 (0x0008) [UGFxObject*]
  funcobj: UGFxObject; // 0x0038 (0x0008) [UGFxObject*]
  Typestring: string; // 0x0040 (0x0010) [FString]
};

/**
 * Function GFxUI.GFxClikWidget.AS3AddEventListener
 */
export type GFxClikWidget_AS3AddEventListener_Params = {
  Type: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  O: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
  useCapture: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
  listenerPriority: number; // 0x001c (0x0004) [int32] [CPF_Parm | CPF_OptionalParm]
  useWeakReference: boolean; // 0x0020 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxClikWidget.ASAddEventListener
 */
export type GFxClikWidget_ASAddEventListener_Params = {
  Type: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  O: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
  func: string; // 0x0018 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxClikWidget.ASRemoveAllEventListeners
 */
export type GFxClikWidget_ASRemoveAllEventListeners_Params = {
  Event: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxClikWidget.EventListener
 */
export type GFxClikWidget_EventListener_Params = {
  Data: FEventData; // 0x0000 (0x0038) [FEventData] [CPF_Parm]
};

/**
 * Function GFxUI.GFxClikWidget.GetEventStringFromTypename
 */
export type GFxClikWidget_GetEventStringFromTypename_Params = {
  Typename: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  ReturnValue: string; // 0x0008 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
  Typestring: string; // 0x0018 (0x0010) [FString]
};

/**
 * Function GFxUI.GFxClikWidget.RemoveAllEventListeners
 */
export type GFxClikWidget_RemoveAllEventListeners_Params = {
  Event: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxClikWidget.SetListener
 */
export type GFxClikWidget_SetListener_Params = {
  O: UGFxObject; // 0x0000 (0x0008) [UGFxObject*] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  Listener: FScriptDelegate; // 0x0018 (0x0018) [FScriptDelegate] [CPF_Parm]
};

/**
 * Function GFxUI.GFxEngine.Tick
 */
export type GFxEngine_Tick_Params = {
  DeltaTime: number; // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxEngine.UpdateMovieLoadingInfo
 */
export type GFxEngine_UpdateMovieLoadingInfo_Params = {
  LoadingInfo: FLoadingMovieMapInfo; // 0x0000 (0x00a0) [FLoadingMovieMapInfo] [CPF_Parm | CPF_OutParm]
};

/**
 * Function GFxUI.GFxFSCmdHandler.FSCommand
 */
export type GFxFSCmdHandler_FSCommand_Params = {
  Movie: UGFxMoviePlayer; // 0x0000 (0x0008) [UGFxMoviePlayer*] [CPF_Parm]
  Event: UGFxEvent_FSCommand; // 0x0008 (0x0008) [UGFxEvent_FSCommand*] [CPF_Parm]
  Cmd: string; // 0x0010 (0x0010) [FString] [CPF_Parm]
  Arg: string; // 0x0020 (0x0010) [FString] [CPF_Parm]
  ReturnValue: boolean; // 0x0030 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxFSCmdHandler_Kismet.FSCommand
 */
export type GFxFSCmdHandler_Kismet_FSCommand_Params = {
  Movie: UGFxMoviePlayer; // 0x0000 (0x0008) [UGFxMoviePlayer*] [CPF_Parm]
  Event: UGFxEvent_FSCommand; // 0x0008 (0x0008) [UGFxEvent_FSCommand*] [CPF_Parm]
  Cmd: string; // 0x0010 (0x0010) [FString] [CPF_Parm]
  Arg: string; // 0x0020 (0x0010) [FString] [CPF_Parm]
  ReturnValue: boolean; // 0x0030 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxInteraction.CloseAllMoviePlayers
 */
export type GFxInteraction_CloseAllMoviePlayers_Params = {};

/**
 * Function GFxUI.GFxInteraction.DebugInputKey
 */
export type GFxInteraction_DebugInputKey_Params = {
  ControllerId: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Key: FName; // 0x0004 (0x0008) [FName] [CPF_Parm]
  Event: EInputEvent; // 0x000c (0x0001) [EInputEvent] [CPF_Parm]
  AmountDepressed: number; // 0x0010 (0x0004) [float] [CPF_Parm]
  bGamepad: boolean; // 0x0014 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxInteraction.GetFocusMovie
 */
export type GFxInteraction_GetFocusMovie_Params = {
  ControllerId: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: UGFxMoviePlayer; // 0x0008 (0x0008) [UGFxMoviePlayer*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxInteraction.NotifyGameSessionEnded
 */
export type GFxInteraction_NotifyGameSessionEnded_Params = {};

/**
 * Function GFxUI.GFxInteraction.NotifyPlayerAdded
 */
export type GFxInteraction_NotifyPlayerAdded_Params = {
  PlayerIndex: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  AddedPlayer: ULocalPlayer; // 0x0008 (0x0008) [ULocalPlayer*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxInteraction.NotifyPlayerRemoved
 */
export type GFxInteraction_NotifyPlayerRemoved_Params = {
  PlayerIndex: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  RemovedPlayer: ULocalPlayer; // 0x0008 (0x0008) [ULocalPlayer*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxInteraction.NotifySplitscreenLayoutChanged
 */
export type GFxInteraction_NotifySplitscreenLayoutChanged_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptConstructor
 */
export type GFxMoviePlayer_ActionScriptConstructor_Params = {
  ClassName: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptFloat
 */
export type GFxMoviePlayer_ActionScriptFloat_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptInt
 */
export type GFxMoviePlayer_ActionScriptInt_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptObject
 */
export type GFxMoviePlayer_ActionScriptObject_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptSetFunction
 */
export type GFxMoviePlayer_ActionScriptSetFunction_Params = {
  Object: UGFxObject; // 0x0000 (0x0008) [UGFxObject*] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptString
 */
export type GFxMoviePlayer_ActionScriptString_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: string; // 0x0010 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ActionScriptVoid
 */
export type GFxMoviePlayer_ActionScriptVoid_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.AddCaptureKey
 */
export type GFxMoviePlayer_AddCaptureKey_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.AddFocusIgnoreKey
 */
export type GFxMoviePlayer_AddFocusIgnoreKey_Params = {
  Key: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.Advance
 */
export type GFxMoviePlayer_Advance_Params = {
  Time: number; // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ApplyPriorityBlurEffect
 */
export type GFxMoviePlayer_ApplyPriorityBlurEffect_Params = {
  bRemoveEffect: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ApplyPriorityEffect
 */
export type GFxMoviePlayer_ApplyPriorityEffect_Params = {
  bRequestedBlurState: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
  bRequestedHiddenState: boolean; // 0x0004 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ApplyPriorityVisibilityEffect
 */
export type GFxMoviePlayer_ApplyPriorityVisibilityEffect_Params = {
  bRemoveEffect: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ClearCaptureKeys
 */
export type GFxMoviePlayer_ClearCaptureKeys_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.ClearFocusIgnoreKeys
 */
export type GFxMoviePlayer_ClearFocusIgnoreKeys_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.Close
 */
export type GFxMoviePlayer_Close_Params = {
  Unload: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.ConditionalClearPause
 */
export type GFxMoviePlayer_ConditionalClearPause_Params = {
  LP: ULocalPlayer; // 0x0000 (0x0008) [ULocalPlayer*]
};

/**
 * Function GFxUI.GFxMoviePlayer.ConsoleCommand
 */
export type GFxMoviePlayer_ConsoleCommand_Params = {
  Command: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  PC: UPlayerController; // 0x0010 (0x0008) [UPlayerController*]
};

/**
 * Function GFxUI.GFxMoviePlayer.CreateArray
 */
export type GFxMoviePlayer_CreateArray_Params = {
  ReturnValue: UGFxObject; // 0x0000 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.CreateObject
 */
export type GFxMoviePlayer_CreateObject_Params = {
  ASClass: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Type: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  args: FASValue[]; // 0x0018 (0x0010) [TArray<FASValue>] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0028 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.FilterButtonInput
 */
export type GFxMoviePlayer_FilterButtonInput_Params = {
  ControllerId: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ButtonName: FName; // 0x0004 (0x0008) [FName] [CPF_Parm]
  InputEvent: EInputEvent; // 0x000c (0x0001) [EInputEvent] [CPF_Parm]
  ReturnValue: boolean; // 0x0010 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.FlushPlayerInput
 */
export type GFxMoviePlayer_FlushPlayerInput_Params = {
  capturekeysonly: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetAVMVersion
 */
export type GFxMoviePlayer_GetAVMVersion_Params = {
  ReturnValue: number; // 0x0000 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetGameViewportClient
 */
export type GFxMoviePlayer_GetGameViewportClient_Params = {
  ReturnValue: UGameViewportClient; // 0x0000 (0x0008) [UGameViewportClient*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetLP
 */
export type GFxMoviePlayer_GetLP_Params = {
  ReturnValue: ULocalPlayer; // 0x0000 (0x0008) [ULocalPlayer*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
  Eng: UEngine; // 0x0008 (0x0008) [UEngine*]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetPC
 */
export type GFxMoviePlayer_GetPC_Params = {
  ReturnValue: UPlayerController; // 0x0000 (0x0008) [UPlayerController*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
  LocalPlayerOwner: ULocalPlayer; // 0x0008 (0x0008) [ULocalPlayer*]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariable
 */
export type GFxMoviePlayer_GetVariable_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: FASValue; // 0x0010 (0x0028) [FASValue] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableArray
 */
export type GFxMoviePlayer_GetVariableArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: FASValue[]; // 0x0018 (0x0010) [TArray<FASValue>] [CPF_Parm | CPF_OutParm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableBool
 */
export type GFxMoviePlayer_GetVariableBool_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: boolean; // 0x0010 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableFloatArray
 */
export type GFxMoviePlayer_GetVariableFloatArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: number[]; // 0x0018 (0x0010) [TArray<float>] [CPF_Parm | CPF_OutParm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableInt
 */
export type GFxMoviePlayer_GetVariableInt_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableIntArray
 */
export type GFxMoviePlayer_GetVariableIntArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: number[]; // 0x0018 (0x0010) [TArray<int32>] [CPF_Parm | CPF_OutParm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableNumber
 */
export type GFxMoviePlayer_GetVariableNumber_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableObject
 */
export type GFxMoviePlayer_GetVariableObject_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Type: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0018 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableString
 */
export type GFxMoviePlayer_GetVariableString_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: string; // 0x0010 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVariableStringArray
 */
export type GFxMoviePlayer_GetVariableStringArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: string[]; // 0x0018 (0x0010) [TArray<FString>] [CPF_Parm | CPF_OutParm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.GetVisibleFrameRect
 */
export type GFxMoviePlayer_GetVisibleFrameRect_Params = {
  x0: number; // 0x0000 (0x0004) [float] [CPF_Parm | CPF_OutParm]
  y0: number; // 0x0004 (0x0004) [float] [CPF_Parm | CPF_OutParm]
  X1: number; // 0x0008 (0x0004) [float] [CPF_Parm | CPF_OutParm]
  Y1: number; // 0x000c (0x0004) [float] [CPF_Parm | CPF_OutParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.Init
 */
export type GFxMoviePlayer_Init_Params = {
  LocPlay: ULocalPlayer; // 0x0000 (0x0008) [ULocalPlayer*] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.Invoke
 */
export type GFxMoviePlayer_Invoke_Params = {
  method: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  args: FASValue[]; // 0x0010 (0x0010) [TArray<FASValue>] [CPF_Parm]
  ReturnValue: FASValue; // 0x0020 (0x0028) [FASValue] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.IsHidden
 */
export type GFxMoviePlayer_IsHidden_Params = {
  ReturnValue: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.OnCleanup
 */
export type GFxMoviePlayer_OnCleanup_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.OnClose
 */
export type GFxMoviePlayer_OnClose_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.OnFocusGained
 */
export type GFxMoviePlayer_OnFocusGained_Params = {
  LocalPlayerIndex: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.OnFocusLost
 */
export type GFxMoviePlayer_OnFocusLost_Params = {
  LocalPlayerIndex: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.OnPostAdvance
 */
export type GFxMoviePlayer_OnPostAdvance_Params = {
  DeltaTime: number; // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.PlaySoundFromTheme
 */
export type GFxMoviePlayer_PlaySoundFromTheme_Params = {
  EventName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  SoundThemeName: FName; // 0x0008 (0x0008) [FName] [CPF_Parm | CPF_OptionalParm]
  ThemeIndex: number; // 0x0010 (0x0004) [int32]
  Theme: UUISoundTheme; // 0x0018 (0x0008) [UUISoundTheme*]
};

/**
 * Function GFxUI.GFxMoviePlayer.PostAdvance
 */
export type GFxMoviePlayer_PostAdvance_Params = {
  DeltaTime: number; // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.PostWidgetInit
 */
export type GFxMoviePlayer_PostWidgetInit_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.RenderOnce
 */
export type GFxMoviePlayer_RenderOnce_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.RequestGarbageCollection
 */
export type GFxMoviePlayer_RequestGarbageCollection_Params = {
  Mode: GFxCollectionMode; // 0x0000 (0x0001) [GFxCollectionMode] [CPF_Parm | CPF_OptionalParm]
  bImmediate: boolean; // 0x0004 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetAlignment
 */
export type GFxMoviePlayer_SetAlignment_Params = {
  A: GFxAlign; // 0x0000 (0x0001) [GFxAlign] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetExternalInterface
 */
export type GFxMoviePlayer_SetExternalInterface_Params = {
  H: UObject; // 0x0000 (0x0008) [UObject*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetExternalTexture
 */
export type GFxMoviePlayer_SetExternalTexture_Params = {
  Resource: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Texture: UTexture; // 0x0010 (0x0008) [UTexture*] [CPF_Parm]
  ReturnValue: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetFullScreen
 */
export type GFxMoviePlayer_SetFullScreen_Params = {
  bFullScreen: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetHidden
 */
export type GFxMoviePlayer_SetHidden_Params = {
  bHidden: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetMovieCanReceiveFocus
 */
export type GFxMoviePlayer_SetMovieCanReceiveFocus_Params = {
  bCanReceiveFocus: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetMovieCanReceiveInput
 */
export type GFxMoviePlayer_SetMovieCanReceiveInput_Params = {
  bCanReceiveInput: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetMovieInfo
 */
export type GFxMoviePlayer_SetMovieInfo_Params = {
  Data: USwfMovie; // 0x0000 (0x0008) [USwfMovie*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetPause
 */
export type GFxMoviePlayer_SetPause_Params = {
  bPausePlayback: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetPerspective3D
 */
export type GFxMoviePlayer_SetPerspective3D_Params = {
  matPersp: FMatrix; // 0x0000 (0x0040) [FMatrix] [CPF_Parm | CPF_OutParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetPriority
 */
export type GFxMoviePlayer_SetPriority_Params = {
  NewPriority: number; // 0x0000 (0x0001) [uint8] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetTimingMode
 */
export type GFxMoviePlayer_SetTimingMode_Params = {
  Mode: GFxTimingMode; // 0x0000 (0x0001) [GFxTimingMode] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariable
 */
export type GFxMoviePlayer_SetVariable_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Arg: FASValue; // 0x0010 (0x0028) [FASValue] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableArray
 */
export type GFxMoviePlayer_SetVariableArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: FASValue[]; // 0x0018 (0x0010) [TArray<FASValue>] [CPF_Parm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableBool
 */
export type GFxMoviePlayer_SetVariableBool_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  B: boolean; // 0x0010 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableFloatArray
 */
export type GFxMoviePlayer_SetVariableFloatArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: number[]; // 0x0018 (0x0010) [TArray<float>] [CPF_Parm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableInt
 */
export type GFxMoviePlayer_SetVariableInt_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  I: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableIntArray
 */
export type GFxMoviePlayer_SetVariableIntArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: number[]; // 0x0018 (0x0010) [TArray<int32>] [CPF_Parm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableNumber
 */
export type GFxMoviePlayer_SetVariableNumber_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  F: number; // 0x0010 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableObject
 */
export type GFxMoviePlayer_SetVariableObject_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Object: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableString
 */
export type GFxMoviePlayer_SetVariableString_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  S: string; // 0x0010 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetVariableStringArray
 */
export type GFxMoviePlayer_SetVariableStringArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Index: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
  Arg: string[]; // 0x0018 (0x0010) [TArray<FString>] [CPF_Parm]
  ReturnValue: boolean; // 0x0028 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetView3D
 */
export type GFxMoviePlayer_SetView3D_Params = {
  matView: FMatrix; // 0x0000 (0x0040) [FMatrix] [CPF_Parm | CPF_OutParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetViewport
 */
export type GFxMoviePlayer_SetViewport_Params = {
  X: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Y: number; // 0x0004 (0x0004) [int32] [CPF_Parm]
  Width: number; // 0x0008 (0x0004) [int32] [CPF_Parm]
  Height: number; // 0x000c (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetViewScaleMode
 */
export type GFxMoviePlayer_SetViewScaleMode_Params = {
  SM: GFxScaleMode; // 0x0000 (0x0001) [GFxScaleMode] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.SetWidgetPathBinding
 */
export type GFxMoviePlayer_SetWidgetPathBinding_Params = {
  WidgetToBind: UGFxObject; // 0x0000 (0x0008) [UGFxObject*] [CPF_Parm]
  Path: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function GFxUI.GFxMoviePlayer.Start
 */
export type GFxMoviePlayer_Start_Params = {
  StartPaused: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: boolean; // 0x0004 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.UpdateSplitscreenLayout
 */
export type GFxMoviePlayer_UpdateSplitscreenLayout_Params = {};

/**
 * Function GFxUI.GFxMoviePlayer.WidgetInitialized
 */
export type GFxMoviePlayer_WidgetInitialized_Params = {
  WidgetName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  WidgetPath: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  Widget: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
  ReturnValue: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxMoviePlayer.WidgetUnloaded
 */
export type GFxMoviePlayer_WidgetUnloaded_Params = {
  WidgetName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  WidgetPath: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  Widget: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
  ReturnValue: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptArray
 */
export type GFxObject_ActionScriptArray_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: UGFxObject[]; // 0x0010 (0x0010) [TArray<UGFxObject*>] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptFloat
 */
export type GFxObject_ActionScriptFloat_Params = {
  method: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptInt
 */
export type GFxObject_ActionScriptInt_Params = {
  method: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptObject
 */
export type GFxObject_ActionScriptObject_Params = {
  Path: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptSetFunction
 */
export type GFxObject_ActionScriptSetFunction_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptSetFunctionOn
 */
export type GFxObject_ActionScriptSetFunctionOn_Params = {
  Target: UGFxObject; // 0x0000 (0x0008) [UGFxObject*] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptString
 */
export type GFxObject_ActionScriptString_Params = {
  method: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: string; // 0x0010 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.ActionScriptVoid
 */
export type GFxObject_ActionScriptVoid_Params = {
  method: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.AttachMovie
 */
export type GFxObject_AttachMovie_Params = {
  symbolname: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  instancename: string; // 0x0010 (0x0010) [FString] [CPF_Parm]
  Depth: number; // 0x0020 (0x0004) [int32] [CPF_Parm | CPF_OptionalParm]
  Type: UGFxObject; // 0x0028 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0030 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.CreateEmptyMovieClip
 */
export type GFxObject_CreateEmptyMovieClip_Params = {
  instancename: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Depth: number; // 0x0010 (0x0004) [int32] [CPF_Parm | CPF_OptionalParm]
  Type: UGFxObject; // 0x0018 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0020 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.Get
 */
export type GFxObject_Get_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: FASValue; // 0x0010 (0x0028) [FASValue] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetBool
 */
export type GFxObject_GetBool_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: boolean; // 0x0010 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetColorTransform
 */
export type GFxObject_GetColorTransform_Params = {
  ReturnValue: FASColorTransform; // 0x0000 (0x0020) [FASColorTransform] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetDisplayInfo
 */
export type GFxObject_GetDisplayInfo_Params = {
  ReturnValue: FASDisplayInfo; // 0x0000 (0x002c) [FASDisplayInfo] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetDisplayMatrix
 */
export type GFxObject_GetDisplayMatrix_Params = {
  ReturnValue: FMatrix; // 0x0000 (0x0040) [FMatrix] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetDisplayMatrix3D
 */
export type GFxObject_GetDisplayMatrix3D_Params = {
  ReturnValue: FMatrix; // 0x0000 (0x0040) [FMatrix] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElement
 */
export type GFxObject_GetElement_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: FASValue; // 0x0008 (0x0028) [FASValue] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementBool
 */
export type GFxObject_GetElementBool_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: boolean; // 0x0004 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementDisplayInfo
 */
export type GFxObject_GetElementDisplayInfo_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: FASDisplayInfo; // 0x0004 (0x002c) [FASDisplayInfo] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementDisplayMatrix
 */
export type GFxObject_GetElementDisplayMatrix_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: FMatrix; // 0x0010 (0x0040) [FMatrix] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementFloat
 */
export type GFxObject_GetElementFloat_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: number; // 0x0004 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementInt
 */
export type GFxObject_GetElementInt_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: number; // 0x0004 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementMember
 */
export type GFxObject_GetElementMember_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  ReturnValue: FASValue; // 0x0018 (0x0028) [FASValue] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementMemberBool
 */
export type GFxObject_GetElementMemberBool_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  ReturnValue: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementMemberFloat
 */
export type GFxObject_GetElementMemberFloat_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0018 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementMemberInt
 */
export type GFxObject_GetElementMemberInt_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0018 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementMemberObject
 */
export type GFxObject_GetElementMemberObject_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  Type: UGFxObject; // 0x0018 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0020 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementMemberString
 */
export type GFxObject_GetElementMemberString_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  ReturnValue: string; // 0x0018 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementObject
 */
export type GFxObject_GetElementObject_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Type: UGFxObject; // 0x0008 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetElementString
 */
export type GFxObject_GetElementString_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  ReturnValue: string; // 0x0008 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetFloat
 */
export type GFxObject_GetFloat_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetInt
 */
export type GFxObject_GetInt_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: number; // 0x0010 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetObject
 */
export type GFxObject_GetObject_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Type: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: UGFxObject; // 0x0018 (0x0008) [UGFxObject*] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetPosition
 */
export type GFxObject_GetPosition_Params = {
  X: number; // 0x0000 (0x0004) [float] [CPF_Parm | CPF_OutParm]
  Y: number; // 0x0004 (0x0004) [float] [CPF_Parm | CPF_OutParm]
  ReturnValue: boolean; // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetString
 */
export type GFxObject_GetString_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  ReturnValue: string; // 0x0010 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GetText
 */
export type GFxObject_GetText_Params = {
  ReturnValue: string; // 0x0000 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.GotoAndPlay
 */
export type GFxObject_GotoAndPlay_Params = {
  frame: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.GotoAndPlayI
 */
export type GFxObject_GotoAndPlayI_Params = {
  frame: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.GotoAndStop
 */
export type GFxObject_GotoAndStop_Params = {
  frame: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.GotoAndStopI
 */
export type GFxObject_GotoAndStopI_Params = {
  frame: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.Invoke
 */
export type GFxObject_Invoke_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  args: FASValue[]; // 0x0010 (0x0010) [TArray<FASValue>] [CPF_Parm]
  ReturnValue: FASValue; // 0x0020 (0x0028) [FASValue] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.Set
 */
export type GFxObject_Set_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Arg: FASValue; // 0x0010 (0x0028) [FASValue] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetBool
 */
export type GFxObject_SetBool_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  B: boolean; // 0x0010 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetColorTransform
 */
export type GFxObject_SetColorTransform_Params = {
  cxform: FASColorTransform; // 0x0000 (0x0020) [FASColorTransform] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetDisplayInfo
 */
export type GFxObject_SetDisplayInfo_Params = {
  D: FASDisplayInfo; // 0x0000 (0x002c) [FASDisplayInfo] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetDisplayMatrix
 */
export type GFxObject_SetDisplayMatrix_Params = {
  M: FMatrix; // 0x0000 (0x0040) [FMatrix] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetDisplayMatrix3D
 */
export type GFxObject_SetDisplayMatrix3D_Params = {
  M: FMatrix; // 0x0000 (0x0040) [FMatrix] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElement
 */
export type GFxObject_SetElement_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Arg: FASValue; // 0x0008 (0x0028) [FASValue] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementBool
 */
export type GFxObject_SetElementBool_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  B: boolean; // 0x0004 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementColorTransform
 */
export type GFxObject_SetElementColorTransform_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  cxform: FASColorTransform; // 0x0004 (0x0020) [FASColorTransform] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementDisplayInfo
 */
export type GFxObject_SetElementDisplayInfo_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  D: FASDisplayInfo; // 0x0004 (0x002c) [FASDisplayInfo] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementDisplayMatrix
 */
export type GFxObject_SetElementDisplayMatrix_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  M: FMatrix; // 0x0010 (0x0040) [FMatrix] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementFloat
 */
export type GFxObject_SetElementFloat_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  F: number; // 0x0004 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementInt
 */
export type GFxObject_SetElementInt_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  I: number; // 0x0004 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementMember
 */
export type GFxObject_SetElementMember_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  Arg: FASValue; // 0x0018 (0x0028) [FASValue] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementMemberBool
 */
export type GFxObject_SetElementMemberBool_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  B: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementMemberFloat
 */
export type GFxObject_SetElementMemberFloat_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  F: number; // 0x0018 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementMemberInt
 */
export type GFxObject_SetElementMemberInt_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  I: number; // 0x0018 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementMemberObject
 */
export type GFxObject_SetElementMemberObject_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  val: UGFxObject; // 0x0018 (0x0008) [UGFxObject*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementMemberString
 */
export type GFxObject_SetElementMemberString_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Member: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
  S: string; // 0x0018 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementObject
 */
export type GFxObject_SetElementObject_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  val: UGFxObject; // 0x0008 (0x0008) [UGFxObject*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementPosition
 */
export type GFxObject_SetElementPosition_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  X: number; // 0x0004 (0x0004) [float] [CPF_Parm]
  Y: number; // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementString
 */
export type GFxObject_SetElementString_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  S: string; // 0x0008 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetElementVisible
 */
export type GFxObject_SetElementVisible_Params = {
  Index: number; // 0x0000 (0x0004) [int32] [CPF_Parm]
  Visible: boolean; // 0x0004 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetFloat
 */
export type GFxObject_SetFloat_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  F: number; // 0x0010 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetFunction
 */
export type GFxObject_SetFunction_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  Context: UObject; // 0x0010 (0x0008) [UObject*] [CPF_Parm]
  fname: FName; // 0x0018 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetInt
 */
export type GFxObject_SetInt_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  I: number; // 0x0010 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetObject
 */
export type GFxObject_SetObject_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  val: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetPosition
 */
export type GFxObject_SetPosition_Params = {
  X: number; // 0x0000 (0x0004) [float] [CPF_Parm]
  Y: number; // 0x0004 (0x0004) [float] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.SetString
 */
export type GFxObject_SetString_Params = {
  Member: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  S: string; // 0x0010 (0x0010) [FString] [CPF_Parm]
  InContext: UTranslationContext; // 0x0020 (0x0008) [UTranslationContext*] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxObject.SetText
 */
export type GFxObject_SetText_Params = {
  Text: string; // 0x0000 (0x0010) [FString] [CPF_Parm | CPF_CoerceParm]
  InContext: UTranslationContext; // 0x0010 (0x0008) [UTranslationContext*] [CPF_Parm | CPF_OptionalParm]
};

/**
 * Function GFxUI.GFxObject.SetVisible
 */
export type GFxObject_SetVisible_Params = {
  Visible: boolean; // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function GFxUI.GFxObject.TranslateString
 */
export type GFxObject_TranslateString_Params = {
  StringToTranslate: string; // 0x0000 (0x0010) [FString] [CPF_Parm]
  InContext: UTranslationContext; // 0x0010 (0x0008) [UTranslationContext*] [CPF_Parm | CPF_OptionalParm]
  ReturnValue: string; // 0x0018 (0x0010) [FString] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.WidgetInitialized
 */
export type GFxObject_WidgetInitialized_Params = {
  WidgetName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  WidgetPath: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  Widget: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
  ReturnValue: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function GFxUI.GFxObject.WidgetUnloaded
 */
export type GFxObject_WidgetUnloaded_Params = {
  WidgetName: FName; // 0x0000 (0x0008) [FName] [CPF_Parm]
  WidgetPath: FName; // 0x0008 (0x0008) [FName] [CPF_Parm]
  Widget: UGFxObject; // 0x0010 (0x0008) [UGFxObject*] [CPF_Parm]
  ReturnValue: boolean; // 0x0018 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};
