/**
 * AkAudio Package - Enums
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

/**
 * Enum AkAudio.AkSoundSource.EAkCallbackType
 */
export enum EAkCallbackType {
  AkCallbackType_Marker = 0,
  AkCallbackType_Duration = 1,
  AkCallbackType_MAX = 2,
}

/**
 * Enum AkAudio.AkDevice.EAkDynamicRangeType
 */
export enum EAkDynamicRangeType {
  AkDRT_Low = 0,
  AkDRT_Medium = 1,
  AkDRT_High = 2,
  AkDRT_MAX = 3,
}

/**
 * Enum AkAudio.SeqAct_AkEnvironment.EAkEnvironmentTarget
 */
export enum EAkEnvironmentTarget {
  AkEnvironmentTarget_LevelDefault = 0,
  AkEnvironmentTarget_Actor = 1,
  AkEnvironmentTarget_MAX = 2,
}

/**
 * Enum AkAudio.AkSoundSource.EAkEnvironmentType
 */
export enum EAkEnvironmentType {
  EnvironmentType_SpatializedAudio = 0,
  EnvironmentType_UnspatializedAudio = 1,
  EnvironmentType_Music = 2,
  EnvironmentType_None = 3,
  EnvironmentType_MAX = 4,
}

/**
 * Enum AkAudio.AkDevice.EAkListenerSpacialization
 */
export enum EAkListenerSpacialization {
  AkLS_3D = 0,
  AkLS_Left = 1,
  AkLS_Right = 2,
  AkLS_MAX = 3,
}

/**
 * Enum AkAudio.AkDevice.EAkOutputType
 */
export enum EAkOutputType {
  AkOT_Speakers = 0,
  AKOT_Headphones = 1,
  EAkOutputType_MAX = 2,
}

/**
 * Enum AkAudio.AkPlaySoundComponent.EAkPlaySoundReceiver
 */
export enum EAkPlaySoundReceiver {
  PlaySoundReceiver_All = 0,
  PlaySoundReceiver_Local = 1,
  PlaySoundReceiver_NonLocal = 2,
  PlaySoundReceiver_MAX = 3,
}

/**
 * Enum AkAudio.AkParamGroup.EAttenuationType
 */
export enum EAttenuationType {
  AttenuationType_Default = 0,
  AttenuationType_None = 1,
  AttenuationType_MAX = 2,
}

/**
 * Enum AkAudio.AkBusActor.EBusEmitterType
 */
export enum EBusEmitterType {
  BusEmitterType_Reflection = 0,
  BusEmitterType_Reverb = 1,
  BusEmitterType_None = 2,
  BusEmitterType_MAX = 3,
}

/**
 * Enum AkAudio.SeqAct_AkPlayMusicWithCues.EMusicSyncType
 */
export enum EMusicSyncType {
  MusicSyncType_EndOfEvent = 0,
  MusicSyncType_UserCue = 1,
  MusicSyncType_MAX = 2,
}

/**
 * Enum AkAudio.AkBusActor.EPinnedAxisType
 */
export enum EPinnedAxisType {
  PinnedAxis_X = 0,
  PinnedAxis_Y = 1,
  PinnedAxis_Z = 2,
  PinnedAxis_None = 3,
  PinnedAxis_MAX = 4,
}

/**
 * Enum AkAudio.AkParamGroup.EReflectionSendType
 */
export enum EReflectionSendType {
  ReflectionSendType_None = 0,
  ReflectionSendType_Slapback = 1,
  ReflectionSendType_ArenaReverb = 2,
  ReflectionSendType_MAX = 3,
}
