/**
 * GFxUI Package - Enums
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

/**
 * Enum GFxUI.GFxMoviePlayer.ASType
 */
export enum ASType {
  AS_Undefined = 0,
  AS_Null = 1,
  AS_Number = 2,
  AS_Int = 3,
  AS_String = 4,
  AS_Boolean = 5,
  AS_Texture = 6,
  AS_UInt = 7,
  AS_MAX = 8,
}

/**
 * Enum GFxUI.SwfMovie.EEdition
 */
export enum EEdition {
  Edition_Default = 0,
  Edition_China = 1,
  Edition_MAX = 2,
}

/**
 * Enum GFxUI.GFxEngine.EWeatherVariant
 */
export enum EWeatherVariant {
  WeatherVariant_None = 0,
  WeatherVariant_Dawn = 1,
  WeatherVariant_Day = 2,
  WeatherVariant_Dusk = 3,
  WeatherVariant_Lab = 4,
  WeatherVariant_Night = 5,
  WeatherVariant_Rain = 6,
  WeatherVariant_Snow = 7,
  WeatherVariant_MAX = 8,
}

/**
 * Enum GFxUI.SwfMovie.FlashTextureRescale
 */
export enum FlashTextureRescale {
  FlashTextureScale_High = 0,
  FlashTextureScale_Low = 1,
  FlashTextureScale_NextLow = 2,
  FlashTextureScale_Mult4 = 3,
  FlashTextureScale_None = 4,
  FlashTextureScale_MAX = 5,
}

/**
 * Enum GFxUI.GFxMoviePlayer.GFxAlign
 */
export enum GFxAlign {
  Align_Center = 0,
  Align_TopCenter = 1,
  Align_BottomCenter = 2,
  Align_CenterLeft = 3,
  Align_CenterRight = 4,
  Align_TopLeft = 5,
  Align_TopRight = 6,
  Align_BottomLeft = 7,
  Align_BottomRight = 8,
  Align_MAX = 9,
}

/**
 * Enum GFxUI.GFxMoviePlayer.GFxCollectionMode
 */
export enum GFxCollectionMode {
  GC_Quick = 0,
  GC_Medium = 1,
  GC_Full = 2,
  GC_MAX = 3,
}

/**
 * Enum GFxUI.GFxMoviePlayer.GFxRenderTextureMode
 */
export enum GFxRenderTextureMode {
  RTM_Opaque = 0,
  RTM_Alpha = 1,
  RTM_AlphaComposite = 2,
  RTM_MAX = 3,
}

/**
 * Enum GFxUI.GFxMoviePlayer.GFxScaleMode
 */
export enum GFxScaleMode {
  SM_NoScale = 0,
  SM_ShowAll = 1,
  SM_ExactFit = 2,
  SM_NoBorder = 3,
  SM_MAX = 4,
}

/**
 * Enum GFxUI.GFxMoviePlayer.GFxTimingMode
 */
export enum GFxTimingMode {
  TM_Game = 0,
  TM_Real = 1,
  TM_MAX = 2,
}
