/**
 * OnlineSubsystemSteamworks Package - Enums
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

/**
 * Enum OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ELeaderboardFormat
 */
export enum ELeaderboardFormat {
  LF_Number = 0,
  LF_Seconds = 1,
  LF_Milliseconds = 2,
  LF_MAX = 3,
}

/**
 * Enum OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ELeaderboardRequestType
 */
export enum ELeaderboardRequestType {
  LRT_Global = 0,
  LRT_Player = 1,
  LRT_Friends = 2,
  LRT_MAX = 3,
}

/**
 * Enum OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ELeaderboardSortType
 */
export enum ELeaderboardSortType {
  LST_Ascending = 0,
  LST_Descending = 1,
  LST_MAX = 2,
}

/**
 * Enum OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ELeaderboardUpdateType
 */
export enum ELeaderboardUpdateType {
  LUT_KeepBest = 0,
  LUT_Force = 1,
  LUT_MAX = 2,
}

/**
 * Enum OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.EMuteType
 */
export enum EMuteType {
  MUTE_None = 0,
  MUTE_AllButFriends = 1,
  MUTE_All = 2,
  MUTE_MAX = 3,
}

/**
 * Enum OnlineSubsystemSteamworks.OnlineGameInterfaceSteamworks.ESteamMatchmakingType
 */
export enum ESteamMatchmakingType {
  SMT_Invalid = 0,
  SMT_LAN = 1,
  SMT_Internet = 2,
  SMT_MAX = 3,
}
