/**
 * IpDrv Package - Enums
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

/**
 * Enum IpDrv.AdHocDelegates.EAdHocCurrentState
 */
export enum EAdHocCurrentState {
  AHCS_None = 0,
  AHCS_Initializing = 1,
  AHCS_Initialized = 2,
  AHCS_Station = 3,
  AHCS_StationScanning = 4,
  AHCS_StationConnecting = 5,
  AHCS_StationConnected = 6,
  AHCS_StationDisconnected = 7,
  AHCS_StationClosing = 8,
  AHCS_AccessPointCreating = 9,
  AHCS_AccessPointCreated = 10,
  AHCS_AccessPointScanning = 11,
  AHCS_AccessPointRejecting = 12,
  AHCS_AccessPointClosing = 13,
  AHCS_Finalizing = 14,
  AHCS_Error = 15,
  AHCS_MAX = 16,
}

/**
 * Enum IpDrv.AdHocDelegates.EAdHocDesiredState
 */
export enum EAdHocDesiredState {
  AHDS_None = 0,
  AHDS_Initialized = 1,
  AHDS_CreateAccessPoint = 2,
  AHDS_CreateStation = 3,
  AHDS_ScanForAccessPoints = 4,
  AHDS_ConnectToChosenStation = 5,
  AHDS_DisconnectSpecifiedStation = 6,
  AHDS_DisconnectFromAccessPoint = 7,
  AHDS_AccessPointRejecting = 8,
  AHDS_Exit = 9,
  AHDS_Max = 10,
}

/**
 * Enum IpDrv.OnlineEventsInterfaceMcp.EEventUploadType
 */
export enum EEventUploadType {
  EUT_GenericStats = 0,
  EUT_ProfileData = 1,
  EUT_MatchmakingData = 2,
  EUT_PlaylistPopulation = 3,
  EUT_MAX = 4,
}

/**
 * Enum IpDrv.InternetLink.ELineMode
 */
export enum ELineMode {
  LMODE_auto = 0,
  LMODE_DOS = 1,
  LMODE_UNIX = 2,
  LMODE_MAC = 3,
  LMODE_MAX = 4,
}

/**
 * Enum IpDrv.InternetLink.ELinkMode
 */
export enum ELinkMode {
  MODE_Text = 0,
  MODE_Line = 1,
  MODE_Binary = 2,
  MODE_MAX = 3,
}

/**
 * Enum IpDrv.TcpLink.ELinkState
 */
export enum ELinkState {
  STATE_Initialized = 0,
  STATE_Ready = 1,
  STATE_Listening = 2,
  STATE_Connecting = 3,
  STATE_Connected = 4,
  STATE_ListenClosePending = 5,
  STATE_ConnectClosePending = 6,
  STATE_ListenClosing = 7,
  STATE_ConnectClosing = 8,
  STATE_MAX = 9,
}

/**
 * Enum IpDrv.OnlineTitleFileDownloadBase.EMcpFileCompressionType
 */
export enum EMcpFileCompressionType {
  MFCT_NONE = 0,
  MFCT_ZLIB = 1,
  MFCT_MAX = 2,
}

/**
 * Enum IpDrv.McpGroupsBase.EMcpGroupAcceptState
 */
export enum EMcpGroupAcceptState {
  MGAS_Error = 0,
  MGAS_Pending = 1,
  MGAS_Accepted = 2,
  MGAS_MAX = 3,
}

/**
 * Enum IpDrv.McpGroupsBase.EMcpGroupAccessLevel
 */
export enum EMcpGroupAccessLevel {
  MGAL_Owner = 0,
  MGAL_Member = 1,
  MGAL_Public = 2,
  MGAL_MAX = 3,
}

/**
 * Enum IpDrv.McpMessageBase.EMcpMessageCompressionType
 */
export enum EMcpMessageCompressionType {
  MMCT_NONE = 0,
  MMCT_LZO = 1,
  MMCT_ZLIB = 2,
  MMCT_MAX = 3,
}

/**
 * Enum IpDrv.MeshBeacon.EMeshBeaconBandwidthTestResult
 */
export enum EMeshBeaconBandwidthTestResult {
  MB_BandwidthTestResult_Succeeded = 0,
  MB_BandwidthTestResult_Timeout = 1,
  MB_BandwidthTestResult_Error = 2,
  MB_BandwidthTestResult_MAX = 3,
}

/**
 * Enum IpDrv.MeshBeacon.EMeshBeaconBandwidthTestState
 */
export enum EMeshBeaconBandwidthTestState {
  MB_BandwidthTestState_NotStarted = 0,
  MB_BandwidthTestState_RequestPending = 1,
  MB_BandwidthTestState_StartPending = 2,
  MB_BandwidthTestState_InProgress = 3,
  MB_BandwidthTestState_Completed = 4,
  MB_BandwidthTestState_Incomplete = 5,
  MB_BandwidthTestState_Timeout = 6,
  MB_BandwidthTestState_Error = 7,
  MB_BandwidthTestState_MAX = 8,
}

/**
 * Enum IpDrv.MeshBeacon.EMeshBeaconBandwidthTestType
 */
export enum EMeshBeaconBandwidthTestType {
  MB_BandwidthTestType_Upstream = 0,
  MB_BandwidthTestType_Downstream = 1,
  MB_BandwidthTestType_RoundtripLatency = 2,
  MB_BandwidthTestType_MAX = 3,
}

/**
 * Enum IpDrv.MeshBeaconClient.EMeshBeaconClientState
 */
export enum EMeshBeaconClientState {
  MBCS_None = 0,
  MBCS_Connecting = 1,
  MBCS_Connected = 2,
  MBCS_ConnectionFailed = 3,
  MBCS_AwaitingResponse = 4,
  MBCS_Closed = 5,
  MBCS_MAX = 6,
}

/**
 * Enum IpDrv.MeshBeacon.EMeshBeaconConnectionResult
 */
export enum EMeshBeaconConnectionResult {
  MB_ConnectionResult_Succeeded = 0,
  MB_ConnectionResult_Duplicate = 1,
  MB_ConnectionResult_Timeout = 2,
  MB_ConnectionResult_Error = 3,
  MB_ConnectionResult_MAX = 4,
}

/**
 * Enum IpDrv.MeshBeacon.EMeshBeaconPacketType
 */
export enum EMeshBeaconPacketType {
  MB_Packet_UnknownType = 0,
  MB_Packet_ClientNewConnectionRequest = 1,
  MB_Packet_ClientBeginBandwidthTest = 2,
  MB_Packet_ClientCreateNewSessionResponse = 3,
  MB_Packet_HostNewConnectionResponse = 4,
  MB_Packet_HostBandwidthTestRequest = 5,
  MB_Packet_HostCompletedBandwidthTest = 6,
  MB_Packet_HostTravelRequest = 7,
  MB_Packet_HostCreateNewSessionRequest = 8,
  MB_Packet_DummyData = 9,
  MB_Packet_Heartbeat = 10,
  MB_Packet_MAX = 11,
}

/**
 * Enum IpDrv.OnlineImageDownloaderWeb.EOnlineImageDownloadState
 */
export enum EOnlineImageDownloadState {
  PIDS_NotStarted = 0,
  PIDS_Downloading = 1,
  PIDS_Succeeded = 2,
  PIDS_Failed = 3,
  PIDS_MAX = 4,
}

/**
 * Enum IpDrv.PartyBeaconClient.EPartyBeaconClientRequest
 */
export enum EPartyBeaconClientRequest {
  PBClientRequest_NewReservation = 0,
  PBClientRequest_UpdateReservation = 1,
  PBClientRequest_MAX = 2,
}

/**
 * Enum IpDrv.PartyBeaconClient.EPartyBeaconClientState
 */
export enum EPartyBeaconClientState {
  PBCS_None = 0,
  PBCS_Connecting = 1,
  PBCS_Connected = 2,
  PBCS_ConnectionFailed = 3,
  PBCS_AwaitingResponse = 4,
  PBCS_Closed = 5,
  PBCS_MAX = 6,
}

/**
 * Enum IpDrv.PartyBeaconHost.EPartyBeaconHostState
 */
export enum EPartyBeaconHostState {
  PBHS_AllowReservations = 0,
  PBHS_DenyReservations = 1,
  PBHS_MAX = 2,
}

/**
 * Enum IpDrv.PartyBeacon.EPartyReservationResult
 */
export enum EPartyReservationResult {
  PRR_GeneralError = 0,
  PRR_PartyLimitReached = 1,
  PRR_IncorrectPlayerCount = 2,
  PRR_RequestTimedOut = 3,
  PRR_ReservationDuplicate = 4,
  PRR_ReservationNotFound = 5,
  PRR_ReservationAccepted = 6,
  PRR_ReservationDenied = 7,
  PRR_MAX = 8,
}

/**
 * Enum IpDrv.InternetLink.EReceiveMode
 */
export enum EReceiveMode {
  RMODE_Manual = 0,
  RMODE_Event = 1,
  RMODE_MAX = 2,
}

/**
 * Enum IpDrv.WebRequest.ERequestType
 */
export enum ERequestType {
  Request_GET = 0,
  Request_POST = 1,
  Request_MAX = 2,
}

/**
 * Enum IpDrv.PartyBeacon.EReservationPacketType
 */
export enum EReservationPacketType {
  RPT_UnknownPacketType = 0,
  RPT_ClientReservationRequest = 1,
  RPT_ClientReservationUpdateRequest = 2,
  RPT_ClientCancellationRequest = 3,
  RPT_HostReservationResponse = 4,
  RPT_HostReservationCountUpdate = 5,
  RPT_HostTravelRequest = 6,
  RPT_HostIsReady = 7,
  RPT_HostHasCancelled = 8,
  RPT_Heartbeat = 9,
  RPT_MAX = 10,
}

/**
 * Enum IpDrv.TitleFileDownloadCache.ETitleFileFileOp
 */
export enum ETitleFileFileOp {
  TitleFile_None = 0,
  TitleFile_Save = 1,
  TitleFile_Load = 2,
  TitleFile_MAX = 3,
}

/**
 * Enum IpDrv.McpClashMobBase.McpChallengeFileStatus
 */
export enum McpChallengeFileStatus {
  MCFS_NotStarted = 0,
  MCFS_Pending = 1,
  MCFS_Success = 2,
  MCFS_Failed = 3,
  MCFS_MAX = 4,
}
