/**
 * ProjectX Package - Enums
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

/**
 * Enum ProjectX.EpicLogin_X.AgeGateState
 */
export enum AgeGateState {
  AGS_Unknown = 0,
  AGS_Active = 1,
  AGS_Complete = 2,
  AGS_MAX = 3,
}

/**
 * Enum ProjectX.OnlineGameDLC_X.DLCOwnershipState
 */
export enum DLCOwnershipState {
  DLCOwnershipState_Unknown = 0,
  DLCOwnershipState_Owned = 1,
  DLCOwnershipState_NotOwned = 2,
  DLCOwnershipState_Error = 3,
  DLCOwnershipState_MAX = 4,
}

/**
 * Enum ProjectX.AnimNodeSeries_X.EAnimNodeSeriesChild
 */
export enum EAnimNodeSeriesChild {
  AnimNodeSeries_Idle = 0,
  AnimNodeSeries_Intro = 1,
  AnimNodeSeries_Loop = 2,
  AnimNodeSeries_Outro = 3,
  AnimNodeSeries_MAX = 4,
}

/**
 * Enum ProjectX.FXActor_X.EAttachActorLocationUnlockFlags
 */
export enum EAttachActorLocationUnlockFlags {
  EAALUF_None = 0,
  EAALUF_X = 1,
  EAALUF_Y = 2,
  EAALUF_Z = 3,
  EAALUF_MAX = 4,
}

/**
 * Enum ProjectX.RemoteAvatarPermissions_X.EAvatarPermission
 */
export enum EAvatarPermission {
  AP_True = 0,
  AP_False = 1,
  AP_Hidden = 2,
  AP_MAX = 3,
}

/**
 * Enum ProjectX.RemoteAvatarPermissions_X.EAvatarRequestTryGetResult
 */
export enum EAvatarRequestTryGetResult {
  ARTGR_NotFound = 0,
  ARTGR_False = 1,
  ARTGR_True = 2,
  ARTGR_Hidden = 3,
  ARTGR_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.EAxisSign
 */
export enum EAxisSign {
  AxisSign_None = 0,
  AxisSign_Positive = 1,
  AxisSign_Negative = 2,
  AxisSign_MAX = 3,
}

/**
 * Enum ProjectX._Types_X.EBanType
 */
export enum EBanType {
  BanType_None = 0,
  BanType_Auth = 1,
  BanType_Chat = 2,
  BanType_Voice = 3,
  BanType_Club = 4,
  BanType_Trade = 5,
  BanType_QuitPenalty = 6,
  BanType_Social = 7,
  BanType_MAX = 8,
}

/**
 * Enum ProjectX._Types_X.EButtonPressType
 */
export enum EButtonPressType {
  BPT_Normal = 0,
  BPT_Tap = 1,
  BPT_Hold = 2,
  BPT_DoubleTap = 3,
  BPT_Toggle = 4,
  BPT_MAX = 5,
}

/**
 * Enum ProjectX._Types_X.EChatChannel
 */
export enum EChatChannel {
  EChatChannel_Match = 0,
  EChatChannel_Team = 1,
  EChatChannel_Party = 2,
  EChatChannel_Individual = 3,
  EChatChannel_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.EChatPermissionLevel
 */
export enum EChatPermissionLevel {
  CPL_Everybody = 0,
  CPL_FriendsAndTeam = 1,
  CPL_Friends = 2,
  CPL_Nobody = 3,
  CPL_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.EChatReportingLevel
 */
export enum EChatReportingLevel {
  VRP_OffWhenPossible = 0,
  VRP_Always = 1,
  VRP_MAX = 2,
}

/**
 * Enum ProjectX._Types_X.EClubBadge
 */
export enum EClubBadge {
  ClubBadge_None = 0,
  ClubBadge_Tier1 = 1,
  ClubBadge_Tier2 = 2,
  ClubBadge_Tier3 = 3,
  ClubBadge_MAX = 4,
}

/**
 * Enum ProjectX.ClubUtil_X.EClubColorChange
 */
export enum EClubColorChange {
  ClubColorChange_None = 0,
  ClubColorChange_SwapTeams = 1,
  ClubColorChange_SwapPrimaryAccent0 = 2,
  ClubColorChange_SwapPrimaryAccent1 = 3,
  ClubColorChange_SwapPrimaryAccent = 4,
  ClubColorChange_WhiteVsBlack = 5,
  ClubColorChange_Gray1 = 6,
  ClubColorChange_MAX = 7,
}

/**
 * Enum ProjectX._Types_X.EClubInviteEventType
 */
export enum EClubInviteEventType {
  CIET_Accept = 0,
  CIET_Reject = 1,
  CIET_Send = 2,
  CIET_MAX = 3,
}

/**
 * Enum ProjectX._Types_X.EClubMemberAction
 */
export enum EClubMemberAction {
  ClubMemberAction_RemoveMember = 0,
  ClubMemberAction_SetClubOwner = 1,
  ClubMemberAction_SetClubManager = 2,
  ClubMemberAction_RemoveClubManager = 3,
  ClubMemberAction_InviteParty = 4,
  ClubMemberAction_RequestJoinParty = 5,
  ClubMemberAction_ViewProfile = 6,
  ClubMemberAction_BlockMember = 7,
  ClubMemberAction_UnblockMember = 8,
  ClubMemberAction_AddEpicFriend = 9,
  ClubMemberAction_RemoveEpicFriend = 10,
  ClubMemberAction_ReportMember = 11,
  ClubMemberAction_MAX = 12,
}

/**
 * Enum ProjectX._Types_X.EClubRole
 */
export enum EClubRole {
  ClubRole_Member = 0,
  ClubRole_Owner = 1,
  ClubRole_Manager = 2,
  ClubRole_None = 3,
  ClubRole_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.EConnectionType_X
 */
export enum EConnectionType_X {
  ConnectionType_Unknown = 0,
  ConnectionType_Wired = 1,
  ConnectionType_WiFi = 2,
  ConnectionType_Mixed = 3,
  ConnectionType_Docked = 4,
  ConnectionType_MAX = 5,
}

/**
 * Enum ProjectX._Types_X.EConsoleQualityMode
 */
export enum EConsoleQualityMode {
  ConsoleQualityMode_Performance = 0,
  ConsoleQualityMode_Quality = 1,
  ConsoleQualityMode_MAX = 2,
}

/**
 * Enum ProjectX._Types_X.EDatabaseEnvironment
 */
export enum EDatabaseEnvironment {
  DBE_DevLocal = 0,
  DBE_Dev = 1,
  DBE_Test = 2,
  DBE_Production = 3,
  DBE_MAX = 4,
}

/**
 * Enum ProjectX.GFxDataCallback_X.EDataCallbackType
 */
export enum EDataCallbackType {
  DataCallbackType_All = 0,
  DataCallbackType_Table = 1,
  DataCallbackType_Row = 2,
  DataCallbackType_Value = 3,
  DataCallbackType_MAX = 4,
}

/**
 * Enum ProjectX.DynamicValue_X.EDynamicValueModType
 */
export enum EDynamicValueModType {
  ModType_Add = 0,
  ModType_Multiply = 1,
  ModType_MultiplyAdd = 2,
  ModType_Set = 3,
  ModType_MAX = 4,
}

/**
 * Enum ProjectX.RPC_ReportExploiter_X.EExploitType
 */
export enum EExploitType {
  ET_FakeProducts = 0,
  ET_InvisibleCar = 1,
  ET_MultipleSplitscreen = 2,
  ET_URLPrivateMatchInjection = 3,
  ET_MAX = 4,
}

/**
 * Enum ProjectX.FXActor_X.EFXComponentState
 */
export enum EFXComponentState {
  FXComponentState_Detached = 0,
  FXComponentState_Attached = 1,
  FXComponentState_PendingDetach = 2,
  FXComponentState_MAX = 3,
}

/**
 * Enum ProjectX.FXActor_X.EFXComponentTarget
 */
export enum EFXComponentTarget {
  FXComponentTarget_All = 0,
  FXComponentTarget_Local = 1,
  FXComponentTarget_NonLocal = 2,
  FXComponentTarget_MAX = 3,
}

/**
 * Enum ProjectX.FXActor_X.EFXLocality
 */
export enum EFXLocality {
  FXLocality_Controller = 0,
  FXLocality_AlwaysLocal = 1,
  FXLocality_NeverLocal = 2,
  FXLocality_MAX = 3,
}

/**
 * Enum ProjectX.FXActor_X.EFXOverrideAttachBehavior
 */
export enum EFXOverrideAttachBehavior {
  FXOverrideAttach_None = 0,
  FXOverrideAttach_Owner = 1,
  FXOverrideAttach_MAX = 2,
}

/**
 * Enum ProjectX._Types_X.EJoinMatchType
 */
export enum EJoinMatchType {
  JMT_Public = 0,
  JMT_Private = 1,
  JMT_MAX = 2,
}

/**
 * Enum ProjectX.OnlineLegalTextEOS_X.ELegalSyncState
 */
export enum ELegalSyncState {
  LSS_NotStarted = 0,
  LSS_Failed = 1,
  LSS_InProgress = 2,
  LSS_AcceptanceRequired = 3,
  LSS_Accepted = 4,
  LSS_MAX = 5,
}

/**
 * Enum ProjectX.BlogTile_X.ELinkType
 */
export enum ELinkType {
  LinkType_None = 0,
  LinkType_RocketPass = 1,
  LinkType_Event = 2,
  LinkType_ESports = 3,
  LinkType_Clubs = 4,
  LinkType_MAX = 5,
}

/**
 * Enum ProjectX.EpicLogin_X.ELoginMethod
 */
export enum ELoginMethod {
  LoginMethod_RefreshToken = 0,
  LoginMethod_PlatformAuthTicket = 1,
  LoginMethod_MAX = 2,
}

/**
 * Enum ProjectX.MaterialEffect_X.EMaterialEffectStage
 */
export enum EMaterialEffectStage {
  EFFECT_INACTIVE = 0,
  EFFECT_FADE_IN = 1,
  EFFECT_ACTIVE = 2,
  EFFECT_FADE_OUT = 3,
  EFFECT_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.ENewsInteractionType
 */
export enum ENewsInteractionType {
  NIT_VIEW = 0,
  NIT_ENGAGED = 1,
  NIT_MAX = 2,
}

/**
 * Enum ProjectX.EncodeObject_X.EObjectEncoding
 */
export enum EObjectEncoding {
  OPSE_UObject = 0,
  OPSE_Json = 1,
  OPSE_MAX = 2,
}

/**
 * Enum ProjectX._Types_X.EOnlinePlayerPermission
 */
export enum EOnlinePlayerPermission {
  OPP_PrivateMatchAdmin = 0,
  OPP_SuperPrivateMatchAdmin = 1,
  OPP_AntiCheatExempt = 2,
  OPP_MAX = 3,
}

/**
 * Enum ProjectX._Types_X.EOnlinePlayerRole
 */
export enum EOnlinePlayerRole {
  OPR_PrivateMatchAdmin = 0,
  OPR_SuperPrivateMatchAdmin = 1,
  OPR_AntiCheatExempt = 2,
  OPR_MAX = 3,
}

/**
 * Enum ProjectX._Types_X.EOnlineStorageFiles
 */
export enum EOnlineStorageFiles {
  OSF_Save = 0,
  OSF_Settings = 1,
  OSF_MAX = 2,
}

/**
 * Enum ProjectX._Types_X.EPartyMatchmakingRestriction
 */
export enum EPartyMatchmakingRestriction {
  PMR_NotOriginalAppOwner = 0,
  PMR_PendingLicenseAgreement = 1,
  PMR_InMainMenu = 2,
  PMR_NotLoggedInPsyNet = 3,
  PMR_MAX = 4,
}

/**
 * Enum ProjectX.ReservationsPasswordMessage_X.EPasswordFailureReason
 */
export enum EPasswordFailureReason {
  PFR_Empty = 0,
  PFR_Mismatch = 1,
  PFR_MAX = 2,
}

/**
 * Enum ProjectX.PerCon_X.EPerConStatus
 */
export enum EPerConStatus {
  PerConStatus_Disabled = 0,
  PerConStatus_Enabled = 1,
  PerConStatus_MAX = 2,
}

/**
 * Enum ProjectX._Types_X.EPsyNetEnvironment
 */
export enum EPsyNetEnvironment {
  EPE_Unset = 0,
  EPE_Environment1 = 1,
  EPE_Environment2 = 2,
  EPE_Environment3 = 3,
  EPE_Environment4 = 4,
  EPE_Environment5 = 5,
  EPE_MAX = 6,
}

/**
 * Enum ProjectX.OnlinePlayerRegionRestrictions_X.ERegionRestriction
 */
export enum ERegionRestriction {
  RegionRestriction_Unknown = 0,
  RegionRestriction_KeyCrate = 1,
  RegionRestriction_Trade = 2,
  RegionRestriction_KeyRocketPassTier = 3,
  RegionRestriction_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.ERemappable
 */
export enum ERemappable {
  Remappable_All = 0,
  Remappable_Key = 1,
  Remappable_Axis = 2,
  Remappable_KeyTriggerAxis = 3,
  Remappable_None = 4,
  Remappable_MAX = 5,
}

/**
 * Enum ProjectX._Types_X.EReservationStatus
 */
export enum EReservationStatus {
  ReservationStatus_None = 0,
  ReservationStatus_Reserved = 1,
  ReservationStatus_Joining = 2,
  ReservationStatus_InGame = 3,
  ReservationStatus_MAX = 4,
}

/**
 * Enum ProjectX.ClanforgeReservation_X.EReserveState
 */
export enum EReserveState {
  ReserveState_Unitialized = 0,
  ReserveState_Unreserved = 1,
  ReserveState_Reserved = 2,
  ReserveState_MAX = 3,
}

/**
 * Enum ProjectX.RPC_X.ERPCPriority
 */
export enum ERPCPriority {
  RPC_Low = 0,
  RPC_Medium = 1,
  RPC_High = 2,
  RPC_MAX = 3,
}

/**
 * Enum ProjectX._Types_X.ESeverityType
 */
export enum ESeverityType {
  SeverityType_None = 0,
  SeverityType_Low = 1,
  SeverityType_Medium = 2,
  SeverityType_High = 3,
  SeverityType_MAX = 4,
}

/**
 * Enum ProjectX.ShakeComponent_X.EShakeReceiver
 */
export enum EShakeReceiver {
  ShakeReceiver_All = 0,
  ShakeReceiver_Local = 1,
  ShakeReceiver_NonLocal = 2,
  ShakeReceiver_MAX = 3,
}

/**
 * Enum ProjectX.TcpConnection.ETcpConnectionState
 */
export enum ETcpConnectionState {
  TcpConnectionState_Invalid = 0,
  TcpConnectionState_Connecting = 1,
  TcpConnectionState_Connected = 2,
  TcpConnectionState_Disconnected = 3,
  TcpConnectionState_MAX = 4,
}

/**
 * Enum ProjectX._Types_X.ETrackingPermissionType
 */
export enum ETrackingPermissionType {
  Tracking_Marketing = 0,
  Tracking_Functional = 1,
  Tracking_Experience = 2,
  Tracking_MAX = 3,
}

/**
 * Enum ProjectX._Types_X.ETradePermissionLevel
 */
export enum ETradePermissionLevel {
  TPL_Everybody = 0,
  TPL_FriendsAndParty = 1,
  TPL_Friends = 2,
  TPL_Nobody = 3,
  TPL_MAX = 4,
}

/**
 * Enum ProjectX.WebRequest_X.EWebRequestState
 */
export enum EWebRequestState {
  WebRequestState_PendingSend = 0,
  WebRequestState_PendingResponse = 1,
  WebRequestState_Success = 2,
  WebRequestState_Error = 3,
  WebRequestState_MAX = 4,
}

/**
 * Enum ProjectX.TcpConnection.EWebSocketState
 */
export enum EWebSocketState {
  WebSocketState_NotRequired = 0,
  WebSocketState_NeedsHandshake = 1,
  WebSocketState_Connected = 2,
  WebSocketState_MAX = 3,
}

/**
 * Enum ProjectX.WordFilterTypes_X.EWordFilterUsage
 */
export enum EWordFilterUsage {
  WordFilterUsage_PlayerName = 0,
  WordFilterUsage_TrainingName = 1,
  WordFilterUsage_LanServerName = 2,
  WordFilterUsage_CustomTeamName = 3,
  WordFilterUsage_TourName = 4,
  WordFilterUsage_TourTeamName = 5,
  WordFilterUsage_ClubName = 6,
  WordFilterUsage_ClubTag = 7,
  WordFilterUsage_ClubTagPlayerName = 8,
  WordFilterUsage_MatchChat = 9,
  WordFilterUsage_PartyChat = 10,
  WordFilterUsage_MAX = 11,
}

/**
 * Enum ProjectX.FakeData_X.FakeDataEnum
 */
export enum FakeDataEnum {
  FakeData = 0,
  FakeData_1 = 1,
  FakeData_2 = 2,
  FakeData_Count = 3,
  FakeData_MAX = 4,
}

/**
 * Enum ProjectX.OnlineGameParty_X.PartyProcessingStatus
 */
export enum PartyProcessingStatus {
  PPS_None = 0,
  PPS_Create = 1,
  PPS_Join = 2,
  PPS_MAX = 3,
}

/**
 * Enum ProjectX.RegionPing_X.RegionPingResult
 */
export enum RegionPingResult {
  PingResult_NotUsable = 0,
  PingResult_UsingCache = 1,
  PingResult_UsingSuccessfulPing = 2,
  PingResult_MAX = 3,
}
