/**
 * RocketLeagueSDK - Game Defines
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

export type FName = {
  Index: number;
  Number: number;
};

export type FString = {
  Data: bigint;
  Count: number;
  Max: number;
};

export type FScriptDelegate = {
  Object: bigint;
  FunctionName: FName;
};

export type FPointer = {
  Dummy: bigint;
};

export type FQWord = {
  A: number;
  B: number;
};

export type FMap_Mirror = {
  Data: bigint;
  Count: number;
  Max: number;
};
