/**
 * Core Package - Classes
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

import type { FName, FScriptDelegate } from '../types/GameDefines';
import type { EAxis, EDebugBreakType } from '../enums/Core';
import type {
  FArray_Mirror,
  FAsyncDelegateInfo,
  FColor,
  FGuid,
  FInterpCurveFloat,
  FInterpCurveVector,
  FInterpCurveVector2D,
  FLinearColor,
  FMap_Mirror,
  FMatrix,
  FObjectProviderPendingCallback,
  FObjectProviderSubscription,
  FPointer,
  FQuat,
  FRotator,
  FRotatorDegrees,
  FRotatorRadians,
  FScriptWarning,
  FVector,
  FVector2D,
} from '../structs/Core';
import type { UScriptGroup_ORS } from './Engine';

/**
 * Class Core.Object
 * Size: 0x0060
 */
export type UObject = {
  VfTableObject: FPointer; // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer; // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint; // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer; // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer; // 0x0020 (0x0008) [FPointer]
  Linker: UObject; // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer; // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number; // 0x0038 (0x0004) [int32]
  NetIndex: number; // 0x003c (0x0004) [int32]
  Outer: UObject; // 0x0040 (0x0008) [UObject*]
  Name: FName; // 0x0048 (0x0008) [FName]
  Class: UObject; // 0x0050 (0x0008) [UObject*]
  ObjectArchetype: UObject; // 0x0058 (0x0008) [UObject*]
};

// Object Functions
// static RSmoothInterpTo(From: FRotator, To: FRotator, Lambda: number, DeltaTime: number): FRotator
// static VSmoothInterpTo(From: FVector, To: FVector, Lambda: number, DeltaTime: number): FVector
// static FSmoothInterpTo(From: number, To: number, Lambda: number, DeltaTime: number): number
// static GetSmoothInterpLerpValue(Lambda: number, DeltaTime: number): number
// static GetTypedOuter(ObjClass: UObject): UObject
// MarkPendingKill(): void
// static NotNone(O: UObject): boolean
// static SwapArrayItems(): void
// static Swap(): void
// static SumFloat(Total: number, Value: number): number
// static SumInt(Total: number, Value: number): number
// static SortDescendingFloat(A: number, B: number): number
// static SortAscendingFloat(A: number, B: number): number
// static SortDescendingString(A: string, B: string): number
// static SortAscendingString(A: string, B: string): number
// static SortDescendingQWORD(A: bigint, B: bigint): number
// static SortAscendingQWORD(A: bigint, B: bigint): number
// static SortDescendingInt(A: number, B: number): number
// static SortAscendingInt(A: number, B: number): number
// static PadString(Str: string, Characters: number): string
// static GetFrameCounter(): bigint
// static GetScaledAxisValue(Value: number, Sensitivity: number, MaxSensitivity: number): number
// static GetSingleton(ObjClass: UObject): UObject
// static GetObjectProvider(): UObjectProvider
// static IsAutomationTest(): boolean
// ToJson(): string
// SetRooted(bRooted: boolean): void
// static ProfNodeEvent(EventName: string): void
// static ProfNodeSetDepthThreshold(Depth: number): void
// static ProfNodeSetTimeThresholdSeconds(Threshold: number): void
// static ProfNodeStop(AssumedTimerIndex: number): void
// static ProfNodeStart(TimerName: string): number
// static CreateGuidString(): string
// static GetStringFromGuid(InGuid: FGuid): string
// static GetGuidFromString(InGuidString: string): FGuid
// static CreateGuid(): FGuid
// static IsGuidValid(InGuid: FGuid): boolean
// static InvalidateGuid(InGuid: FGuid): void
// FindStructProperty(PropertyClass: UObject, PropertyName: FName, StructName: FName): UObject
// FindProperty(PropertyClass: UObject, PropertyName: FName): UObject
// DuplicateObject(Template: UObject, ObjOuter: UObject, DestClass: UObject): UObject
// RunningAverage(OldAverage: number, NewValue: number, NewCount: number): number
// static GetCurrentTime(): number
// GetMaxLinearColorBrightness(C: FLinearColor): FLinearColor
// GetMaxColorBrightness(C: FColor): FColor
// static LABtoRGB(C: FLinearColor): FLinearColor
// static RGBtoLAB(C: FLinearColor): FLinearColor
// static HSVtoRGB(C: FLinearColor): FLinearColor
// static RGBtoHSV(C: FLinearColor): FLinearColor
// static IntToLinearColor(I: number): FLinearColor
// static IntToColor(I: number): FColor
// static LinearColorToInt(C: FLinearColor): number
// static ColorToInt(C: FColor): number
// SolveVelocityQuadratic(Distance: number, Speed: number, Accel: number, Time: number): boolean
// Sign(X: number): number
// static MakeVector2D(X: number, Y: number): FVector2D
// static VAbs(V: FVector): FVector
// static MakeVector(X: number, Y: number, Z: number): FVector
// FlattenVector(NormalToFlatten: FVector, PlaneNormal: FVector): FVector
// GetRealArchetypeName(): FName
// static FormatTime(Seconds: number): string
// static GetTextArchetype(ArchetypeClass: UObject, Path: string): UObject
// IsArchetype(): boolean
// UnsubscribeFromAllEvents(): void
// NewInstance(ObjOuter: UObject, ObjName: FName): UObject
// PrintDebugInfo(Drawer: UDebugDrawer): void
// static RotatorFromInt(RotationPitchAndYaw: number): FRotator
// static RotatorToInt(Rotation: FRotator): number
// static GetLanguage(): string
// GetRandomOptionSumFrequency(FreqList: number[]): number
// GetBuildChangelistNumber(): number
// GetEngineVersion(): number
// GetAppSeconds(): number
// GetSystemTime(Year: number, Month: number, DayOfWeek: number, Day: number, Hour: number, Min: number, Sec: number, MSec: number): void
// TimeStamp(): string
// TransformVectorByRotation(SourceRotation: FRotator, SourceVector: FVector, bInverse: boolean): FVector
// GetPackageName(): FName
// IsPendingKill(): boolean
// RangeByteToFloatUnsigned(inputByte: number): number
// RangeByteToFloatSigned(inputByte: number): number
// FloatToRangeByteUnsigned(inputFloat: number): number
// FloatToRangeByteSigned(inputFloat: number): number
// static UnwindHeading(A: number): number
// static FindDeltaAngle(A1: number, A2: number): number
// static GetHeadingAngle(Dir: FVector): number
// static GetAngularDegreesFromRadians(OutFOV: FVector2D): void
// static GetAngularFromDotDist(OutAngDist: FVector2D, DotDist: FVector2D): void
// static GetAngularDistance(OutAngularDist: FVector2D, Direction: FVector, AxisX: FVector, AxisY: FVector, AxisZ: FVector): boolean
// static GetDotDistance(OutDotDist: FVector2D, Direction: FVector, AxisX: FVector, AxisY: FVector, AxisZ: FVector): boolean
// LinePlaneIntersection(LineStart: FVector, LineEnd: FVector, PlaneOrigin: FVector, PlaneNormal: FVector, Out_Intersection: FVector, Out_T: number, bCheckLineSegment: boolean): boolean
// static PointProjectToPlane(Point: FVector, A: FVector, B: FVector, C: FVector): FVector
// PointDistToPlane(Point: FVector, Orientation: FRotator, Origin: FVector, out_ClosestPoint: FVector): number
// PointDistToSegment(Point: FVector, StartPoint: FVector, EndPoint: FVector, OutClosestPoint: FVector): number
// static PointDistToLine(Point: FVector, Line: FVector, Origin: FVector, OutClosestPoint: FVector): number
// static GetPerObjectConfigObjects(SearchClass: UObject, OutObject: UObject, ObjectOuter: UObject, MaxResults: number): void
// static GetPerObjectConfigSections(SearchClass: UObject, out_SectionNames: string[], ObjectOuter: UObject, MaxResults: number): boolean
// static ImportJSON(PropertyName: string, JSON: string): void
// static StaticSaveConfig(): void
// SaveConfig(): void
// static LoadSeekFreeObject(ObjClass: UObject, Path: string): UObject
// static FindObject(ObjectName: string, ObjectClass: UObject): UObject
// static DynamicLoadObject(ObjectName: string, ObjectClass: UObject, MayFail: boolean): UObject
// static EnumFromString(E: UObject, ValueName: FName): number
// static GetEnum(E: UObject, I: number): FName
// Disable(ProbeFunc: FName): void
// Enable(ProbeFunc: FName): void
// ContinuedState(): void
// PausedState(): void
// PoppedState(): void
// PushedState(): void
// EndState(NextStateName: FName): void
// BeginState(PreviousStateName: FName): void
// DumpStateStack(): void
// PopState(bPopAll: boolean): void
// PushState(NewState: FName, NewLabel: FName): void
// GetStateName(): FName
// IsChildState(TestState: FName, TestParentState: FName): boolean
// IsInState(TestState: FName, bTestStateStack: boolean): boolean
// GotoState(NewState: FName, Label: FName, bForceEvents: boolean, bKeepStack: boolean): void
// static IsUTracing(): boolean
// static SetUTracing(bShouldUTrace: boolean): void
// static GetFuncName(): FName
// static DebugBreak(UserFlags: number, DebuggerType: EDebugBreakType): void
// static GetScriptTrace(): string
// static ScriptTrace(): void
// static ParseLocalizedPropertyPath(PathName: string): string
// static Localize(SectionName: string, KeyName: string, PackageName: string, bOptional: boolean): string
// static WarnInternal(S: string): void
// static LogInternal(S: string, Tag: FName, bFileOnly: boolean): void
// static LinearColorLerp(ColorA: FLinearColor, ColorB: FLinearColor, Alpha: number): FLinearColor
// static Subtract_LinearColorLinearColor(A: FLinearColor, B: FLinearColor): FLinearColor
// static Multiply_LinearColorFloat(LC: FLinearColor, Mult: number): FLinearColor
// static ConvertFromSRGB(OldColor: FLinearColor): FLinearColor
// static LinearColorToColor(OldColor: FLinearColor): FColor
// static ColorToLinearColor(OldColor: FColor): FLinearColor
// static MakeLinearColor(R: number, G: number, B: number, A: number): FLinearColor
// static LerpColor(A: FColor, B: FColor, Alpha: number): FColor
// static MakeColor(R: number, G: number, B: number, A: number): FColor
// static Add_ColorColor(A: FColor, B: FColor): FColor
// static Multiply_ColorFloat(A: FColor, B: number): FColor
// static Multiply_FloatColor(A: number, B: FColor): FColor
// static Subtract_ColorColor(A: FColor, B: FColor): FColor
// static EvalInterpCurveVector2D(Vector2DCurve: FInterpCurveVector2D, InVal: number): FVector2D
// static AutoSetTangentsVector(Curve: FInterpCurveVector): void
// static EvalInterpCurveVector(VectorCurve: FInterpCurveVector, InVal: number): FVector
// static AutoSetTangentsFloat(Curve: FInterpCurveFloat): void
// static EvalInterpCurveFloat(FloatCurve: FInterpCurveFloat, InVal: number): number
// static vect2d(InX: number, InY: number): FVector2D
// static GetMappedRangeValue(InputRange: FVector2D, OutputRange: FVector2D, Value: number): number
// static GetRangePctByValue(Range: FVector2D, Value: number): number
// static GetRangeValueByPct(Range: FVector2D, Pct: number): number
// static V2DNormal(A: FVector2D): FVector2D
// static V2DSizeSq(A: FVector2D): number
// static V2DSize(A: FVector2D): number
// static Dot_Vector2DVector2D(A: FVector2D, B: FVector2D): number
// static SubtractEqual_Vector2DVector2D(A: FVector2D, B: FVector2D): FVector2D
// static AddEqual_Vector2DVector2D(A: FVector2D, B: FVector2D): FVector2D
// static DivideEqual_Vector2DFloat(A: FVector2D, B: number): FVector2D
// static MultiplyEqual_Vector2DFloat(A: FVector2D, B: number): FVector2D
// static Divide_Vector2DFloat(A: FVector2D, B: number): FVector2D
// static Multiply_Vector2DFloat(A: FVector2D, B: number): FVector2D
// static Subtract_Vector2DVector2D(A: FVector2D, B: FVector2D): FVector2D
// static Add_Vector2DVector2D(A: FVector2D, B: FVector2D): FVector2D
// static Subtract_QuatQuat(A: FQuat, B: FQuat): FQuat
// static Add_QuatQuat(A: FQuat, B: FQuat): FQuat
// static QuatSlerp(A: FQuat, B: FQuat, Alpha: number, bShortestPath: boolean): FQuat
// static QuatToRotator(A: FQuat): FRotator
// static QuatFromRotator(A: FRotator): FQuat
// static QuatFromAxisAndAngle(Axis: FVector, Angle: number): FQuat
// static QuatFindBetween(A: FVector, B: FVector): FQuat
// static QuatRotateVector(A: FQuat, B: FVector): FVector
// static QuatInvert(A: FQuat): FQuat
// static QuatDot(A: FQuat, B: FQuat): number
// static QuatProduct(A: FQuat, B: FQuat): FQuat
// static MatrixGetAxis(TM: FMatrix, Axis: EAxis): FVector
// static MatrixGetOrigin(TM: FMatrix): FVector
// static MatrixGetRotator(TM: FMatrix): FRotator
// static MakeRotationMatrix(Rotation: FRotator): FMatrix
// static MakeRotationTranslationMatrix(Translation: FVector, Rotation: FRotator): FMatrix
// static InverseTransformNormal(TM: FMatrix, A: FVector): FVector
// static TransformNormal(TM: FMatrix, A: FVector): FVector
// static InverseTransformVector(TM: FMatrix, A: FVector): FVector
// static TransformVector(TM: FMatrix, A: FVector): FVector
// static Multiply_MatrixMatrix(A: FMatrix, B: FMatrix): FMatrix
// static NotEqual_NameName(A: FName, B: FName): boolean
// static EqualEqual_NameName(A: FName, B: FName): boolean
// IsA(ClassName: FName): boolean
// static ClassIsChildOf(TestClass: UObject, ParentClass: UObject): boolean
// static NotEqual_InterfaceInterface(A: UInterface, B: UInterface): boolean
// static EqualEqual_InterfaceInterface(A: UInterface, B: UInterface): boolean
// static NotEqual_ObjectObject(A: UObject, B: UObject): boolean
// static EqualEqual_ObjectObject(A: UObject, B: UObject): boolean
// GetPathName(): string
// static PathName(CheckObject: UObject): string
// static SplitString(Source: string, Delimiter: string, bCullEmpty: boolean): string[]
// static ParseStringIntoArray(BaseString: string, Pieces: string[], delim: string, bCullEmpty: boolean): void
// static ContainsWhitespace(Text: string): boolean
// static RepeatString(InValue: string, Count: number): string
// static JoinArrayQWord(QWordArray: bigint[], delim: string, bIgnoreBlanks: boolean): string
// static JoinArrayInt(IntArray: number[], delim: string, bIgnoreBlanks: boolean): string
// static JoinArrayName(NameArray: FName[], delim: string, bIgnoreBlanks: boolean): string
// static JoinArrayStr(StringArray: string[], delim: string, bIgnoreBlanks: boolean): string
// static JoinArray(StringArray: string[], out_Result: string, delim: string, bIgnoreBlanks: boolean): void
// static GetRightMost(Text: string): string
// static Split(Text: string, SplitStr: string, bOmitSplitStr: boolean): string
// static TCharToUTF8(Src: string): string
// static UTF8ToTChar(Src: string): string
// static MakeAsciiSafe(InStr: string): string
// static PadRight(S: string, WidthChars: number): string
// static StartsWith(Src: string, Prefix: string): boolean
// static Trim(Src: string): string
// static Repl(Src: string, Match: string, With: string, bCaseSensitive: boolean): string
// static Asc(S: string): number
// static Chr(I: number): string
// static Locs(S: string): string
// static Caps(S: string): string
// static Right(S: string, I: number): string
// static Left(S: string, I: number): string
// static Mid(S: string, I: number, J: number): string
// static InStr(S: string, T: string, bSearchFromRight: boolean, bIgnoreCase: boolean, StartPos: number): number
// static Len(S: string): number
// static SubtractEqual_StrStr(A: string, B: string): string
// static AtEqual_StrStr(A: string, B: string): string
// static ConcatEqual_StrStr(A: string, B: string): string
// static ComplementEqual_StrStr(A: string, B: string): boolean
// static NotEqual_StrStr(A: string, B: string): boolean
// static EqualEqual_StrStr(A: string, B: string): boolean
// static GreaterEqual_StrStr(A: string, B: string): boolean
// static LessEqual_StrStr(A: string, B: string): boolean
// static Greater_StrStr(A: string, B: string): boolean
// static Less_StrStr(A: string, B: string): boolean
// static At_StrStr(A: string, B: string): string
// static Concat_StrStr(A: string, B: string): string
// static RotateRotator(Axis: FVector, Rot: FRotator, Direction: FRotator, Amount: number): FRotator
// static MakeQuat(X: number, Y: number, Z: number, W: number): FQuat
// static MakeRotator(Pitch: number, Yaw: number, Roll: number): FRotator
// static SClampRotAxis(DeltaTime: number, ViewAxis: number, out_DeltaViewAxis: number, MaxLimit: number, MinLimit: number, InterpolationSpeed: number): boolean
// static ClampRotAxisFromRange(Current: number, Min: number, Max: number): number
// static ClampRotAxisFromBase(Current: number, Center: number, MaxDelta: number): number
// static ClampRotAxis(ViewAxis: number, out_DeltaViewAxis: number, MaxLimit: number, MinLimit: number): void
// static FlattenRotatorOnAxis(AxisToRemove: FVector, RotToFlatten: FRotator, RotToFlattenTo: FRotator): FRotator
// static RSize(R: FRotator): number
// static RDiff(A: FRotator, B: FRotator): number
// static NormalizeRotAxis(Angle: number): number
// static RInterpTo(Current: FRotator, Target: FRotator, DeltaTime: number, InterpSpeed: number, bConstantInterpSpeed: boolean): FRotator
// static RTransform(R: FRotator, RBasis: FRotator): FRotator
// static RLerp(A: FRotator, B: FRotator, Alpha: number, bShortestPath: boolean): FRotator
// static Normalize(Rot: FRotator): FRotator
// static OrthoRotation(X: FVector, Y: FVector, Z: FVector): FRotator
// static RotRand(bRoll: boolean): FRotator
// static GetRotatorAxis(A: FRotator, Axis: number): FVector
// static GetUnAxes(A: FRotator, X: FVector, Y: FVector, Z: FVector): void
// static GetAxes(A: FRotator, X: FVector, Y: FVector, Z: FVector): void
// static ClockwiseFrom_IntInt(A: number, B: number): boolean
// static SubtractEqual_RotatorRotator(A: FRotator, B: FRotator): FRotator
// static AddEqual_RotatorRotator(A: FRotator, B: FRotator): FRotator
// static Subtract_RotatorRotator(A: FRotator, B: FRotator): FRotator
// static Add_RotatorRotator(A: FRotator, B: FRotator): FRotator
// static DivideEqual_RotatorFloat(A: FRotator, B: number): FRotator
// static MultiplyEqual_RotatorFloat(A: FRotator, B: number): FRotator
// static Divide_RotatorFloat(A: FRotator, B: number): FRotator
// static Multiply_FloatRotator(A: number, B: FRotator): FRotator
// static Multiply_RotatorFloat(A: FRotator, B: number): FRotator
// static NotEqual_RotatorRotator(A: FRotator, B: FRotator): boolean
// static EqualEqual_RotatorRotator(A: FRotator, B: FRotator): boolean
// static GetRadiansBetweenVectors(V0: FVector, v1: FVector): number
// static VClamp(A: FVector, Min: FVector, Max: FVector): FVector
// static vect3d(X: number, Y: number, Z: number): FVector
// InCylinder(Origin: FVector, Dir: FRotator, Width: number, A: FVector, bIgnoreZ: boolean): boolean
// static NoZDot(A: FVector, B: FVector): number
// static ClampLength(V: FVector, MaxLength: number): FVector
// static VInterpConstantTo(Current: FVector, Target: FVector, DeltaTime: number, InterpSpeed: number): FVector
// static VInterpTo(Current: FVector, Target: FVector, DeltaTime: number, InterpSpeed: number): FVector
// Construct(): void
// static ProjectOnToPlane(InVector: FVector, InNormal: FVector, OverBounce: number): FVector
// static IsZero(A: FVector): boolean
// static ProjectOnTo(X: FVector, Y: FVector): FVector
// static MirrorVectorByNormal(InVect: FVector, InNormal: FVector): FVector
// static VRandCone2(Dir: FVector, HorizontalConeHalfAngleRadians: number, VerticalConeHalfAngleRadians: number): FVector
// static VRandCone(Dir: FVector, ConeHalfAngleRadians: number): FVector
// static VRand(): FVector
// static VLerp(A: FVector, B: FVector, Alpha: number): FVector
// static Normal2D(A: FVector): FVector
// static Normal(A: FVector): FVector
// static VSizeSq2D(A: FVector): number
// static VSizeSq(A: FVector): number
// static VSize2D(A: FVector): number
// static VSize(A: FVector): number
// static SubtractEqual_VectorVector(A: FVector, B: FVector): FVector
// static AddEqual_VectorVector(A: FVector, B: FVector): FVector
// static DivideEqual_VectorFloat(A: FVector, B: number): FVector
// static MultiplyEqual_VectorVector(A: FVector, B: FVector): FVector
// static MultiplyEqual_VectorFloat(A: FVector, B: number): FVector
// static Cross_VectorVector(A: FVector, B: FVector): FVector
// static Dot_VectorVector(A: FVector, B: FVector): number
// static NotEqual_VectorVector(A: FVector, B: FVector): boolean
// static EqualEqual_VectorVector(A: FVector, B: FVector): boolean
// static GreaterGreater_VectorRotator(A: FVector, B: FRotator): FVector
// static LessLess_VectorRotator(A: FVector, B: FRotator): FVector
// static Subtract_VectorVector(A: FVector, B: FVector): FVector
// static Add_VectorVector(A: FVector, B: FVector): FVector
// static Divide_VectorFloat(A: FVector, B: number): FVector
// static Multiply_VectorVector(A: FVector, B: FVector): FVector
// static Multiply_FloatVector(A: number, B: FVector): FVector
// static Multiply_VectorFloat(A: FVector, B: number): FVector
// static Subtract_PreVector(A: FVector): FVector
// static FInterpConstantTo(Current: number, Target: number, DeltaTime: number, InterpSpeed: number): number
// static FInterpTo(Current: number, Target: number, DeltaTime: number, InterpSpeed: number): number
// static FPctByRange(Value: number, InMin: number, InMax: number): number
// static RandSign(Value: number): number
// static CalculateGravityPosition(Location: FVector, Velocity: FVector, Gravity: number, Time: number, GravityDirection: FVector): FVector
// static RandRange(InMin: number, InMax: number): number
// static FInterpEaseInOut(A: number, B: number, Alpha: number, Exp: number): number
// static FInterpEaseOut(A: number, B: number, Alpha: number, Exp: number): number
// static FInterpEaseIn(A: number, B: number, Alpha: number, Exp: number): number
// static FCubicInterp(P0: number, T0: number, P1: number, T1: number, A: number): number
// static FloorLog2(Value: number): number
// static FCeil(A: number): number
// static FFloor(A: number): number
// static Round(A: number): number
// static Lerp(A: number, B: number, Alpha: number): number
// static FClamp(V: number, A: number, B: number): number
// static FMax(A: number, B: number): number
// static FMin(A: number, B: number): number
// static FRand(): number
// static Square(A: number): number
// static Sqrt(A: number): number
// static Loge(A: number): number
// static Exp(A: number): number
// static Atan2(A: number, B: number): number
// static Atan(A: number): number
// static Tan(A: number): number
// static Acos(A: number): number
// static Cos(A: number): number
// static Asin(A: number): number
// static Sin(A: number): number
// static Abs(A: number): number
// static SubtractEqual_FloatFloat(A: number, B: number): number
// static AddEqual_FloatFloat(A: number, B: number): number
// static DivideEqual_FloatFloat(A: number, B: number): number
// static MultiplyEqual_FloatFloat(A: number, B: number): number
// static NotEqual_FloatFloat(A: number, B: number): boolean
// static ComplementEqual_FloatFloat(A: number, B: number): boolean
// static EqualEqual_FloatFloat(A: number, B: number): boolean
// static GreaterEqual_FloatFloat(A: number, B: number): boolean
// static LessEqual_FloatFloat(A: number, B: number): boolean
// static Greater_FloatFloat(A: number, B: number): boolean
// static Less_FloatFloat(A: number, B: number): boolean
// static Subtract_FloatFloat(A: number, B: number): number
// static Add_FloatFloat(A: number, B: number): number
// static Percent_FloatFloat(A: number, B: number): number
// static Divide_FloatFloat(A: number, B: number): number
// static Multiply_FloatFloat(A: number, B: number): number
// static MultiplyMultiply_FloatFloat(Base: number, Exp: number): number
// static Subtract_PreFloat(A: number): number
// static ToHex(A: number): string
// static Clamp(V: number, A: number, B: number): number
// static Max(A: number, B: number): number
// static Min(A: number, B: number): number
// static Rand(Max: number): number
// static FromHexColor(Hex: string): FColor
// static FromHex(Hex: string): number
// static SQWordMin(): void
// static SQWordMax(): void
// static SubtractEqual_SQWordSQWord(): void
// static AddEqual_SQWordSQWord(): void
// static NotEqual_SQWordSQWord(): boolean
// static EqualEqual_SQWordSQWord(): boolean
// static GreaterEqual_SQWordSQWord(): boolean
// static LessEqual_SQWordSQWord(): boolean
// static Greater_SQWordSQWord(): boolean
// static Less_SQWordSQWord(): boolean
// static Subtract_SQWordSQWord(): void
// static Add_SQWordSQWord(): void
// static Divide_SQWordSQWord(): void
// static Multiply_SQWordSQWord(): void
// static QMin(A: bigint, B: bigint): bigint
// static QMax(A: bigint, B: bigint): bigint
// static QSubtractNoUnderflow(A: bigint, B: bigint): bigint
// static NotEqual_QWordInt(A: bigint, B: number): boolean
// static EqualEqual_QWordInt(A: bigint, B: number): boolean
// static SubtractEqual_QWordQWord(A: bigint, B: bigint): bigint
// static AddEqual_QWordQWord(A: bigint, B: bigint): bigint
// static NotEqual_QWordQWord(A: bigint, B: bigint): boolean
// static EqualEqual_QWordQWord(A: bigint, B: bigint): boolean
// static GreaterEqual_QWordQWord(A: bigint, B: bigint): boolean
// static LessEqual_QWordQWord(A: bigint, B: bigint): boolean
// static Greater_QWordQWord(A: bigint, B: bigint): boolean
// static Less_QWordQWord(A: bigint, B: bigint): boolean
// static Subtract_QWordQWord(A: bigint, B: bigint): number
// static Add_QWordQWord(A: bigint, B: bigint): bigint
// static Divide_QWordQWord(A: bigint, B: bigint): bigint
// static Multiply_QWordQWord(A: bigint, B: bigint): bigint
// static SubtractSubtract_Int(A: number): number
// static AddAdd_Int(A: number): number
// static SubtractSubtract_PreInt(A: number): number
// static AddAdd_PreInt(A: number): number
// static SubtractEqual_IntInt(A: number, B: number): number
// static AddEqual_IntInt(A: number, B: number): number
// static DivideEqual_IntFloat(A: number, B: number): number
// static MultiplyEqual_IntFloat(A: number, B: number): number
// static Or_IntInt(A: number, B: number): number
// static Xor_IntInt(A: number, B: number): number
// static And_IntInt(A: number, B: number): number
// static NotEqual_IntInt(A: number, B: number): boolean
// static EqualEqual_IntInt(A: number, B: number): boolean
// static GreaterEqual_IntInt(A: number, B: number): boolean
// static LessEqual_IntInt(A: number, B: number): boolean
// static Greater_IntInt(A: number, B: number): boolean
// static Less_IntInt(A: number, B: number): boolean
// static GreaterGreaterGreater_IntInt(A: number, B: number): number
// static GreaterGreater_IntInt(A: number, B: number): number
// static LessLess_IntInt(A: number, B: number): number
// static Subtract_IntInt(A: number, B: number): number
// static Add_IntInt(A: number, B: number): number
// static Percent_IntInt(A: number, B: number): number
// static Divide_IntInt(A: number, B: number): number
// static Multiply_IntInt(A: number, B: number): number
// static Subtract_PreInt(A: number): number
// static Complement_PreInt(A: number): number
// static SubtractSubtract_Byte(A: number): number
// static AddAdd_Byte(A: number): number
// static SubtractSubtract_PreByte(A: number): number
// static AddAdd_PreByte(A: number): number
// static SubtractEqual_ByteByte(A: number, B: number): number
// static AddEqual_ByteByte(A: number, B: number): number
// static DivideEqual_ByteByte(A: number, B: number): number
// static MultiplyEqual_ByteFloat(A: number, B: number): number
// static MultiplyEqual_ByteByte(A: number, B: number): number
// static OrOr_BoolBool(A: boolean, B: boolean): boolean
// static XorXor_BoolBool(A: boolean, B: boolean): boolean
// static AndAnd_BoolBool(A: boolean, B: boolean): boolean
// static NotEqual_BoolBool(A: boolean, B: boolean): boolean
// static EqualEqual_BoolBool(A: boolean, B: boolean): boolean
// static Not_PreBool(A: boolean): boolean

/**
 * Class Core.__AsyncTask__All_0x1
 * Size: 0x0070
 * Extends: UObject
 */
export type U__AsyncTask__All_0x1 = UObject & {
  DependentsCount: number; // 0x0060 (0x0004) [int32]
  Parent: UAsyncTask; // 0x0068 (0x0008) [UAsyncTask*]
};

// __AsyncTask__All_0x1 Functions
// __AsyncTask__All_0x1(): void

/**
 * Class Core._LoggingDoc
 * Size: 0x0060
 * Extends: UObject
 */
export type U_LoggingDoc = UObject & {};

// _LoggingDoc Functions
// static TestSpecialLogging(): void

/**
 * Class Core._Types_Core
 * Size: 0x0060
 * Extends: UObject
 */
export type U_Types_Core = UObject & {};

/**
 * Class Core._Types_Generated
 * Size: 0x0060
 * Extends: UObject
 */
export type U_Types_Generated = UObject & {};

/**
 * Class Core.ErrorList
 * Size: 0x0080
 * Extends: UObject
 */
export type UErrorList = UObject & {
  LocalizationPackage: string; // 0x0060 (0x0010) [FString]
  LocalizationSection: string; // 0x0070 (0x0010) [FString]
};

// ErrorList Functions
// static GetErrorType(Error: FName): UErrorType

/**
 * Class Core.ArrayErrors
 * Size: 0x0090
 * Extends: UErrorList
 */
export type UArrayErrors = UErrorList & {
  Remove_NegativeNumberOfElements: UErrorType; // 0x0080 (0x0008) [UErrorType*]
  Remove_OutOfBounds: UErrorType; // 0x0088 (0x0008) [UErrorType*]
};

/**
 * Class Core.ArrayFuncs
 * Size: 0x0060
 * Extends: UObject
 */
export type UArrayFuncs = UObject & {};

// ArrayFuncs Functions
// static GetRandomElement(): void
// static ShuffleArray(): void

/**
 * Class Core.Field
 * Size: 0x0070
 * Extends: UObject
 */
export type UField = UObject & {};

/**
 * Class Core.Property
 * Size: 0x00C8
 * Extends: UField
 */
export type UProperty = UField & {};

/**
 * Class Core.ArrayProperty
 * Size: 0x00D0
 * Extends: UProperty
 */
export type UArrayProperty = UProperty & {};

/**
 * Class Core.AsyncTask
 * Size: 0x00D0
 * Extends: UObject
 */
export type UAsyncTask = UObject & {
  bComplete: boolean; // 0x0060 (0x0004) [bool : 0x1]
  bDisposed: boolean; // 0x0060 (0x0004) [bool : 0x2]
  Error: UError; // 0x0068 (0x0008) [UError*]
  __EventAsyncTaskSuccess__Delegate: FScriptDelegate; // 0x0070 (0x0018) [FScriptDelegate]
  __EventAsyncTaskFail__Delegate: FScriptDelegate; // 0x0088 (0x0018) [FScriptDelegate]
  __EventAsyncTaskComplete__Delegate: FScriptDelegate; // 0x00a0 (0x0018) [FScriptDelegate]
  __EventDisposed__Delegate: FScriptDelegate; // 0x00b8 (0x0018) [FScriptDelegate]
};

// AsyncTask Functions
// QueCallbacks(): void
// static CreateError(InError: UError): UAsyncTask
// static CreateSuccess(): UAsyncTask
// static Create(): UAsyncTask
// Watch(Other: UAsyncTask): UAsyncTask
// static All(Dependents: UAsyncTask[]): UAsyncTask
// DependOn(Other: UAsyncTask): UAsyncTask
// NotifyOnDispose(Callback: FScriptDelegate): UAsyncTask
// ClearCallbacks(): void
// Dispose(): void
// SetComplete(InError: UError): void
// SetError(InError: UError): void
// NotifyOnComplete(Callback: FScriptDelegate): UAsyncTask
// NotifyOnFail(Callback: FScriptDelegate): UAsyncTask
// NotifyOnSuccess(Callback: FScriptDelegate): UAsyncTask
// EventDisposed(): void
// EventAsyncTaskComplete(TaskError: UError): void
// EventAsyncTaskFail(TaskError: UError): void
// EventAsyncTaskSuccess(): void

/**
 * Class Core.AsyncResult
 * Size: 0x00D0
 * Extends: UAsyncTask
 */
export type UAsyncResult = UAsyncTask & {};

/**
 * Class Core.AutomationTest
 * Size: 0x00A0
 * Extends: UObject
 */
export type UAutomationTest = UObject & {
  MaterialsCompiled: string[]; // 0x0060 (0x0010) [TArray<FString>]
  MaterialsFailedCompile: string[]; // 0x0070 (0x0010) [TArray<FString>]
  AsyncPreloadPackagesMissing: string[]; // 0x0080 (0x0010) [TArray<FString>]
  ScriptWarnings: FScriptWarning[]; // 0x0090 (0x0010) [TArray<FScriptWarning>]
};

/**
 * Class Core.Base64
 * Size: 0x0060
 * Extends: UObject
 */
export type UBase64 = UObject & {};

// Base64 Functions
// static PadAndDecodeString(Input: string): number[]
// static DecodeStringInline(Input: string, Output: number[]): void
// static DecodeString(Input: string): number[]
// static DecodeInline(Input: number[], Output: number[]): void
// static Decode(Input: number[]): number[]
// static EncodeStringInline(Input: number[], Output: string): void
// static EncodeString(Input: number[]): string
// static EncodeInline(Input: number[], Output: number[]): void
// static Encode(Input: number[]): number[]

/**
 * Class Core.BoolProperty
 * Size: 0x00D0
 * Extends: UProperty
 */
export type UBoolProperty = UProperty & {};

/**
 * Class Core.Breadcrumbs
 * Size: 0x0068
 * Extends: UObject
 */
export type UBreadcrumbs = UObject & {
  BreadcrumbInstance: FPointer; // 0x0060 (0x0008) [FPointer]
};

// Breadcrumbs Functions
// BreadcrumbFloat(Category: string, Value: number): void
// BreadcrumbString(Category: string, Value: string): void

/**
 * Class Core.ByteProperty
 * Size: 0x00D0
 * Extends: UProperty
 */
export type UByteProperty = UProperty & {};

/**
 * Class Core.Struct
 * Size: 0x0130
 * Extends: UField
 */
export type UStruct = UField & {};

/**
 * Class Core.State
 * Size: 0x0190
 * Extends: UStruct
 */
export type UState = UStruct & {};

/**
 * Class Core.Class
 * Size: 0x03B8
 * Extends: UState
 */
export type UClass = UState & {};

/**
 * Class Core.ObjectProperty
 * Size: 0x00D8
 * Extends: UProperty
 */
export type UObjectProperty = UProperty & {};

/**
 * Class Core.ClassProperty
 * Size: 0x00E0
 * Extends: UObjectProperty
 */
export type UClassProperty = UObjectProperty & {};

/**
 * Class Core.ClassTuple_ORS
 * Size: 0x00C8
 * Extends: UObject
 */
export type UClassTuple_ORS = UObject & {};

/**
 * Class Core.ClassTupleCollection_ORS
 * Size: 0x00C0
 * Extends: UObject
 */
export type UClassTupleCollection_ORS = UObject & {};

/**
 * Class Core.Commandlet
 * Size: 0x00B4
 * Extends: UObject
 */
export type UCommandlet = UObject & {
  HelpDescription: string; // 0x0060 (0x0010) [FString]
  HelpUsage: string; // 0x0070 (0x0010) [FString]
  HelpWebLink: string; // 0x0080 (0x0010) [FString]
  HelpParamNames: string[]; // 0x0090 (0x0010) [TArray<FString>]
  HelpParamDescriptions: string[]; // 0x00a0 (0x0010) [TArray<FString>]
  IsServer: boolean; // 0x00b0 (0x0004) [bool : 0x1]
  IsClient: boolean; // 0x00b0 (0x0004) [bool : 0x2]
  IsEditor: boolean; // 0x00b0 (0x0004) [bool : 0x4]
  LogToConsole: boolean; // 0x00b0 (0x0004) [bool : 0x8]
  ShowErrorCount: boolean; // 0x00b0 (0x0004) [bool : 0x10]
};

// Commandlet Functions
// Main(Params: string): number

/**
 * Class Core.Component
 * Size: 0x0070
 * Extends: UObject
 */
export type UComponent = UObject & {
  TemplateOwnerClass: UObject; // 0x0060 (0x0008) [UObject*]
  TemplateName: FName; // 0x0068 (0x0008) [FName]
};

/**
 * Class Core.ComponentProperty
 * Size: 0x00D8
 * Extends: UObjectProperty
 */
export type UComponentProperty = UObjectProperty & {};

/**
 * Class Core.Compression
 * Size: 0x0060
 * Extends: UObject
 */
export type UCompression = UObject & {};

// Compression Functions
// static ZLibCompress(Uncompressed: number[], OutCompressed: number[]): boolean

/**
 * Class Core.Config_ORS
 * Size: 0x00C0
 * Extends: UObject
 */
export type UConfig_ORS = UObject & {};

/**
 * Class Core.Const
 * Size: 0x0080
 * Extends: UField
 */
export type UConst = UField & {};

/**
 * Class Core.DebugDrawer
 * Size: 0x00C0
 * Extends: UObject
 */
export type UDebugDrawer = UObject & {
  DefaultTextColor: FColor; // 0x0060 (0x0004) [FColor]
  bSilent: boolean; // 0x0064 (0x0004) [bool : 0x1]
  bPrintActorsInline: boolean; // 0x0064 (0x0004) [bool : 0x2]
  Indentation: number; // 0x0068 (0x0004) [int32]
  IndentationString: string; // 0x0070 (0x0010) [FString]
  PrintedObjects: UObject[]; // 0x0080 (0x0010) [TArray<UObject*>]
  QueuedObjects: UObject[]; // 0x0090 (0x0010) [TArray<UObject*>]
  PrintObjectCount: number; // 0x00a0 (0x0004) [int32]
  __LogFunc__Delegate: FScriptDelegate; // 0x00a8 (0x0018) [FScriptDelegate]
};

// DebugDrawer Functions
// Reset(): void
// PrintText(Text: string, InColor: FColor): void
// PrintArrayProperty(PropertyName: string, Index: number, Value: string): void
// PrintProperty(PropertyName: string, Value: string): void
// EndSection(): void
// StartSection(): void
// PrintObject(Title: string, ForObj: UObject): void
// PrintSeperater(): void
// DebugArrayObject(Title: string, Index: number, ForObj: UObject): void
// DebugObject(Title: string, ForObj: UObject): void
// ShouldDisplayDebug(Category: FName): boolean
// LogFunc(Str: string): void

/**
 * Class Core.DelegateProperty
 * Size: 0x00D8
 * Extends: UProperty
 */
export type UDelegateProperty = UProperty & {};

/**
 * Class Core.DelegateTracker
 * Size: 0x0088
 * Extends: UObject
 */
export type UDelegateTracker = UObject & {
  AsyncDelegates: FAsyncDelegateInfo[]; // 0x0060 (0x0010) [TArray<FAsyncDelegateInfo>]
  __PlaceholderDelegate__Delegate: FScriptDelegate; // 0x0070 (0x0018) [FScriptDelegate]
};

// DelegateTracker Functions
// RemoveDelegate(CallbackId: number): FScriptDelegate
// AddDelegate(Callback: FScriptDelegate): number
// PlaceholderDelegate(): void

/**
 * Class Core.DistributionFloat
 * Size: 0x007C
 * Extends: UComponent
 */
export type UDistributionFloat = UComponent & {
  VfTable_FCurveEdInterface: FPointer; // 0x0070 (0x0008) [FPointer]
  bCanBeBaked: boolean; // 0x0078 (0x0004) [bool : 0x1]
  bIsDirty: boolean; // 0x0078 (0x0004) [bool : 0x2]
};

// DistributionFloat Functions
// GetFloatValue(F: number): number

/**
 * Class Core.DistributionVector
 * Size: 0x007C
 * Extends: UComponent
 */
export type UDistributionVector = UComponent & {
  VfTable_FCurveEdInterface: FPointer; // 0x0070 (0x0008) [FPointer]
  bCanBeBaked: boolean; // 0x0078 (0x0004) [bool : 0x1]
  bIsDirty: boolean; // 0x0078 (0x0004) [bool : 0x2]
};

// DistributionVector Functions
// GetVectorValue(F: number, LastExtreme: number): FVector

/**
 * Class Core.Enum
 * Size: 0x0080
 * Extends: UField
 */
export type UEnum = UField & {};

/**
 * Class Core.Error
 * Size: 0x0084
 * Extends: UObject
 */
export type UError = UObject & {
  Type: UErrorType; // 0x0060 (0x0008) [UErrorType*]
  Message: string; // 0x0068 (0x0010) [FString]
  Code: number; // 0x0078 (0x0004) [int32]
  RetryKey: FName; // 0x007c (0x0008) [FName]
};

// Error Functions
// GetDebugMessage(): string
// GetLocalizedMessage(): string

/**
 * Class Core.ErrorType
 * Size: 0x0070
 * Extends: UObject
 */
export type UErrorType = UObject & {
  LocalizationKey: string; // 0x0060 (0x0010) [FString]
};

// ErrorType Functions
// CreateError(InErrorMessage: string, InErrorCode: number): UError
// GetLocalizedMessage(): string

/**
 * Class Core.Exporter
 * Size: 0x0098
 * Extends: UObject
 */
export type UExporter = UObject & {
  FormatExtension: string[]; // 0x0068 (0x0010) [TArray<FString>]
  FormatDescription: string[]; // 0x0078 (0x0010) [TArray<FString>]
};

/**
 * Class Core.Factory
 * Size: 0x00B8
 * Extends: UObject
 */
export type UFactory = UObject & {
  Category: string; // 0x0060 (0x0010) [FString]
  SupportedClass: UObject; // 0x0070 (0x0008) [UObject*]
  ContextClass: UObject; // 0x0078 (0x0008) [UObject*]
  Description: string; // 0x0080 (0x0010) [FString]
  Formats: string[]; // 0x0090 (0x0010) [TArray<FString>]
  bCreateNew: boolean; // 0x00a0 (0x0004) [bool : 0x1]
  bEditAfterNew: boolean; // 0x00a0 (0x0004) [bool : 0x2]
  bEditorImport: boolean; // 0x00a0 (0x0004) [bool : 0x4]
  bText: boolean; // 0x00a0 (0x0004) [bool : 0x8]
  bAssetNameMatchesPackageName: boolean; // 0x00a0 (0x0004) [bool : 0x10]
  AutoPriority: number; // 0x00a4 (0x0004) [int32]
  ValidGameNames: string[]; // 0x00a8 (0x0010) [TArray<FString>]
};

/**
 * Class Core.FeatureSystem
 * Size: 0x0080
 * Extends: UObject
 */
export type UFeatureSystem = UObject & {
  Prime: boolean; // 0x0068 (0x0004) [bool : 0x2]
  Matchmaking: boolean; // 0x0068 (0x0004) [bool : 0x8]
  PrivateMatch: boolean; // 0x0068 (0x0004) [bool : 0x10]
  SplitscreenMatch: boolean; // 0x0068 (0x0004) [bool : 0x20]
  SplitscreenJoin: boolean; // 0x0068 (0x0004) [bool : 0x40]
  SeasonMode: boolean; // 0x0068 (0x0004) [bool : 0x80]
  Tutorial: boolean; // 0x0068 (0x0004) [bool : 0x100]
  Garage: boolean; // 0x0068 (0x0004) [bool : 0x200]
  Options: boolean; // 0x0068 (0x0004) [bool : 0x400]
  ReplaySaves: boolean; // 0x0068 (0x0004) [bool : 0x800]
  MainMenu: boolean; // 0x0068 (0x0004) [bool : 0x1000]
  MidgameMenu: boolean; // 0x0068 (0x0004) [bool : 0x2000]
  Party: boolean; // 0x0068 (0x0004) [bool : 0x4000]
  PsyNetParty: boolean; // 0x0068 (0x0004) [bool : 0x8000]
  Achievements: boolean; // 0x0068 (0x0004) [bool : 0x10000]
  Stats: boolean; // 0x0068 (0x0004) [bool : 0x20000]
  Leaderboards: boolean; // 0x0068 (0x0004) [bool : 0x40000]
  XP: boolean; // 0x0068 (0x0004) [bool : 0x80000]
  Chat: boolean; // 0x0068 (0x0004) [bool : 0x100000]
  TrainingDifficulties: boolean; // 0x0068 (0x0004) [bool : 0x200000]
  Spectator: boolean; // 0x0068 (0x0004) [bool : 0x400000]
  CrossPlatformPrivateMatch: boolean; // 0x0068 (0x0004) [bool : 0x800000]
  Lan: boolean; // 0x0068 (0x0004) [bool : 0x1000000]
  PlayerReporting: boolean; // 0x0068 (0x0004) [bool : 0x2000000]
  OnlineServices: boolean; // 0x0068 (0x0004) [bool : 0x40000000]
  RemoveCrossPlatformProducts: boolean; // 0x0068 (0x0004) [bool : 0x80000000]
  ProductValidation: boolean; // 0x006c (0x0004) [bool : 0x1]
  MapPrefs: boolean; // 0x006c (0x0004) [bool : 0x2]
  PreMatchLobby: boolean; // 0x006c (0x0004) [bool : 0x8]
  Challenges: boolean; // 0x006c (0x0004) [bool : 0x10]
  AntiAddiction: boolean; // 0x006c (0x0004) [bool : 0x20]
  TrainingEditor: boolean; // 0x006c (0x0004) [bool : 0x40]
  VoiceChat: boolean; // 0x006c (0x0004) [bool : 0x80]
  SplitScreen: boolean; // 0x006c (0x0004) [bool : 0x100]
  Clubs: boolean; // 0x006c (0x0004) [bool : 0x200]
  FilterContent: boolean; // 0x006c (0x0004) [bool : 0x400]
  EncryptContent: boolean; // 0x006c (0x0004) [bool : 0x800]
  EsportsCamera: boolean; // 0x006c (0x0004) [bool : 0x4000]
  OnlineXP: boolean; // 0x006c (0x0004) [bool : 0x8000]
  ClanforgeReservation: boolean; // 0x006c (0x0004) [bool : 0x20000]
  UserSettingObserver: boolean; // 0x006c (0x0004) [bool : 0x40000]
  Metrics: boolean; // 0x006c (0x0004) [bool : 0x80000]
  EOSMetrics: boolean; // 0x006c (0x0004) [bool : 0x100000]
  MusicPlaylistSelection: boolean; // 0x006c (0x0004) [bool : 0x200000]
  SpecialEvents: boolean; // 0x006c (0x0004) [bool : 0x400000]
  PlayerBannerCustomization: boolean; // 0x006c (0x0004) [bool : 0x800000]
  SecureUDP: boolean; // 0x006c (0x0004) [bool : 0x1000000]
  PsyNet: boolean; // 0x006c (0x0004) [bool : 0x2000000]
  OnlinePlayerStorage: boolean; // 0x006c (0x0004) [bool : 0x4000000]
  LocalSaveData: boolean; // 0x006c (0x0004) [bool : 0x8000000]
  CrowdV2: boolean; // 0x006c (0x0004) [bool : 0x10000000]
  ChatBan: boolean; // 0x006c (0x0004) [bool : 0x20000000]
  BacktraceCrashDumps: boolean; // 0x006c (0x0004) [bool : 0x40000000]
  SpotifyButton: boolean; // 0x006c (0x0004) [bool : 0x80000000]
  SeasonRewards: boolean; // 0x0070 (0x0004) [bool : 0x1]
  FaceIt: boolean; // 0x0070 (0x0004) [bool : 0x2]
  KnockOut: boolean; // 0x0070 (0x0004) [bool : 0x4]
  OnlinePlayerTitles: boolean; // 0x0070 (0x0004) [bool : 0x8]
  RestrictByRegion: boolean; // 0x0070 (0x0004) [bool : 0x10]
  FirstTimeExperience: boolean; // 0x0070 (0x0004) [bool : 0x40]
  RLBot: boolean; // 0x0070 (0x0004) [bool : 0x80]
  UserBugReport: boolean; // 0x0070 (0x0004) [bool : 0x100]
  SteamInput: boolean; // 0x0070 (0x0004) [bool : 0x200]
  ReplayFXControls: boolean; // 0x0070 (0x0004) [bool : 0x4000]
  ESportsShop: boolean; // 0x0070 (0x0004) [bool : 0x8000]
  MatchHistory: boolean; // 0x0070 (0x0004) [bool : 0x10000]
  DynamicRangeAudioSettings: boolean; // 0x0070 (0x0004) [bool : 0x80000]
  QuickPlay: boolean; // 0x0070 (0x0004) [bool : 0x100000]
  NewsPanelV2: boolean; // 0x0070 (0x0004) [bool : 0x200000]
  Blueprints: boolean; // 0x0070 (0x0004) [bool : 0x400000]
  RocketBucks: boolean; // 0x0070 (0x0004) [bool : 0x1000000]
  Tritip: boolean; // 0x0070 (0x0004) [bool : 0x4000000]
  DiscordRichPresence: boolean; // 0x0070 (0x0004) [bool : 0x10000000]
  SupportACreator: boolean; // 0x0070 (0x0004) [bool : 0x20000000]
  CinematicIntro: boolean; // 0x0070 (0x0004) [bool : 0x40000000]
  TinyCrowd: boolean; // 0x0070 (0x0004) [bool : 0x80000000]
  CrumbTrail: boolean; // 0x0074 (0x0004) [bool : 0x1]
  XPGatedPlaylists: boolean; // 0x0074 (0x0004) [bool : 0x4]
  TradeInV2: boolean; // 0x0074 (0x0004) [bool : 0x10]
  Football: boolean; // 0x0074 (0x0004) [bool : 0x20]
  RumbleSelection: boolean; // 0x0074 (0x0004) [bool : 0x40]
  UndersizedParty: boolean; // 0x0074 (0x0004) [bool : 0x80]
  StreamerSafeAudio: boolean; // 0x0074 (0x0004) [bool : 0x100]
  FreeplayCommands: boolean; // 0x0074 (0x0004) [bool : 0x200]
  Rumble_BM: boolean; // 0x0074 (0x0004) [bool : 0x400]
  PlayerReportingV2: boolean; // 0x0074 (0x0004) [bool : 0x800]
  EOSVoice: boolean; // 0x0074 (0x0004) [bool : 0x2000]
  QuickPostMatchRequeue: boolean; // 0x0074 (0x0004) [bool : 0x4000]
  TrainingNavigation: boolean; // 0x0074 (0x0004) [bool : 0x20000]
  TrainingManipulation: boolean; // 0x0074 (0x0004) [bool : 0x40000]
  FilterByColor: boolean; // 0x0074 (0x0004) [bool : 0x100000]
  Scoreboard: boolean; // 0x0074 (0x0004) [bool : 0x200000]
  DynamicMapEvents: boolean; // 0x0074 (0x0004) [bool : 0x400000]
  NameplateBoost: boolean; // 0x0074 (0x0004) [bool : 0x1000000]
  EOSGameClips: boolean; // 0x0074 (0x0004) [bool : 0x2000000]
  DynamicLogos: boolean; // 0x0074 (0x0004) [bool : 0x4000000]
  XETagging: boolean; // 0x0074 (0x0004) [bool : 0x8000000]
  PlayMenuV4: boolean; // 0x0074 (0x0004) [bool : 0x10000000]
  QuickChatTimeStamp: boolean; // 0x0074 (0x0004) [bool : 0x20000000]
  SoccarPong: boolean; // 0x0074 (0x0004) [bool : 0x40000000]
  OnlineFreeplay: boolean; // 0x0074 (0x0004) [bool : 0x80000000]
  MatchmakingSubRegion: boolean; // 0x0078 (0x0004) [bool : 0x2]
  CrossbarSFX: boolean; // 0x0078 (0x0004) [bool : 0x4]
  RugbyIteration: boolean; // 0x0078 (0x0004) [bool : 0x8]
  ChallengesV2: boolean; // 0x0078 (0x0004) [bool : 0x20]
  PossessionExpanded: boolean; // 0x0078 (0x0004) [bool : 0x40]
  TargetFind: boolean; // 0x0078 (0x0004) [bool : 0x80]
  KeepUp: boolean; // 0x0078 (0x0004) [bool : 0x200]
  RocketPassUpgrades: boolean; // 0x0078 (0x0004) [bool : 0x800]
  PentathlonTournaments: boolean; // 0x0078 (0x0004) [bool : 0x1000]
  DemolishUpdates: boolean; // 0x0078 (0x0004) [bool : 0x2000]
  ViralItem: boolean; // 0x0078 (0x0004) [bool : 0x4000]
  ThankYouMessage: boolean; // 0x0078 (0x0004) [bool : 0x8000]
  AttackerDemoFX: boolean; // 0x0078 (0x0004) [bool : 0x10000]
  NewDriverChallengesV2: boolean; // 0x0078 (0x0004) [bool : 0x20000]
  TextModeration: boolean; // 0x0078 (0x0004) [bool : 0x100000]
  FilterToggle: boolean; // 0x0078 (0x0004) [bool : 0x200000]
  DdosPrevention: boolean; // 0x0078 (0x0004) [bool : 0x400000]
  OunceEnhancements: boolean; // 0x0078 (0x0004) [bool : 0x800000]
  FastFreeplay: boolean; // 0x0078 (0x0004) [bool : 0x1000000]
  MatchAdminMutator: boolean; // 0x0078 (0x0004) [bool : 0x2000000]
  Thistle: boolean; // 0x0078 (0x0004) [bool : 0x4000000]
  DemoFXMutator: boolean; // 0x0078 (0x0004) [bool : 0x8000000]
  OffProdHandling: boolean; // 0x0078 (0x0004) [bool : 0x10000000]
  FlipResetIndicator: boolean; // 0x0078 (0x0004) [bool : 0x40000000]
  NewsOverhaul: boolean; // 0x0078 (0x0004) [bool : 0x80000000]
  QueueMenuChanges: boolean; // 0x007c (0x0004) [bool : 0x1]
  VisibleMMR: boolean; // 0x007c (0x0004) [bool : 0x2]
  EasyAntiCheat: boolean; // 0x007c (0x0004) [bool : 0x4]
  OverrideBoostSound: boolean; // 0x007c (0x0004) [bool : 0x8]
  SettingsExport: boolean; // 0x007c (0x0004) [bool : 0x10]
  RBActorStatGraphs: boolean; // 0x007c (0x0004) [bool : 0x80]
  DemoSpawnSelection: boolean; // 0x007c (0x0004) [bool : 0x100]
  FreeplayTeamColors: boolean; // 0x007c (0x0004) [bool : 0x200]
  HitboxVisualizer: boolean; // 0x007c (0x0004) [bool : 0x400]
  StatsAPI: boolean; // 0x007c (0x0004) [bool : 0x800]
  TrainingAdditions: boolean; // 0x007c (0x0004) [bool : 0x1000]
  ScorerGoalViewToggle: boolean; // 0x007c (0x0004) [bool : 0x2000]
  StreamerSafe: boolean; // 0x007c (0x0004) [bool : 0x4000]
  WorldCup: boolean; // 0x007c (0x0004) [bool : 0x8000]
  ImprovedPresence: boolean; // 0x007c (0x0004) [bool : 0x40000]
  AutoSkipGoalReplay: boolean; // 0x007c (0x0004) [bool : 0x80000]
};

/**
 * Class Core.FileSystem
 * Size: 0x0060
 * Extends: UObject
 */
export type UFileSystem = UObject & {};

// FileSystem Functions
// static IsCookedBuild(): boolean
// static CloseLogFile(): void
// static GetLogFileName(): string
// static DeleteDirectoryTree(Path: string): boolean
// static DeleteFile(Path: string): boolean
// static AppendStringToFile(Path: string, Text: string): boolean
// static SaveStringToFile(Path: string, Text: string): boolean
// static SaveBytesToFile(Path: string, Bytes: number[]): boolean
// static LoadFileToBytes(Path: string, OutBytes: number[], StartOffset: number, Length: number): boolean
// static LoadFileToString(Path: string, OutText: string): boolean
// static GetFileSize(Path: string): number
// static GetFileExtensionWithoutDot(Path: string): string
// static GetFileExtension(Path: string): string
// static GetFilePathWithoutExtension(Path: string): string
// static GetFileNameWithoutExtension(Path: string): string
// static GetFilename(Path: string): string
// static FindFiles(Path: string, OutFilenames: string[]): void

/**
 * Class Core.FloatProperty
 * Size: 0x00C8
 * Extends: UProperty
 */
export type UFloatProperty = UProperty & {};

/**
 * Class Core.Function
 * Size: 0x0160
 * Extends: UStruct
 */
export type UFunction = UStruct & {};

/**
 * Class Core.Global_ORS
 * Size: 0x0078
 * Extends: UObject
 */
export type UGlobal_ORS = UObject & {};

/**
 * Class Core.Group_ORS
 * Size: 0x0138
 * Extends: UScriptGroup_ORS
 */
export type UGroup_ORS = UScriptGroup_ORS & {};

/**
 * Class Core.HelpCommandlet
 * Size: 0x00B8
 * Extends: UCommandlet
 */
export type UHelpCommandlet = UCommandlet & {};

// HelpCommandlet Functions
// Main(Params: string): number

/**
 * Class Core.Interface
 * Size: 0x0060
 * Extends: UObject
 */
export type UInterface = UObject & {};

/**
 * Class Core.IDisposable
 * Size: 0x0060
 * Extends: UInterface
 */
export type UIDisposable = UInterface & {};

// IDisposable Functions
// Dispose(): void

/**
 * Class Core.Instance_ORS
 * Size: 0x0110
 * Extends: UObject
 */
export type UInstance_ORS = UObject & {};

/**
 * Class Core.InterfaceProperty
 * Size: 0x00D8
 * Extends: UProperty
 */
export type UInterfaceProperty = UProperty & {};

/**
 * Class Core.IntProperty
 * Size: 0x00C8
 * Extends: UProperty
 */
export type UIntProperty = UProperty & {};

/**
 * Class Core.Linker
 * Size: 0x01E8
 * Extends: UObject
 */
export type ULinker = UObject & {};

/**
 * Class Core.LinkerLoad
 * Size: 0x0810
 * Extends: ULinker
 */
export type ULinkerLoad = ULinker & {};

/**
 * Class Core.LinkerSave
 * Size: 0x02A8
 * Extends: ULinker
 */
export type ULinkerSave = ULinker & {};

/**
 * Class Core.MapProperty
 * Size: 0x00D8
 * Extends: UProperty
 */
export type UMapProperty = UProperty & {};

/**
 * Class Core.MetaData
 * Size: 0x00B0
 * Extends: UObject
 */
export type UMetaData = UObject & {};

/**
 * Class Core.NameProperty
 * Size: 0x00C8
 * Extends: UProperty
 */
export type UNameProperty = UProperty & {};

/**
 * Class Core.ObjectProvider
 * Size: 0x01E0
 * Extends: UComponent
 */
export type UObjectProvider = UComponent & {
  VfTable_FObjectDestructionSubscriber: FPointer; // 0x0070 (0x0008) [FPointer]
  MyObjects: UObject[]; // 0x0078 (0x0010) [TArray<UObject*>]
  ObjectRefs: FMap_Mirror; // 0x0088 (0x0050) [FMap_Mirror]
  TreeObjects: UObject[]; // 0x00d8 (0x0010) [TArray<UObject*>]
  SubscribedToAdds: FObjectProviderSubscription[]; // 0x00e8 (0x0010) [TArray<FObjectProviderSubscription>]
  SubscribedToRemoves: FObjectProviderSubscription[]; // 0x00f8 (0x0010) [TArray<FObjectProviderSubscription>]
  SubscribedToLists: FObjectProviderSubscription[]; // 0x0108 (0x0010) [TArray<FObjectProviderSubscription>]
  Injections: FArray_Mirror; // 0x0118 (0x0010) [FArray_Mirror]
  InterfaceInjections: FArray_Mirror; // 0x0128 (0x0010) [FArray_Mirror]
  PendingInjectionClasses: UObject[]; // 0x0138 (0x0010) [TArray<UObject*>]
  PendingCallbacks: FObjectProviderPendingCallback[]; // 0x0148 (0x0010) [TArray<FObjectProviderPendingCallback>]
  bTriggeringCallbacks: number; // 0x0158 (0x0001) [uint8]
  Parent: UObjectProvider; // 0x0160 (0x0008) [UObjectProvider*]
  Children: UObjectProvider[]; // 0x0168 (0x0010) [TArray<UObjectProvider*>]
  Proxies: UObjectProvider[]; // 0x0178 (0x0010) [TArray<UObjectProvider*>]
  PendingInjectionCallbacks: FObjectProviderPendingCallback[]; // 0x0188 (0x0010) [TArray<FObjectProviderPendingCallback>]
  __ObjectSubscriptionCallback__Delegate: FScriptDelegate; // 0x0198 (0x0018) [FScriptDelegate]
  __ObjectListSubscriptionCallback__Delegate: FScriptDelegate; // 0x01b0 (0x0018) [FScriptDelegate]
  __ObjectChangeCallback__Delegate: FScriptDelegate; // 0x01c8 (0x0018) [FScriptDelegate]
};

// ObjectProvider Functions
// SetParent(InParent: UObjectProvider): void
// RemoveProxy(InProxy: UObjectProvider): void
// AddProxy(InProxy: UObjectProvider): void
// SetSingleton(ObjClass: UObject, Replacement: UObject): void
// Replace(Existing: UObject, Replacement: UObject): void
// AddAndRemoveObjects(AddObjects: UObject[], RemoveObjects: UObject[]): void
// RemoveObjects(InObjects: UObject[]): void
// RemoveAllObjects(ObjectClass: UObject): void
// RemoveObject(Obj: UObject): void
// AddObjects(InObjects: UObject[]): void
// AddObject(Obj: UObject): void
// GetExactCount(ObjClass: UObject): number
// GetCount(ObjClass: UObject): number
// GetOrCreate(ObjClass: UObject): UObject
// GetExact(ObjClass: UObject): UObject
// GetUnsafe(ObjClass: UObject): UObject
// Get(ObjClass: UObject): UObject
// AllObjects(BaseClass: UObject, Obj: UObject, InterfaceClass: UInterface): void
// IsRegisteredForInjection(Subscriber: UObject): boolean
// InjectDelayed(Subscriber: UObject): void
// Inject(Subscriber: UObject): void
// UnsubscribeAll(Subscriber: UObject): void
// Unsubscribe(Callback: FScriptDelegate, Callback2: FScriptDelegate): void
// SubscribeList(BaseClass: UObject, Callback: FScriptDelegate): void
// SubscribeOnce(BaseClass: UObject, OnAdd: FScriptDelegate, OnRemove: FScriptDelegate): void
// Subscribe(BaseClass: UObject, OnAdd: FScriptDelegate, OnRemove: FScriptDelegate): void
// ObjectChangeCallback(): void
// ObjectListSubscriptionCallback(Provider: UObjectProvider): void
// ObjectSubscriptionCallback(Obj: UObject): void

/**
 * Class Core.ObjectRedirector
 * Size: 0x0068
 * Extends: UObject
 */
export type UObjectRedirector = UObject & {};

/**
 * Class Core.ObjectSerializer
 * Size: 0x0070
 * Extends: UObject
 */
export type UObjectSerializer = UObject & {};

/**
 * Class Core.ObjectUtil
 * Size: 0x0060
 * Extends: UObject
 */
export type UObjectUtil = UObject & {};

// ObjectUtil Functions
// static FindClass(ClassName: FName): UObject
// static ClearNaNValues(InObject: UObject): void
// static IdenticalDeep(Left: UObject, Right: UObject): boolean
// static Identical(Left: UObject, Right: UObject): boolean
// static InitProperties(InObject: UObject): void
// static AllCDOs(BaseClass: UObject, OutCDO: UObject, bIncludeAbstract: boolean): void
// static GetCDO(InClass: UObject): UObject

/**
 * Class Core.Package
 * Size: 0x0148
 * Extends: UObject
 */
export type UPackage = UObject & {};

/**
 * Class Core.PackageMap
 * Size: 0x0118
 * Extends: UObject
 */
export type UPackageMap = UObject & {};

/**
 * Class Core.PropertyChangeDispatcher
 * Size: 0x0070
 * Extends: UObject
 */
export type UPropertyChangeDispatcher = UObject & {};

/**
 * Class Core.QWordProperty
 * Size: 0x00C8
 * Extends: UProperty
 */
export type UQWordProperty = UProperty & {};

/**
 * Class Core.RotatorConversions
 * Size: 0x0060
 * Extends: UObject
 */
export type URotatorConversions = UObject & {};

// RotatorConversions Functions
// static GetAsRadians(InRotator: FRotator): FRotatorRadians
// static GetAsDegrees(InRotator: FRotator): FRotatorDegrees

/**
 * Class Core.ScriptStruct
 * Size: 0x0158
 * Extends: UStruct
 */
export type UScriptStruct = UStruct & {};

/**
 * Class Core.SQWordProperty
 * Size: 0x00C8
 * Extends: UProperty
 */
export type USQWordProperty = UProperty & {};

/**
 * Class Core.StringMap
 * Size: 0x00D8
 * Extends: UComponent
 */
export type UStringMap = UComponent & {
  Map: FMap_Mirror; // 0x0070 (0x0050) [FMap_Mirror]
  __PairCallback__Delegate: FScriptDelegate; // 0x00c0 (0x0018) [FScriptDelegate]
};

// StringMap Functions
// ForEach(Callback: FScriptDelegate): void
// Append(Other: UStringMap): void
// Contains(Key: string): boolean
// Remove(Key: string): void
// TryGet(Key: string, OutValue: string): boolean
// Get(Key: string): string
// Set(Key: string, Value: string): void
// PairCallback(Key: string, Value: string): void

/**
 * Class Core.StringObjectMap
 * Size: 0x00C0
 * Extends: UComponent
 */
export type UStringObjectMap = UComponent & {
  Map: FMap_Mirror; // 0x0070 (0x0050) [FMap_Mirror]
};

// StringObjectMap Functions
// Contains(Key: string): boolean
// Remove(Key: string): void
// TryGetObject(Key: string, OutValue: UObject): boolean
// TryGet(): void
// GetObject(Key: string): UObject
// Get(): void
// Set(Key: string, Value: UObject): void

/**
 * Class Core.StrProperty
 * Size: 0x00C8
 * Extends: UProperty
 */
export type UStrProperty = UProperty & {};

/**
 * Class Core.StructProperty
 * Size: 0x00D0
 * Extends: UProperty
 */
export type UStructProperty = UProperty & {};

/**
 * Class Core.Subscription
 * Size: 0x0078
 * Extends: UObject
 */
export type USubscription = UObject & {
  __SubscriberCallback__Delegate: FScriptDelegate; // 0x0060 (0x0018) [FScriptDelegate]
};

// Subscription Functions
// static __Subscription__TriggerAll_0x1(S: USubscription): void
// static GetNone(): USubscription
// static TriggerAll(Subscriptions: USubscription[]): void
// static Create(InCallback: FScriptDelegate): USubscription
// Dispose(): void
// TriggerCallback(): void
// SetCallback(InCallback: FScriptDelegate): void
// SubscriberCallback(): void

/**
 * Class Core.SubscriptionCollection_ORS
 * Size: 0x0080
 * Extends: UObject
 */
export type USubscriptionCollection_ORS = UObject & {};

/**
 * Class Core.Subsystem
 * Size: 0x0068
 * Extends: UObject
 */
export type USubsystem = UObject & {
  VfTable_FExec: FPointer; // 0x0060 (0x0008) [FPointer]
};

/**
 * Class Core.System
 * Size: 0x0160
 * Extends: USubsystem
 */
export type USystem = USubsystem & {
  StaleCacheDays: number; // 0x0068 (0x0004) [int32]
  MaxStaleCacheSize: number; // 0x006c (0x0004) [int32]
  MaxOverallCacheSize: number; // 0x0070 (0x0004) [int32]
  PackageSizeSoftLimit: number; // 0x0074 (0x0004) [int32]
  AsyncIOBandwidthLimit: number; // 0x0078 (0x0004) [float]
  SavePath: string; // 0x0080 (0x0010) [FString]
  CachePath: string; // 0x0090 (0x0010) [FString]
  CacheExt: string; // 0x00a0 (0x0010) [FString]
  Paths: string[]; // 0x00b0 (0x0010) [TArray<FString>]
  SeekFreePCPaths: string[]; // 0x00c0 (0x0010) [TArray<FString>]
  ScriptPaths: string[]; // 0x00d0 (0x0010) [TArray<FString>]
  FRScriptPaths: string[]; // 0x00e0 (0x0010) [TArray<FString>]
  CutdownPaths: string[]; // 0x00f0 (0x0010) [TArray<FString>]
  Suppress: FName[]; // 0x0100 (0x0010) [TArray<FName>]
  SuppressPublic: FName[]; // 0x0110 (0x0010) [TArray<FName>]
  Extensions: string[]; // 0x0120 (0x0010) [TArray<FString>]
  SeekFreePCExtensions: string[]; // 0x0130 (0x0010) [TArray<FString>]
  LocalizationPaths: string[]; // 0x0140 (0x0010) [TArray<FString>]
  TextureFileCacheExtension: string; // 0x0150 (0x0010) [FString]
};

/**
 * Class Core.TAsyncResult
 * Size: 0x00D0
 * Extends: UAsyncTask
 */
export type UTAsyncResult = UAsyncTask & {};

/**
 * Class Core.TextBuffer
 * Size: 0x0090
 * Extends: UObject
 */
export type UTextBuffer = UObject & {};

/**
 * Class Core.TextBufferFactory
 * Size: 0x00B8
 * Extends: UFactory
 */
export type UTextBufferFactory = UFactory & {};

/**
 * Class Core.UTF8
 * Size: 0x0060
 * Extends: UObject
 */
export type UUTF8 = UObject & {};

// UTF8 Functions
// static DecodeInline(Input: number[], Output: string): void
// static Decode(Input: number[]): string
// static EncodeInline(Input: string, Output: number[]): void
// static Encode(Input: string): number[]
