/**
 * GFxUI Package - Classes
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

import type { FName, FScriptDelegate } from '../types/GameDefines';
import type { EInputEvent } from '../enums/Core';
import type { EEdition, FlashTextureRescale, GFxAlign, GFxCollectionMode, GFxRenderTextureMode, GFxScaleMode, GFxTimingMode } from '../enums/GFxUI';
import type { FMap_Mirror, FMatrix, FPointer } from '../structs/Core';
import type { FASColorTransform, FASDisplayInfo, FASValue, FEventData, FExternalTexture, FGCReference, FGFxWidgetBinding, FLoadingMovieMapInfo, FSoundThemeBinding } from '../structs/GFxUI';
import type { UObject } from './Core';
import type { UGameViewportClient, UInteraction, ULocalPlayer, UPlayerController, USequenceAction, USequenceEvent, UTexture, UTextureRenderTarget2D, UTranslationContext } from './Engine';

/**
 * Class GFxUI.GFxRawData
 * Size: 0x00A0
 * Extends: UObject
 */
export type UGFxRawData = UObject & {
  RawData: number[]; // 0x0060 (0x0010) [TArray<uint8>]
  ReferencedSwfs: string[]; // 0x0070 (0x0010) [TArray<FString>]
  References: UObject[]; // 0x0080 (0x0010) [TArray<UObject*>]
  UserReferences: UObject[]; // 0x0090 (0x0010) [TArray<UObject*>]
};

/**
 * Class GFxUI.SwfMovie
 * Size: 0x0128
 * Extends: UGFxRawData
 */
export type USwfMovie = UGFxRawData & {
  bUsesFontlib: boolean; // 0x00a0 (0x0004) [bool : 0x1]
  bSetSRGBOnImportedTextures: boolean; // 0x00a0 (0x0004) [bool : 0x2]
  bPackTextures: boolean; // 0x00a0 (0x0004) [bool : 0x4]
  bForceSquarePacking: boolean; // 0x00a0 (0x0004) [bool : 0x8]
  SourceFile: string; // 0x00a8 (0x0010) [FString]
  PackTextureSize: number; // 0x00b8 (0x0004) [int32]
  TextureRescale: FlashTextureRescale; // 0x00bc (0x0001) [FlashTextureRescale]
  TextureFormat: string; // 0x00c0 (0x0010) [FString]
  SourceFileTimestamp: string; // 0x00d0 (0x0010) [FString]
  SourceFileCRC: number; // 0x00e0 (0x0004) [int32]
  PrioritizeImportSwfs: string[]; // 0x00e8 (0x0010) [TArray<FString>]
  Editions: EEdition[]; // 0x00f8 (0x0010) [TArray<EEdition>]
  Features: FName[]; // 0x0108 (0x0010) [TArray<FName>]
  RTTextures: number; // 0x0118 (0x0004) [int32]
  RTVideoTextures: number; // 0x011c (0x0004) [int32]
  ImportTimeStamp: bigint; // 0x0120 (0x0008) [uint64]
};

/**
 * Class GFxUI.FlashMovie
 * Size: 0x0128
 * Extends: USwfMovie
 */
export type UFlashMovie = USwfMovie & {};

/**
 * Class GFxUI.GFxAction_CloseMovie
 * Size: 0x016C
 * Extends: USequenceAction
 */
export type UGFxAction_CloseMovie = USequenceAction & {
  Movie: UGFxMoviePlayer; // 0x0160 (0x0008) [UGFxMoviePlayer*]
  bUnload: boolean; // 0x0168 (0x0004) [bool : 0x1]
};

// GFxAction_CloseMovie Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_GetVariable
 * Size: 0x0178
 * Extends: USequenceAction
 */
export type UGFxAction_GetVariable = USequenceAction & {
  Movie: UGFxMoviePlayer; // 0x0160 (0x0008) [UGFxMoviePlayer*]
  Variable: string; // 0x0168 (0x0010) [FString]
};

// GFxAction_GetVariable Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_Invoke
 * Size: 0x0188
 * Extends: USequenceAction
 */
export type UGFxAction_Invoke = USequenceAction & {
  Movie: UGFxMoviePlayer; // 0x0160 (0x0008) [UGFxMoviePlayer*]
  MethodName: string; // 0x0168 (0x0010) [FString]
  Arguments: FASValue[]; // 0x0178 (0x0010) [TArray<FASValue>]
};

// GFxAction_Invoke Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_OpenMovie
 * Size: 0x01A8
 * Extends: USequenceAction
 */
export type UGFxAction_OpenMovie = USequenceAction & {
  Movie: USwfMovie; // 0x0160 (0x0008) [USwfMovie*]
  MoviePlayerClass: UGFxMoviePlayer; // 0x0168 (0x0008) [UGFxMoviePlayer*]
  MoviePlayer: UGFxMoviePlayer; // 0x0170 (0x0008) [UGFxMoviePlayer*]
  bTakeFocus: boolean; // 0x0178 (0x0004) [bool : 0x1]
  bCaptureInput: boolean; // 0x0178 (0x0004) [bool : 0x2]
  bStartPaused: boolean; // 0x0178 (0x0004) [bool : 0x4]
  bEnableGammaCorrection: boolean; // 0x0178 (0x0004) [bool : 0x8]
  bDisplayWithHudOff: boolean; // 0x0178 (0x0004) [bool : 0x10]
  RenderTextureMode: GFxRenderTextureMode; // 0x017c (0x0001) [GFxRenderTextureMode]
  RenderTexture: UTextureRenderTarget2D; // 0x0180 (0x0008) [UTextureRenderTarget2D*]
  CaptureKeys: FName[]; // 0x0188 (0x0010) [TArray<FName>]
  FocusIgnoreKeys: FName[]; // 0x0198 (0x0010) [TArray<FName>]
};

// GFxAction_OpenMovie Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_SetCaptureKeys
 * Size: 0x0178
 * Extends: USequenceAction
 */
export type UGFxAction_SetCaptureKeys = USequenceAction & {
  Movie: UGFxMoviePlayer; // 0x0160 (0x0008) [UGFxMoviePlayer*]
  CaptureKeys: FName[]; // 0x0168 (0x0010) [TArray<FName>]
};

/**
 * Class GFxUI.GFxAction_SetVariable
 * Size: 0x0178
 * Extends: USequenceAction
 */
export type UGFxAction_SetVariable = USequenceAction & {
  Movie: UGFxMoviePlayer; // 0x0160 (0x0008) [UGFxMoviePlayer*]
  Variable: string; // 0x0168 (0x0010) [FString]
};

// GFxAction_SetVariable Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxObject
 * Size: 0x00A0
 * Extends: UObject
 */
export type UGFxObject = UObject & {
  Value: number; // 0x0060 (0x0030) [int32]
  SubWidgetBindings: FGFxWidgetBinding[]; // 0x0090 (0x0010) [TArray<FGFxWidgetBinding>]
};

// GFxObject Functions
// WidgetUnloaded(WidgetName: FName, WidgetPath: FName, Widget: UGFxObject): boolean
// WidgetInitialized(WidgetName: FName, WidgetPath: FName, Widget: UGFxObject): boolean
// AttachMovie(symbolname: string, instancename: string, Depth: number, Type: UGFxObject): UGFxObject
// CreateEmptyMovieClip(instancename: string, Depth: number, Type: UGFxObject): UGFxObject
// GotoAndStopI(frame: number): void
// GotoAndStop(frame: string): void
// GotoAndPlayI(frame: number): void
// GotoAndPlay(frame: string): void
// ActionScriptArray(Path: string): UGFxObject[]
// ActionScriptObject(Path: string): UGFxObject
// ActionScriptString(method: string): string
// ActionScriptFloat(method: string): number
// ActionScriptInt(method: string): number
// ActionScriptVoid(method: string): void
// Invoke(Member: string, args: FASValue[]): FASValue
// ActionScriptSetFunctionOn(Target: UGFxObject, Member: string): void
// ActionScriptSetFunction(Member: string): void
// SetElementMemberString(Index: number, Member: string, S: string): void
// SetElementMemberInt(Index: number, Member: string, I: number): void
// SetElementMemberFloat(Index: number, Member: string, F: number): void
// SetElementMemberBool(Index: number, Member: string, B: boolean): void
// SetElementMemberObject(Index: number, Member: string, val: UGFxObject): void
// SetElementMember(Index: number, Member: string, Arg: FASValue): void
// GetElementMemberString(Index: number, Member: string): string
// GetElementMemberInt(Index: number, Member: string): number
// GetElementMemberFloat(Index: number, Member: string): number
// GetElementMemberBool(Index: number, Member: string): boolean
// GetElementMemberObject(Index: number, Member: string, Type: UGFxObject): UGFxObject
// GetElementMember(Index: number, Member: string): FASValue
// SetElementColorTransform(Index: number, cxform: FASColorTransform): void
// SetElementPosition(Index: number, X: number, Y: number): void
// SetElementVisible(Index: number, Visible: boolean): void
// SetElementDisplayMatrix(Index: number, M: FMatrix): void
// SetElementDisplayInfo(Index: number, D: FASDisplayInfo): void
// GetElementDisplayMatrix(Index: number): FMatrix
// GetElementDisplayInfo(Index: number): FASDisplayInfo
// SetElementString(Index: number, S: string): void
// SetElementInt(Index: number, I: number): void
// SetElementFloat(Index: number, F: number): void
// SetElementBool(Index: number, B: boolean): void
// SetElementObject(Index: number, val: UGFxObject): void
// SetElement(Index: number, Arg: FASValue): void
// GetElementString(Index: number): string
// GetElementInt(Index: number): number
// GetElementFloat(Index: number): number
// GetElementBool(Index: number): boolean
// GetElementObject(Index: number, Type: UGFxObject): UGFxObject
// GetElement(Index: number): FASValue
// SetText(Text: string, InContext: UTranslationContext): void
// GetText(): string
// SetVisible(Visible: boolean): void
// SetDisplayMatrix3D(M: FMatrix): void
// SetDisplayMatrix(M: FMatrix): void
// SetColorTransform(cxform: FASColorTransform): void
// SetPosition(X: number, Y: number): void
// SetDisplayInfo(D: FASDisplayInfo): void
// GetDisplayMatrix3D(): FMatrix
// GetDisplayMatrix(): FMatrix
// GetColorTransform(): FASColorTransform
// GetPosition(X: number, Y: number): boolean
// GetDisplayInfo(): FASDisplayInfo
// static TranslateString(StringToTranslate: string, InContext: UTranslationContext): string
// SetFunction(Member: string, Context: UObject, fname: FName): void
// SetObject(Member: string, val: UGFxObject): void
// SetString(Member: string, S: string, InContext: UTranslationContext): void
// SetInt(Member: string, I: number): void
// SetFloat(Member: string, F: number): void
// SetBool(Member: string, B: boolean): void
// Set(Member: string, Arg: FASValue): void
// GetObject(Member: string, Type: UGFxObject): UGFxObject
// GetString(Member: string): string
// GetInt(Member: string): number
// GetFloat(Member: string): number
// GetBool(Member: string): boolean
// Get(Member: string): FASValue

/**
 * Class GFxUI.GFxClikWidget
 * Size: 0x00B8
 * Extends: UGFxObject
 */
export type UGFxClikWidget = UGFxObject & {
  __EventListener__Delegate: FScriptDelegate; // 0x00a0 (0x0018) [FScriptDelegate]
};

// GFxClikWidget Functions
// ASRemoveAllEventListeners(Event: string): void
// AS3AddEventListener(Type: string, O: UGFxObject, useCapture: boolean, listenerPriority: number, useWeakReference: boolean): void
// ASAddEventListener(Type: string, O: UGFxObject, func: string): void
// SetListener(O: UGFxObject, Member: string, Listener: FScriptDelegate): void
// GetEventStringFromTypename(Typename: FName): string
// RemoveAllEventListeners(Event: string): void
// AddEventListener(Type: FName, Listener: FScriptDelegate, useCapture: boolean, listenerPriority: number, useWeakReference: boolean): void
// EventListener(Data: FEventData): void

/**
 * Class GFxUI.GFxEngine
 * Size: 0x0128
 * Extends: UObject
 */
export type UGFxEngine = UObject & {
  GCReferences: FGCReference[]; // 0x0060 (0x0010) [TArray<FGCReference>]
  RefCount: number; // 0x0070 (0x0004) [int32]
  LoadingScreenInfo: FLoadingMovieMapInfo; // 0x0078 (0x00a0) [FLoadingMovieMapInfo]
  IgnoreWarningsThatStartWith: string[]; // 0x0118 (0x0010) [TArray<FString>]
};

// GFxEngine Functions
// UpdateMovieLoadingInfo(LoadingInfo: FLoadingMovieMapInfo): void
// Tick(DeltaTime: number): void

/**
 * Class GFxUI.GFxEvent_FSCommand
 * Size: 0x01A0
 * Extends: USequenceEvent
 */
export type UGFxEvent_FSCommand = USequenceEvent & {
  Movie: USwfMovie; // 0x0180 (0x0008) [USwfMovie*]
  FSCommand: string; // 0x0188 (0x0010) [FString]
  Handler: UGFxFSCmdHandler_Kismet; // 0x0198 (0x0008) [UGFxFSCmdHandler_Kismet*]
};

/**
 * Class GFxUI.GFxFSCmdHandler
 * Size: 0x0060
 * Extends: UObject
 */
export type UGFxFSCmdHandler = UObject & {};

// GFxFSCmdHandler Functions
// FSCommand(Movie: UGFxMoviePlayer, Event: UGFxEvent_FSCommand, Cmd: string, Arg: string): boolean

/**
 * Class GFxUI.GFxFSCmdHandler_Kismet
 * Size: 0x0060
 * Extends: UGFxFSCmdHandler
 */
export type UGFxFSCmdHandler_Kismet = UGFxFSCmdHandler & {};

// GFxFSCmdHandler_Kismet Functions
// FSCommand(Movie: UGFxMoviePlayer, Event: UGFxEvent_FSCommand, Cmd: string, Arg: string): boolean

/**
 * Class GFxUI.GFxInteraction
 * Size: 0x00DC
 * Extends: UInteraction
 */
export type UGFxInteraction = UInteraction & {
  VfTable_FCallbackEventDevice: FPointer; // 0x00d0 (0x0008) [FPointer]
  bFakeMobileTouches: boolean; // 0x00d8 (0x0004) [bool : 0x1]
};

// GFxInteraction Functions
// DebugInputKey(ControllerId: number, Key: FName, Event: EInputEvent, AmountDepressed: number, bGamepad: boolean): void
// CloseAllMoviePlayers(): void
// NotifySplitscreenLayoutChanged(): void
// NotifyPlayerRemoved(PlayerIndex: number, RemovedPlayer: ULocalPlayer): void
// NotifyPlayerAdded(PlayerIndex: number, AddedPlayer: ULocalPlayer): void
// NotifyGameSessionEnded(): void
// GetFocusMovie(ControllerId: number): UGFxMoviePlayer

/**
 * Class GFxUI.GFxMoviePlayer
 * Size: 0x0218
 * Extends: UObject
 */
export type UGFxMoviePlayer = UObject & {
  pMovie: FPointer; // 0x0060 (0x0008) [FPointer]
  pCaptureKeys: FPointer; // 0x0068 (0x0008) [FPointer]
  pFocusIgnoreKeys: FPointer; // 0x0070 (0x0008) [FPointer]
  ASUClasses: FMap_Mirror; // 0x0078 (0x0050) [FMap_Mirror]
  ASUObjects: FMap_Mirror; // 0x00c8 (0x0050) [FMap_Mirror]
  NextASUObject: number; // 0x0118 (0x0004) [int32]
  MovieInfo: USwfMovie; // 0x0120 (0x0008) [USwfMovie*]
  bMovieIsOpen: boolean; // 0x0128 (0x0004) [bool : 0x1]
  bDisplayWithHudOff: boolean; // 0x0128 (0x0004) [bool : 0x2]
  bEnableGammaCorrection: boolean; // 0x0128 (0x0004) [bool : 0x4]
  bWidgetsInitializedThisFrame: boolean; // 0x0128 (0x0004) [bool : 0x8]
  bLogUnhandedWidgetInitializations: boolean; // 0x0128 (0x0004) [bool : 0x10]
  bAllowInput: boolean; // 0x0128 (0x0004) [bool : 0x20]
  bAllowFocus: boolean; // 0x0128 (0x0004) [bool : 0x40]
  bAutoPlay: boolean; // 0x0128 (0x0004) [bool : 0x80]
  bPauseGameWhileActive: boolean; // 0x0128 (0x0004) [bool : 0x100]
  bDisableWorldRendering: boolean; // 0x0128 (0x0004) [bool : 0x200]
  bCaptureWorldRendering: boolean; // 0x0128 (0x0004) [bool : 0x400]
  bCloseOnLevelChange: boolean; // 0x0128 (0x0004) [bool : 0x800]
  bOnlyOwnerFocusable: boolean; // 0x0128 (0x0004) [bool : 0x1000]
  bForceFullViewport: boolean; // 0x0128 (0x0004) [bool : 0x2000]
  bDiscardNonOwnerInput: boolean; // 0x0128 (0x0004) [bool : 0x4000]
  bCaptureInput: boolean; // 0x0128 (0x0004) [bool : 0x8000]
  bCaptureMouseInput: boolean; // 0x0128 (0x0004) [bool : 0x10000]
  bIgnoreMouseInput: boolean; // 0x0128 (0x0004) [bool : 0x20000]
  bIsSplitscreenLayoutModified: boolean; // 0x0128 (0x0004) [bool : 0x40000]
  bShowHardwareMouseCursor: boolean; // 0x0128 (0x0004) [bool : 0x80000]
  bForceFullScreen: boolean; // 0x0128 (0x0004) [bool : 0x100000]
  bBlurLesserMovies: boolean; // 0x0128 (0x0004) [bool : 0x200000]
  bHideLesserMovies: boolean; // 0x0128 (0x0004) [bool : 0x400000]
  bIsPriorityBlurred: boolean; // 0x0128 (0x0004) [bool : 0x800000]
  bIsPriorityHidden: boolean; // 0x0128 (0x0004) [bool : 0x1000000]
  bIgnoreVisibilityEffect: boolean; // 0x0128 (0x0004) [bool : 0x2000000]
  bIgnoreBlurEffect: boolean; // 0x0128 (0x0004) [bool : 0x4000000]
  RenderTexture: UTextureRenderTarget2D; // 0x0130 (0x0008) [UTextureRenderTarget2D*]
  LocalPlayerOwnerIndex: number; // 0x0138 (0x0004) [int32]
  ExternalInterface: UObject; // 0x0140 (0x0008) [UObject*]
  CaptureKeys: FName[]; // 0x0148 (0x0010) [TArray<FName>]
  FocusIgnoreKeys: FName[]; // 0x0158 (0x0010) [TArray<FName>]
  ExternalTextures: FExternalTexture[]; // 0x0168 (0x0010) [TArray<FExternalTexture>]
  SoundThemes: FSoundThemeBinding[]; // 0x0178 (0x0010) [TArray<FSoundThemeBinding>]
  TimingMode: GFxTimingMode; // 0x0188 (0x0001) [GFxTimingMode]
  RenderTextureMode: GFxRenderTextureMode; // 0x0189 (0x0001) [GFxRenderTextureMode]
  Priority: number; // 0x018a (0x0001) [uint8]
  WidgetBindings: FGFxWidgetBinding[]; // 0x0190 (0x0010) [TArray<FGFxWidgetBinding>]
  WidgetPathBindings: FMap_Mirror; // 0x01a0 (0x0050) [FMap_Mirror]
  SplitscreenLayoutObject: UGFxObject; // 0x01f0 (0x0008) [UGFxObject*]
  SplitscreenLayoutYAdjust: number; // 0x01f8 (0x0004) [int32]
  __OnPostAdvance__Delegate: FScriptDelegate; // 0x0200 (0x0018) [FScriptDelegate]
};

// GFxMoviePlayer Functions
// SetFullScreen(bFullScreen: boolean): void
// IsHidden(): boolean
// SetHidden(bHidden: boolean): void
// RenderOnce(): void
// UpdateSplitscreenLayout(): void
// ApplyPriorityVisibilityEffect(bRemoveEffect: boolean): void
// ApplyPriorityBlurEffect(bRemoveEffect: boolean): void
// ApplyPriorityEffect(bRequestedBlurState: boolean, bRequestedHiddenState: boolean): void
// PlaySoundFromTheme(EventName: FName, SoundThemeName: FName): void
// OnFocusLost(LocalPlayerIndex: number): void
// OnFocusGained(LocalPlayerIndex: number): void
// ConsoleCommand(Command: string): void
// GetPC(): UPlayerController
// GetLP(): ULocalPlayer
// Init(LocPlay: ULocalPlayer): void
// SetWidgetPathBinding(WidgetToBind: UGFxObject, Path: FName): void
// PostWidgetInit(): void
// WidgetUnloaded(WidgetName: FName, WidgetPath: FName, Widget: UGFxObject): boolean
// WidgetInitialized(WidgetName: FName, WidgetPath: FName, Widget: UGFxObject): boolean
// ActionScriptConstructor(ClassName: string): UGFxObject
// ActionScriptObject(Path: string): UGFxObject
// ActionScriptString(Path: string): string
// ActionScriptFloat(Path: string): number
// ActionScriptInt(Path: string): number
// ActionScriptVoid(Path: string): void
// Invoke(method: string, args: FASValue[]): FASValue
// ActionScriptSetFunction(Object: UGFxObject, Member: string): void
// CreateArray(): UGFxObject
// CreateObject(ASClass: string, Type: UGFxObject, args: FASValue[]): UGFxObject
// SetVariableStringArray(Path: string, Index: number, Arg: string[]): boolean
// SetVariableFloatArray(Path: string, Index: number, Arg: number[]): boolean
// SetVariableIntArray(Path: string, Index: number, Arg: number[]): boolean
// SetVariableArray(Path: string, Index: number, Arg: FASValue[]): boolean
// GetVariableStringArray(Path: string, Index: number, Arg: string[]): boolean
// GetVariableFloatArray(Path: string, Index: number, Arg: number[]): boolean
// GetVariableIntArray(Path: string, Index: number, Arg: number[]): boolean
// GetVariableArray(Path: string, Index: number, Arg: FASValue[]): boolean
// SetVariableObject(Path: string, Object: UGFxObject): void
// SetVariableString(Path: string, S: string): void
// SetVariableInt(Path: string, I: number): void
// SetVariableNumber(Path: string, F: number): void
// SetVariableBool(Path: string, B: boolean): void
// SetVariable(Path: string, Arg: FASValue): void
// GetVariableObject(Path: string, Type: UGFxObject): UGFxObject
// GetVariableString(Path: string): string
// GetVariableInt(Path: string): number
// GetVariableNumber(Path: string): number
// GetVariableBool(Path: string): boolean
// GetVariable(Path: string): FASValue
// GetAVMVersion(): number
// FilterButtonInput(ControllerId: number, ButtonName: FName, InputEvent: EInputEvent): boolean
// FlushPlayerInput(capturekeysonly: boolean): void
// ClearFocusIgnoreKeys(): void
// AddFocusIgnoreKey(Key: FName): void
// ClearCaptureKeys(): void
// AddCaptureKey(Key: FName): void
// SetMovieCanReceiveInput(bCanReceiveInput: boolean): void
// SetMovieCanReceiveFocus(bCanReceiveFocus: boolean): void
// SetPerspective3D(matPersp: FMatrix): void
// SetView3D(matView: FMatrix): void
// GetVisibleFrameRect(x0: number, y0: number, X1: number, Y1: number): void
// SetAlignment(A: GFxAlign): void
// SetViewScaleMode(SM: GFxScaleMode): void
// SetViewport(X: number, Y: number, Width: number, Height: number): void
// GetGameViewportClient(): UGameViewportClient
// RequestGarbageCollection(Mode: GFxCollectionMode, bImmediate: boolean): void
// SetPriority(NewPriority: number): void
// SetExternalTexture(Resource: string, Texture: UTexture): boolean
// SetExternalInterface(H: UObject): void
// SetTimingMode(Mode: GFxTimingMode): void
// SetMovieInfo(Data: USwfMovie): void
// ConditionalClearPause(): void
// OnCleanup(): void
// OnClose(): void
// Close(Unload: boolean): void
// SetPause(bPausePlayback: boolean): void
// OnPostAdvance(DeltaTime: number): void
// PostAdvance(DeltaTime: number): void
// Advance(Time: number): void
// Start(StartPaused: boolean): boolean
