/**
 * ProjectX Package - Constants
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 */

export const ClosedReason_DuplicateLogin = '"DuplicateLogin"'; // ProjectX.WebSocketConnection_X.ClosedReason_DuplicateLogin
export const HttpContentType = '"plain/text"'; // ProjectX.MatchLog_X.HttpContentType
export const InMatchmakingID = -2; // ProjectX.GameSettingPlaylist_X.InMatchmakingID
export const LocalPlayersBroadcastDelay = '0.1f'; // ProjectX.OnlineGameParty_X.LocalPlayersBroadcastDelay
export const MaxPing = '1.0f'; // ProjectX.RegionPing_X.MaxPing
export const MaxPrivateMatchNameLength = 16; // ProjectX._Types_X.MaxPrivateMatchNameLength
export const MaxPrivateMatchPasswordLength = 16; // ProjectX._Types_X.MaxPrivateMatchPasswordLength
export const NumFriendsPerRequest = 100; // ProjectX.OnlineGameLeaderboards_X.NumFriendsPerRequest
export const PrimaryControllerId = 0; // ProjectX.BlockStatusReporter_X.PrimaryControllerId
export const QueueMax = 100; // ProjectX.ActionQueue_X.QueueMax
export const ReservationType_FriendJoin = "'FriendJoin'"; // ProjectX._Types_X.ReservationType_FriendJoin
export const ReservationType_JoinPrivateMatch = "'JoinPrivate'"; // ProjectX._Types_X.ReservationType_JoinPrivateMatch
export const ReservationType_Reconnect = "'Reconnect'"; // ProjectX._Types_X.ReservationType_Reconnect
export const XpTitleID = "'XP'"; // ProjectX.TitleConfig_X.XpTitleID
