/**
 * IpDrv Package - Offsets
 * Auto-generated by Stev Peifer <stev.p@outlook.com> (https://github.com/ObscuritySRL)
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

/**
 * Core.Object Offsets
 * Size: 0x0060
 */
export const Object_ = {
  VfTableObject: 0x0000n, // 0x0000 (0x0008) [FPointer]
  HashNext: 0x0008n, // 0x0008 (0x0008) [FPointer]
  ObjectFlags: 0x0010n, // 0x0010 (0x0008) [uint64]
  HashOuterNext: 0x0018n, // 0x0018 (0x0008) [FPointer]
  StateFrame: 0x0020n, // 0x0020 (0x0008) [FPointer]
  Linker: 0x0028n, // 0x0028 (0x0008) [UObject*]
  LinkerIndex: 0x0030n, // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: 0x0038n, // 0x0038 (0x0004) [int32]
  NetIndex: 0x003cn, // 0x003c (0x0004) [int32]
  Outer: 0x0040n, // 0x0040 (0x0008) [UObject*]
  Name: 0x0048n, // 0x0048 (0x0008) [FName]
  Class: 0x0050n, // 0x0050 (0x0008) [UObject*]
  ObjectArchetype: 0x0058n, // 0x0058 (0x0008) [UObject*]
} as const;

/**
 * IpDrv.AdHocDelegates Offsets
 * Size: 0x0138
 * Extends: Object_
 */
export const AdHocDelegates = {
  __EventAdHocOnNetworkChanged__Delegate: 0x0060n, // 0x0060 (0x0018) [FScriptDelegate]
  __EventAdHocError__Delegate: 0x0078n, // 0x0078 (0x0018) [FScriptDelegate]
  __EventAdHocInitialized__Delegate: 0x0090n, // 0x0090 (0x0018) [FScriptDelegate]
  __EventAccessPointCreated__Delegate: 0x00a8n, // 0x00a8 (0x0018) [FScriptDelegate]
  __EventBecomeStation__Delegate: 0x00c0n, // 0x00c0 (0x0018) [FScriptDelegate]
  __EventStationConnected__Delegate: 0x00d8n, // 0x00d8 (0x0018) [FScriptDelegate]
  __EventStationDisconnected__Delegate: 0x00f0n, // 0x00f0 (0x0018) [FScriptDelegate]
  __EventAdHocFinalized__Delegate: 0x0108n, // 0x0108 (0x0018) [FScriptDelegate]
  __EventAdHocDestroyed__Delegate: 0x0120n, // 0x0120 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Core.ErrorList Offsets
 * Size: 0x0080
 * Extends: Object_
 */
export const ErrorList = {
  LocalizationPackage: 0x0060n, // 0x0060 (0x0010) [FString]
  LocalizationSection: 0x0070n, // 0x0070 (0x0010) [FString]
  ...Object_,
} as const;

/**
 * IpDrv.AdHocErrors Offsets
 * Size: 0x0088
 * Extends: ErrorList
 */
export const AdHocErrors = {
  AdHocError: 0x0080n, // 0x0080 (0x0008) [UErrorType*]
  ...ErrorList,
} as const;

/**
 * IpDrv.AvatarDownload Offsets
 * Size: 0x00e0
 * Extends: Object_
 */
export const AvatarDownload = {
  PlayerID: 0x0060n, // 0x0060 (0x0048) [FUniqueNetId]
  URL: 0x00a8n, // 0x00a8 (0x0010) [FString]
  AvatarSize: 0x00b8n, // 0x00b8 (0x0001) [AvatarSize]
  Texture: 0x00c0n, // 0x00c0 (0x0008) [UTexture*]
  Callbacks: 0x00c8n, // 0x00c8 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Core.Component Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const Component = {
  TemplateOwnerClass: 0x0060n, // 0x0060 (0x0008) [UObject*]
  TemplateName: 0x0068n, // 0x0068 (0x0008) [FName]
  ...Object_,
} as const;

/**
 * IpDrv.AvatarDownloadComponent Offsets
 * Size: 0x0080
 * Extends: Component
 */
export const AvatarDownloadComponent = {
  AvatarDownloadCache: 0x0070n, // 0x0070 (0x0008) [UAvatarDownloadMap*]
  ImageDownloader: 0x0078n, // 0x0078 (0x0008) [UOnlineImageDownloaderWeb*]
  ...Component,
} as const;

/**
 * IpDrv.AvatarDownloadMap Offsets
 * Size: 0x0160
 * Extends: Component
 */
export const AvatarDownloadMap = {
  AvatarMap: 0x0070n, // 0x0070 (0x0050) [FMap_Mirror]
  ImageMap: 0x00c0n, // 0x00c0 (0x0050) [FMap_Mirror]
  AvatarsPendingImages: 0x0110n, // 0x0110 (0x0050) [FMap_Mirror]
  ...Component,
} as const;

/**
 * IpDrv.ClientBeaconAddressResolver Offsets
 * Size: 0x006c
 * Extends: Object_
 */
export const ClientBeaconAddressResolver = {
  BeaconPort: 0x0060n, // 0x0060 (0x0004) [int32]
  BeaconName: 0x0064n, // 0x0064 (0x0008) [FName]
  ...Object_,
} as const;

/**
 * IpDrv.McpIdMappingManager.AddMappingRequest Offsets
 * Size: 0x0038
 */
export const FAddMappingRequest = {
  McpId: 0x0000n, // 0x0000 (0x0010) [FString]
  ExternalId: 0x0010n, // 0x0010 (0x0010) [FString]
  ExternalType: 0x0020n, // 0x0020 (0x0010) [FString]
  Request: 0x0030n, // 0x0030 (0x0008) [UHttpRequestInterface*]
} as const;

/**
 * IpDrv.AdHocDelegates.AdHocAccessPointInfo Offsets
 * Size: 0x0038
 */
export const FAdHocAccessPointInfo = {
  Ipv4Addr: 0x0000n, // 0x0000 (0x0010) [FString]
  Username: 0x0010n, // 0x0010 (0x0010) [FString]
  AdvertiseData: 0x0020n, // 0x0020 (0x0010) [FString]
  ScanResultIndex: 0x0030n, // 0x0030 (0x0004) [int32]
  NetworkNodeIndex: 0x0034n, // 0x0034 (0x0004) [int32]
} as const;

/**
 * IpDrv.AdHocDelegates.AdHocStationInfo Offsets
 * Size: 0x0010
 */
export const FAdHocStationInfo = {
  Username: 0x0000n, // 0x0000 (0x0010) [FString]
} as const;

/**
 * IpDrv.OnlineAuthInterfaceImpl.AuthCodeRequest Offsets
 * Size: 0x0064
 */
export const FAuthCodeRequest = {
  PlayerID: 0x0000n, // 0x0000 (0x0048) [FUniqueNetId]
  Callback: 0x0048n, // 0x0048 (0x0018) [FScriptDelegate]
  RequestID: 0x0060n, // 0x0060 (0x0004) [int32]
} as const;

/**
 * IpDrv.AvatarDownloadMap.AvatarKey Offsets
 * Size: 0x0049
 */
export const FAvatarKey = {
  PlayerID: 0x0000n, // 0x0000 (0x0048) [FUniqueNetId]
  Size: 0x0048n, // 0x0048 (0x0001) [AvatarSize]
} as const;

/**
 * IpDrv.MeshBeaconClient.ClientBandwidthTestData Offsets
 * Size: 0x0014
 */
export const FClientBandwidthTestData = {
  TestType: 0x0000n, // 0x0000 (0x0001) [EMeshBeaconBandwidthTestType]
  CurrentState: 0x0001n, // 0x0001 (0x0001) [EMeshBeaconBandwidthTestState]
  NumBytesToSendTotal: 0x0004n, // 0x0004 (0x0004) [int32]
  NumBytesSentTotal: 0x0008n, // 0x0008 (0x0004) [int32]
  NumBytesSentLast: 0x000cn, // 0x000c (0x0004) [int32]
  ElapsedTestTime: 0x0010n, // 0x0010 (0x0004) [float]
} as const;

/**
 * IpDrv.PartyBeaconHost.ClientBeaconConnection Offsets
 * Size: 0x0058
 */
export const FClientBeaconConnection = {
  PartyLeader: 0x0000n, // 0x0000 (0x0048) [FUniqueNetId]
  ElapsedHeartbeatTime: 0x0048n, // 0x0048 (0x0004) [float]
  Socket: 0x0050n, // 0x0050 (0x0008) [FPointer]
} as const;

/**
 * IpDrv.MeshBeaconHost.ClientConnectionBandwidthTestData Offsets
 * Size: 0x002c
 */
export const FClientConnectionBandwidthTestData = {
  CurrentState: 0x0000n, // 0x0000 (0x0001) [EMeshBeaconBandwidthTestState]
  TestType: 0x0001n, // 0x0001 (0x0001) [EMeshBeaconBandwidthTestType]
  BytesTotalNeeded: 0x0004n, // 0x0004 (0x0004) [int32]
  BytesReceived: 0x0008n, // 0x0008 (0x0004) [int32]
  RequestTestStartTime: 0x0010n, // 0x0010 (0x0008) [FDouble]
  TestStartTime: 0x0018n, // 0x0018 (0x0008) [FDouble]
  BandwidthStats: 0x0020n, // 0x0020 (0x000c) [FConnectionBandwidthStats]
} as const;

/**
 * IpDrv.MeshBeaconClient.ClientConnectionRequest Offsets
 * Size: 0x006c
 */
export const FClientConnectionRequest = {
  PlayerNetId: 0x0000n, // 0x0000 (0x0048) [FUniqueNetId]
  NatType: 0x0048n, // 0x0048 (0x0001) [ENATType]
  bCanHostVs: 0x004cn, // 0x004c (0x0004) [bool : 0x1]
  GoodHostRatio: 0x0050n, // 0x0050 (0x0004) [float]
  BandwidthHistory: 0x0058n, // 0x0058 (0x0010) [TArray<FConnectionBandwidthStats>]
  MinutesSinceLastTest: 0x0068n, // 0x0068 (0x0004) [int32]
} as const;

/**
 * IpDrv.MeshBeaconHost.ClientMeshBeaconConnection Offsets
 * Size: 0x00b4
 */
export const FClientMeshBeaconConnection = {
  PlayerNetId: 0x0000n, // 0x0000 (0x0048) [FUniqueNetId]
  ElapsedHeartbeatTime: 0x0048n, // 0x0048 (0x0004) [float]
  Socket: 0x0050n, // 0x0050 (0x0008) [FPointer]
  bConnectionAccepted: 0x0058n, // 0x0058 (0x0004) [bool : 0x1]
  BandwidthTest: 0x0060n, // 0x0060 (0x0030) [FClientConnectionBandwidthTestData]
  NatType: 0x0090n, // 0x0090 (0x0001) [ENATType]
  bCanHostVs: 0x0094n, // 0x0094 (0x0004) [bool : 0x1]
  GoodHostRatio: 0x0098n, // 0x0098 (0x0004) [float]
  BandwidthHistory: 0x00a0n, // 0x00a0 (0x0010) [TArray<FConnectionBandwidthStats>]
  MinutesSinceLastTest: 0x00b0n, // 0x00b0 (0x0004) [int32]
} as const;

/**
 * IpDrv.OnlinePlaylistManager.ConfiguredGameSetting Offsets
 * Size: 0x0030
 */
export const FConfiguredGameSetting = {
  GameSettingId: 0x0000n, // 0x0000 (0x0004) [int32]
  GameSettingsClassName: 0x0008n, // 0x0008 (0x0010) [FString]
  URL: 0x0018n, // 0x0018 (0x0010) [FString]
  GameSettings: 0x0028n, // 0x0028 (0x0008) [UOnlineGameSettings*]
} as const;

/**
 * IpDrv.MeshBeacon.ConnectionBandwidthStats Offsets
 * Size: 0x000c
 */
export const FConnectionBandwidthStats = {
  UpstreamRate: 0x0000n, // 0x0000 (0x0004) [int32]
  DownstreamRate: 0x0004n, // 0x0004 (0x0004) [int32]
  RoundtripLatency: 0x0008n, // 0x0008 (0x0004) [int32]
} as const;

/**
 * IpDrv.ImageDecoder.DecodeImageRequest Offsets
 * Size: 0x0030
 */
export const FDecodeImageRequest = {
  RequestURL: 0x0000n, // 0x0000 (0x0010) [FString]
  OnFinishedCallback: 0x0010n, // 0x0010 (0x0018) [FScriptDelegate]
  Task: 0x0028n, // 0x0028 (0x0008) [FPointer]
} as const;

/**
 * IpDrv.ImageDecoder.DecodeImageTask Offsets
 * Size: 0x0040
 */
export const FDecodeImageTask = {
  RequestURL: 0x0000n, // 0x0000 (0x0010) [FString]
  ImageType: 0x0010n, // 0x0010 (0x0001) [EImageType]
  ImageData: 0x0018n, // 0x0018 (0x0010) [TArray<uint8>]
  Result: 0x0028n, // 0x0028 (0x0018) [FImageLayout]
} as const;

/**
 * IpDrv.OnlineEventsInterfaceMcp.EventUploadConfig Offsets
 * Size: 0x0020
 */
export const FEventUploadConfig = {
  UploadType: 0x0000n, // 0x0000 (0x0001) [EEventUploadType]
  UploadUrl: 0x0008n, // 0x0008 (0x0010) [FString]
  Timeout: 0x0018n, // 0x0018 (0x0004) [float]
  bUseCompression: 0x001cn, // 0x001c (0x0004) [bool : 0x1]
} as const;

/**
 * IpDrv.OnlineTitleFileDownloadBase.FileNameToURLMapping Offsets
 * Size: 0x0010
 */
export const FFileNameToURLMapping = {
  Filename: 0x0000n, // 0x0000 (0x0008) [FName]
  UrlMapping: 0x0008n, // 0x0008 (0x0008) [FName]
} as const;

/**
 * IpDrv.McpUserInventoryManager.SaveSlotRequestState Offsets
 * Size: 0x0028
 */
export const FSaveSlotRequestState = {
  McpId: 0x0000n, // 0x0000 (0x0010) [FString]
  SaveSlotId: 0x0010n, // 0x0010 (0x0010) [FString]
  Request: 0x0020n, // 0x0020 (0x0008) [UHttpRequestInterface*]
} as const;

/**
 * IpDrv.McpUserInventoryManager.InventoryItemRequestState Offsets
 * Size: 0x0038
 * Extends: FSaveSlotRequestState
 */
export const FInventoryItemRequestState = {
  ItemID: 0x0028n, // 0x0028 (0x0010) [FString]
  ...FSaveSlotRequestState,
} as const;

/**
 * IpDrv.McpManagedValueManagerBase.ManagedValue Offsets
 * Size: 0x000c
 */
export const FManagedValue = {
  ValueId: 0x0000n, // 0x0000 (0x0008) [FName]
  Value: 0x0008n, // 0x0008 (0x0004) [int32]
} as const;

/**
 * IpDrv.McpManagedValueManagerBase.ManagedValueSaveSlot Offsets
 * Size: 0x0030
 */
export const FManagedValueSaveSlot = {
  OwningMcpId: 0x0000n, // 0x0000 (0x0010) [FString]
  SaveSlot: 0x0010n, // 0x0010 (0x0010) [FString]
  Values: 0x0020n, // 0x0020 (0x0010) [TArray<FManagedValue>]
} as const;

/**
 * IpDrv.McpClashMobManager.McpChallengeRequest Offsets
 * Size: 0x0018
 */
export const FMcpChallengeRequest = {
  UniqueChallengeId: 0x0000n, // 0x0000 (0x0010) [FString]
  HTTPRequest: 0x0010n, // 0x0010 (0x0008) [UHttpRequestInterface*]
} as const;

/**
 * IpDrv.McpClashMobManager.McpChallengeUserRequest Offsets
 * Size: 0x0050
 */
export const FMcpChallengeUserRequest = {
  UniqueUserId: 0x0000n, // 0x0000 (0x0010) [FString]
  ChallengeStatusRequests: 0x0010n, // 0x0010 (0x0010) [TArray<FMcpChallengeRequest>]
  ChallengeAcceptRequests: 0x0020n, // 0x0020 (0x0010) [TArray<FMcpChallengeRequest>]
  ChallengeUpdateProgressRequests: 0x0030n, // 0x0030 (0x0010) [TArray<FMcpChallengeRequest>]
  ChallengeUpdateRewardRequests: 0x0040n, // 0x0040 (0x0010) [TArray<FMcpChallengeRequest>]
} as const;

/**
 * IpDrv.McpClashMobBase.McpClashMobChallengeEvent Offsets
 * Size: 0x00e0
 */
export const FMcpClashMobChallengeEvent = {
  unique_challenge_id: 0x0000n, // 0x0000 (0x0010) [FString]
  visible_date: 0x0010n, // 0x0010 (0x0010) [FString]
  start_date: 0x0020n, // 0x0020 (0x0010) [FString]
  end_date: 0x0030n, // 0x0030 (0x0010) [FString]
  completed_date: 0x0040n, // 0x0040 (0x0010) [FString]
  purge_date: 0x0050n, // 0x0050 (0x0010) [FString]
  challenge_type: 0x0060n, // 0x0060 (0x0010) [FString]
  num_attempts: 0x0070n, // 0x0070 (0x0004) [int32]
  num_successful_attempts: 0x0074n, // 0x0074 (0x0004) [int32]
  goal_value: 0x0078n, // 0x0078 (0x0004) [int32]
  goal_start_value: 0x007cn, // 0x007c (0x0004) [int32]
  goal_current_value: 0x0080n, // 0x0080 (0x0004) [int32]
  has_started: 0x0084n, // 0x0084 (0x0004) [bool : 0x1]
  is_visible: 0x0084n, // 0x0084 (0x0004) [bool : 0x2]
  has_completed: 0x0084n, // 0x0084 (0x0004) [bool : 0x4]
  was_successful: 0x0084n, // 0x0084 (0x0004) [bool : 0x8]
  file_list: 0x0088n, // 0x0088 (0x0010) [TArray<FMcpClashMobChallengeFile>]
  facebook_likes: 0x0098n, // 0x0098 (0x0004) [int32]
  facebook_comments: 0x009cn, // 0x009c (0x0004) [int32]
  facebook_like_scaler: 0x00a0n, // 0x00a0 (0x0004) [float]
  facebook_comment_scaler: 0x00a4n, // 0x00a4 (0x0004) [float]
  facebook_like_goal_progress: 0x00a8n, // 0x00a8 (0x0004) [int32]
  facebook_comment_goal_progress: 0x00acn, // 0x00ac (0x0004) [int32]
  facebook_id: 0x00b0n, // 0x00b0 (0x0010) [FString]
  twitter_retweets: 0x00c0n, // 0x00c0 (0x0004) [int32]
  twitter_retweets_scaler: 0x00c4n, // 0x00c4 (0x0004) [float]
  twitter_goal_progress: 0x00c8n, // 0x00c8 (0x0004) [int32]
  twitter_id: 0x00d0n, // 0x00d0 (0x0010) [FString]
} as const;

/**
 * IpDrv.McpClashMobBase.McpClashMobChallengeFile Offsets
 * Size: 0x0059
 */
export const FMcpClashMobChallengeFile = {
  should_keep_post_challenge: 0x0000n, // 0x0000 (0x0004) [bool : 0x1]
  title_id: 0x0008n, // 0x0008 (0x0010) [FString]
  file_name: 0x0018n, // 0x0018 (0x0010) [FString]
  dl_name: 0x0028n, // 0x0028 (0x0010) [FString]
  hash_code: 0x0038n, // 0x0038 (0x0010) [FString]
  Type: 0x0048n, // 0x0048 (0x0010) [FString]
  Status: 0x0058n, // 0x0058 (0x0001) [McpChallengeFileStatus]
} as const;

/**
 * IpDrv.McpClashMobBase.McpClashMobChallengeUserStatus Offsets
 * Size: 0x008c
 */
export const FMcpClashMobChallengeUserStatus = {
  unique_challenge_id: 0x0000n, // 0x0000 (0x0010) [FString]
  unique_user_id: 0x0010n, // 0x0010 (0x0010) [FString]
  num_attempts: 0x0020n, // 0x0020 (0x0004) [int32]
  num_successful_attempts: 0x0024n, // 0x0024 (0x0004) [int32]
  goal_progress: 0x0028n, // 0x0028 (0x0004) [int32]
  did_complete: 0x002cn, // 0x002c (0x0004) [bool : 0x1]
  last_update_time: 0x0030n, // 0x0030 (0x0010) [FString]
  user_award_given: 0x0040n, // 0x0040 (0x0004) [int32]
  accept_time: 0x0048n, // 0x0048 (0x0010) [FString]
  did_preregister: 0x0058n, // 0x0058 (0x0004) [bool : 0x1]
  facebook_like_time: 0x0060n, // 0x0060 (0x0010) [FString]
  enrolled_via_facebook: 0x0070n, // 0x0070 (0x0004) [bool : 0x1]
  liked_via_facebook: 0x0070n, // 0x0070 (0x0004) [bool : 0x2]
  commented_via_facebook: 0x0070n, // 0x0070 (0x0004) [bool : 0x4]
  twitter_retweet_time: 0x0078n, // 0x0078 (0x0010) [FString]
  enrolled_via_twitter: 0x0088n, // 0x0088 (0x0004) [bool : 0x1]
  retweeted: 0x0088n, // 0x0088 (0x0004) [bool : 0x2]
} as const;

/**
 * IpDrv.McpClashMobBase.McpClashMobPushNotification Offsets
 * Size: 0x0044
 */
export const FMcpClashMobPushNotification = {
  device_tokens: 0x0000n, // 0x0000 (0x0010) [TArray<FString>]
  badge_type: 0x0010n, // 0x0010 (0x0010) [FString]
  Sound: 0x0020n, // 0x0020 (0x0010) [FString]
  Message: 0x0030n, // 0x0030 (0x0010) [FString]
  Params: 0x0040n, // 0x0040 (0x0004) [FMcpClashMobPushNotificationParams]
} as const;

/**
 * IpDrv.McpClashMobBase.McpClashMobPushNotificationParams Offsets
 * Size: 0x0004
 */
export const FMcpClashMobPushNotificationParams = {
  bah: 0x0000n, // 0x0000 (0x0004) [int32]
} as const;

/**
 * IpDrv.McpMessageManager.McpCompressMessageRequest Offsets
 * Size: 0x0038
 */
export const FMcpCompressMessageRequest = {
  SourceBuffer: 0x0000n, // 0x0000 (0x0010) [TArray<uint8>]
  DestBuffer: 0x0010n, // 0x0010 (0x0010) [TArray<uint8>]
  OutCompressedSize: 0x0020n, // 0x0020 (0x0004) [int32]
  Request: 0x0028n, // 0x0028 (0x0008) [UHttpRequestInterface*]
  CompressionWorker: 0x0030n, // 0x0030 (0x0008) [FPointer]
} as const;

/**
 * IpDrv.McpGroupsBase.McpGroup Offsets
 * Size: 0x0048
 */
export const FMcpGroup = {
  OwnerId: 0x0000n, // 0x0000 (0x0010) [FString]
  GroupId: 0x0010n, // 0x0010 (0x0010) [FString]
  GroupName: 0x0020n, // 0x0020 (0x0010) [FString]
  AccessLevel: 0x0030n, // 0x0030 (0x0001) [EMcpGroupAccessLevel]
  Members: 0x0038n, // 0x0038 (0x0010) [TArray<FMcpGroupMember>]
} as const;

/**
 * IpDrv.McpGroupsBase.McpGroupList Offsets
 * Size: 0x0020
 */
export const FMcpGroupList = {
  RequesterId: 0x0000n, // 0x0000 (0x0010) [FString]
  Groups: 0x0010n, // 0x0010 (0x0010) [TArray<FMcpGroup>]
} as const;

/**
 * IpDrv.McpGroupsBase.McpGroupMember Offsets
 * Size: 0x0011
 */
export const FMcpGroupMember = {
  MemberId: 0x0000n, // 0x0000 (0x0010) [FString]
  AcceptState: 0x0010n, // 0x0010 (0x0001) [EMcpGroupAcceptState]
} as const;

/**
 * IpDrv.McpIdMappingBase.McpIdMapping Offsets
 * Size: 0x0030
 */
export const FMcpIdMapping = {
  McpId: 0x0000n, // 0x0000 (0x0010) [FString]
  ExternalId: 0x0010n, // 0x0010 (0x0010) [FString]
  ExternalType: 0x0020n, // 0x0020 (0x0010) [FString]
} as const;

/**
 * IpDrv.McpUserInventoryBase.McpInventoryItem Offsets
 * Size: 0x0050
 */
export const FMcpInventoryItem = {
  InstanceItemId: 0x0000n, // 0x0000 (0x0010) [FString]
  GlobalItemId: 0x0010n, // 0x0010 (0x0010) [FString]
  Quantity: 0x0020n, // 0x0020 (0x0004) [int32]
  QuantityIAP: 0x0024n, // 0x0024 (0x0004) [int32]
  Scalar: 0x0028n, // 0x0028 (0x0004) [float]
  LastUpdateTime: 0x0030n, // 0x0030 (0x0010) [FString]
  Attributes: 0x0040n, // 0x0040 (0x0010) [TArray<FMcpInventoryItemAttribute>]
} as const;

/**
 * IpDrv.McpUserInventoryBase.McpInventoryItemAttribute Offsets
 * Size: 0x0014
 */
export const FMcpInventoryItemAttribute = {
  AttributeId: 0x0000n, // 0x0000 (0x0010) [FString]
  Value: 0x0010n, // 0x0010 (0x0004) [int32]
} as const;

/**
 * IpDrv.McpUserInventoryBase.McpInventoryItemContainer Offsets
 * Size: 0x0014
 */
export const FMcpInventoryItemContainer = {
  GlobalItemId: 0x0000n, // 0x0000 (0x0010) [FString]
  Quantity: 0x0010n, // 0x0010 (0x0004) [int32]
} as const;

/**
 * IpDrv.McpUserInventoryBase.McpInventorySaveSlot Offsets
 * Size: 0x0030
 */
export const FMcpInventorySaveSlot = {
  OwningMcpId: 0x0000n, // 0x0000 (0x0010) [FString]
  SaveSlotId: 0x0010n, // 0x0010 (0x0010) [FString]
  Items: 0x0020n, // 0x0020 (0x0010) [TArray<FMcpInventoryItem>]
} as const;

/**
 * IpDrv.McpMessageBase.McpMessage Offsets
 * Size: 0x0061
 */
export const FMcpMessage = {
  MessageId: 0x0000n, // 0x0000 (0x0010) [FString]
  ToUniqueUserId: 0x0010n, // 0x0010 (0x0010) [FString]
  FromUniqueUserId: 0x0020n, // 0x0020 (0x0010) [FString]
  FromFriendlyName: 0x0030n, // 0x0030 (0x0010) [FString]
  MessageType: 0x0040n, // 0x0040 (0x0010) [FString]
  ValidUntil: 0x0050n, // 0x0050 (0x0010) [FString]
  MessageCompressionType: 0x0060n, // 0x0060 (0x0001) [EMcpMessageCompressionType]
} as const;

/**
 * IpDrv.McpMessageBase.McpMessageContents Offsets
 * Size: 0x0020
 */
export const FMcpMessageContents = {
  MessageId: 0x0000n, // 0x0000 (0x0010) [FString]
  MessageContents: 0x0010n, // 0x0010 (0x0010) [TArray<uint8>]
} as const;

/**
 * IpDrv.McpMessageBase.McpMessageList Offsets
 * Size: 0x0020
 */
export const FMcpMessageList = {
  ToUniqueUserId: 0x0000n, // 0x0000 (0x0010) [FString]
  Messages: 0x0010n, // 0x0010 (0x0010) [TArray<FMcpMessage>]
} as const;

/**
 * IpDrv.McpMessageManager.McpUncompressMessageRequest Offsets
 * Size: 0x0040
 */
export const FMcpUncompressMessageRequest = {
  MessageId: 0x0000n, // 0x0000 (0x0010) [FString]
  SourceBuffer: 0x0010n, // 0x0010 (0x0010) [TArray<uint8>]
  DestBuffer: 0x0020n, // 0x0020 (0x0010) [TArray<uint8>]
  OutUncompressedSize: 0x0030n, // 0x0030 (0x0004) [int32]
  UncompressionWorker: 0x0038n, // 0x0038 (0x0008) [FPointer]
} as const;

/**
 * Engine.OnlineSubsystem.EmsFile Offsets
 * Size: 0x0034
 */
export const FEmsFile = {
  Hash: 0x0000n, // 0x0000 (0x0010) [FString]
  DLName: 0x0010n, // 0x0010 (0x0010) [FString]
  Filename: 0x0020n, // 0x0020 (0x0010) [FString]
  FileSize: 0x0030n, // 0x0030 (0x0004) [int32]
} as const;

/**
 * IpDrv.McpUserCloudFileDownload.McpUserCloudFileInfo Offsets
 * Size: 0x0068
 * Extends: FEmsFile
 */
export const FMcpUserCloudFileInfo = {
  CreationDate: 0x0038n, // 0x0038 (0x0010) [FString]
  LastUpdateDate: 0x0048n, // 0x0048 (0x0010) [FString]
  CompressionType: 0x0058n, // 0x0058 (0x0010) [FString]
  ...FEmsFile,
} as const;

/**
 * IpDrv.McpUserCloudFileDownload.McpUserCloudFilesEntry Offsets
 * Size: 0x0038
 */
export const FMcpUserCloudFilesEntry = {
  UserId: 0x0000n, // 0x0000 (0x0010) [FString]
  DownloadedFiles: 0x0010n, // 0x0010 (0x0010) [TArray<FTitleFileWeb>]
  EnumeratedFiles: 0x0020n, // 0x0020 (0x0010) [TArray<FMcpUserCloudFileInfo>]
  HTTPRequestEnumerateFiles: 0x0030n, // 0x0030 (0x0008) [UHttpRequestInterface*]
} as const;

/**
 * IpDrv.McpUserManagerBase.McpUserStatus Offsets
 * Size: 0x0068
 */
export const FMcpUserStatus = {
  McpId: 0x0000n, // 0x0000 (0x0010) [FString]
  SecretKey: 0x0010n, // 0x0010 (0x0010) [FString]
  Ticket: 0x0020n, // 0x0020 (0x0010) [FString]
  UDID: 0x0030n, // 0x0030 (0x0010) [FString]
  RegisteredDate: 0x0040n, // 0x0040 (0x0010) [FString]
  LastActiveDate: 0x0050n, // 0x0050 (0x0010) [FString]
  DaysInactive: 0x0060n, // 0x0060 (0x0004) [int32]
  bIsBanned: 0x0064n, // 0x0064 (0x0004) [bool : 0x1]
} as const;

/**
 * IpDrv.OnlineNewsInterfaceMcp.NewsCacheEntry Offsets
 * Size: 0x0038
 */
export const FNewsCacheEntry = {
  NewsUrl: 0x0000n, // 0x0000 (0x0010) [FString]
  ReadState: 0x0010n, // 0x0010 (0x0001) [EOnlineEnumerationReadState]
  NewsType: 0x0011n, // 0x0011 (0x0001) [EOnlineNewsType]
  NewsItem: 0x0018n, // 0x0018 (0x0010) [FString]
  Timeout: 0x0028n, // 0x0028 (0x0004) [float]
  bIsUnicode: 0x002cn, // 0x002c (0x0004) [bool : 0x1]
  HttpDownloader: 0x0030n, // 0x0030 (0x0008) [FPointer]
} as const;

/**
 * IpDrv.OnlineImageDownloaderWeb.OnlineImageDownload Offsets
 * Size: 0x0040
 */
export const FOnlineImageDownload = {
  URL: 0x0000n, // 0x0000 (0x0010) [FString]
  HTTPRequest: 0x0010n, // 0x0010 (0x0008) [UHttpRequestInterface*]
  Status: 0x0018n, // 0x0018 (0x0001) [EOnlineImageDownloadState]
  Texture: 0x0020n, // 0x0020 (0x0008) [UTexture2DDynamic*]
  DecodedCallbacks: 0x0028n, // 0x0028 (0x0018) [FScriptDelegate]
} as const;

/**
 * IpDrv.PartyBeacon.PartyReservation Offsets
 * Size: 0x0060
 */
export const FPartyReservation = {
  TeamNum: 0x0000n, // 0x0000 (0x0004) [int32]
  PartyLeader: 0x0008n, // 0x0008 (0x0048) [FUniqueNetId]
  PartyMembers: 0x0050n, // 0x0050 (0x0010) [TArray<FPlayerReservation>]
} as const;

/**
 * IpDrv.MeshBeacon.PlayerMember Offsets
 * Size: 0x0050
 */
export const FPlayerMember = {
  TeamNum: 0x0000n, // 0x0000 (0x0004) [int32]
  Skill: 0x0004n, // 0x0004 (0x0004) [int32]
  NetId: 0x0008n, // 0x0008 (0x0048) [FUniqueNetId]
} as const;

/**
 * IpDrv.PartyBeacon.PlayerReservation Offsets
 * Size: 0x0064
 */
export const FPlayerReservation = {
  NetId: 0x0000n, // 0x0000 (0x0048) [FUniqueNetId]
  Skill: 0x0048n, // 0x0048 (0x0004) [int32]
  XpLevel: 0x004cn, // 0x004c (0x0004) [int32]
  Mu: 0x0050n, // 0x0050 (0x0008) [FDouble]
  Sigma: 0x0058n, // 0x0058 (0x0008) [FDouble]
  ElapsedSessionTime: 0x0060n, // 0x0060 (0x0004) [float]
} as const;

/**
 * IpDrv.OnlinePlaylistManager.Playlist Offsets
 * Size: 0x0080
 */
export const FPlaylist = {
  ConfiguredGames: 0x0000n, // 0x0000 (0x0010) [TArray<FConfiguredGameSetting>]
  PlaylistId: 0x0010n, // 0x0010 (0x0004) [int32]
  LoadBalanceId: 0x0014n, // 0x0014 (0x0004) [int32]
  LocalizationString: 0x0018n, // 0x0018 (0x0010) [FString]
  ContentIds: 0x0028n, // 0x0028 (0x0010) [TArray<int32>]
  TeamSize: 0x0038n, // 0x0038 (0x0004) [int32]
  TeamCount: 0x003cn, // 0x003c (0x0004) [int32]
  MaxPartySize: 0x0040n, // 0x0040 (0x0004) [int32]
  Name: 0x0048n, // 0x0048 (0x0010) [FString]
  URL: 0x0058n, // 0x0058 (0x0010) [FString]
  MatchType: 0x0068n, // 0x0068 (0x0004) [int32]
  bDisableDedicatedServerSearches: 0x006cn, // 0x006c (0x0004) [bool : 0x1]
  MapCycle: 0x0070n, // 0x0070 (0x0010) [TArray<FName>]
} as const;

/**
 * IpDrv.OnlinePlaylistManager.PlaylistPopulation Offsets
 * Size: 0x000c
 */
export const FPlaylistPopulation = {
  PlaylistId: 0x0000n, // 0x0000 (0x0004) [int32]
  WorldwideTotal: 0x0004n, // 0x0004 (0x0004) [int32]
  RegionTotal: 0x0008n, // 0x0008 (0x0004) [int32]
} as const;

/**
 * IpDrv.McpIdMappingManager.QueryMappingRequest Offsets
 * Size: 0x0018
 */
export const FQueryMappingRequest = {
  ExternalType: 0x0000n, // 0x0000 (0x0010) [FString]
  Request: 0x0010n, // 0x0010 (0x0008) [UHttpRequestInterface*]
} as const;

/**
 * IpDrv.OnlineSubsystemCommonImpl.SanitizeCallbackData Offsets
 * Size: 0x0030
 */
export const FSanitizeCallbackData = {
  Id: 0x0000n, // 0x0000 (0x0004) [int32]
  Callback: 0x0008n, // 0x0008 (0x0018) [FScriptDelegate]
  Comment: 0x0020n, // 0x0020 (0x0010) [FString]
} as const;

/**
 * Engine.OnlineSubsystem.TitleFile Offsets
 * Size: 0x0028
 */
export const FTitleFile = {
  Filename: 0x0000n, // 0x0000 (0x0010) [FString]
  AsyncState: 0x0010n, // 0x0010 (0x0001) [EOnlineEnumerationReadState]
  Data: 0x0018n, // 0x0018 (0x0010) [TArray<uint8>]
} as const;

/**
 * IpDrv.TitleFileDownloadCache.TitleFileCacheEntry Offsets
 * Size: 0x0058
 * Extends: FTitleFile
 */
export const FTitleFileCacheEntry = {
  LogicalName: 0x0028n, // 0x0028 (0x0010) [FString]
  Hash: 0x0038n, // 0x0038 (0x0010) [FString]
  FileOp: 0x0048n, // 0x0048 (0x0001) [ETitleFileFileOp]
  Ar: 0x0050n, // 0x0050 (0x0008) [FPointer]
  ...FTitleFile,
} as const;

/**
 * IpDrv.OnlineTitleFileDownloadMcp.TitleFileMcp Offsets
 * Size: 0x0030
 * Extends: FTitleFile
 */
export const FTitleFileMcp = {
  HttpDownloader: 0x0028n, // 0x0028 (0x0008) [FPointer]
  ...FTitleFile,
} as const;

/**
 * IpDrv.OnlineTitleFileDownloadBase.TitleFileWeb Offsets
 * Size: 0x0041
 * Extends: FTitleFile
 */
export const FTitleFileWeb = {
  StringData: 0x0028n, // 0x0028 (0x0010) [FString]
  HTTPRequest: 0x0038n, // 0x0038 (0x0008) [UHttpRequestInterface*]
  FileCompressionType: 0x0040n, // 0x0040 (0x0001) [EMcpFileCompressionType]
  ...FTitleFile,
} as const;

/**
 * IpDrv.McpUserManager.UserRequest Offsets
 * Size: 0x0018
 */
export const FUserRequest = {
  McpId: 0x0000n, // 0x0000 (0x0010) [FString]
  Request: 0x0010n, // 0x0010 (0x0008) [UHttpRequestInterface*]
} as const;

/**
 * IpDrv.McpManagedValueManager.ValueRequestState Offsets
 * Size: 0x0030
 * Extends: FSaveSlotRequestState
 */
export const FValueRequestState = {
  ValueId: 0x0028n, // 0x0028 (0x0008) [FName]
  ...FSaveSlotRequestState,
} as const;

/**
 * IpDrv.WebApplication Offsets
 * Size: 0x0080
 * Extends: Object_
 */
export const WebApplication = {
  WorldInfo: 0x0060n, // 0x0060 (0x0008) [UWorldInfo*]
  WebServer: 0x0068n, // 0x0068 (0x0008) [UWebServer*]
  Path: 0x0070n, // 0x0070 (0x0010) [FString]
  ...Object_,
} as const;

/**
 * IpDrv.HelloWeb Offsets
 * Size: 0x0080
 * Extends: WebApplication
 */
export const HelloWeb = {
  ...WebApplication,
} as const;

/**
 * Engine.Download Offsets
 * Size: 0x0ab0
 * Extends: Object_
 */
export const Download = {
  ...Object_,
} as const;

/**
 * IpDrv.HTTPDownload Offsets
 * Size: 0x0bf0
 * Extends: Download
 */
export const HTTPDownload = {
  RedirectToURL: 0x0078n, // 0x0078 (0x0010) [FString]
  UseCompression: 0x0088n, // 0x0088 (0x0004) [bool : 0x1]
  ProxyServerHost: 0x0ab0n, // 0x0ab0 (0x0010) [FString]
  ProxyServerPort: 0x0ac0n, // 0x0ac0 (0x0004) [int32]
  MaxRedirection: 0x0ac4n, // 0x0ac4 (0x0004) [bool : 0x1]
  ConnectionTimeout: 0x0ac8n, // 0x0ac8 (0x0004) [float]
  ...Download,
} as const;

/**
 * Engine.HttpBaseInterface Offsets
 * Size: 0x0060
 * Extends: Object_
 */
export const HttpBaseInterface = {
  ...Object_,
} as const;

/**
 * Engine.HttpRequestInterface Offsets
 * Size: 0x0078
 * Extends: HttpBaseInterface
 */
export const HttpRequestInterface = {
  __OnProcessRequestComplete__Delegate: 0x0060n, // 0x0060 (0x0018) [FScriptDelegate]
  ...HttpBaseInterface,
} as const;

/**
 * IpDrv.HttpRequestCurl Offsets
 * Size: 0x00c0
 * Extends: HttpRequestInterface
 */
export const HttpRequestCurl = {
  Request: 0x0078n, // 0x0078 (0x0008) [FPointer]
  RequestVerb: 0x0080n, // 0x0080 (0x0010) [FString]
  RequestURL: 0x0090n, // 0x0090 (0x0010) [FString]
  Payload: 0x00a0n, // 0x00a0 (0x0010) [TArray<uint8>]
  AllowedRedirectURLs: 0x00b0n, // 0x00b0 (0x0010) [TArray<FString>]
  ...HttpRequestInterface,
} as const;

/**
 * Engine.HttpResponseInterface Offsets
 * Size: 0x0060
 * Extends: HttpBaseInterface
 */
export const HttpResponseInterface = {
  ...HttpBaseInterface,
} as const;

/**
 * IpDrv.HttpResponseCurl Offsets
 * Size: 0x0078
 * Extends: HttpResponseInterface
 */
export const HttpResponseCurl = {
  Response: 0x0060n, // 0x0060 (0x0008) [FPointer]
  Payload: 0x0068n, // 0x0068 (0x0010) [TArray<uint8>]
  ...HttpResponseInterface,
} as const;

/**
 * IpDrv.ImageDecoder Offsets
 * Size: 0x0090
 * Extends: Object_
 */
export const ImageDecoder = {
  VfTable_FTickableObject: 0x0060n, // 0x0060 (0x0008) [FPointer]
  ActiveDecodeRequests: 0x0068n, // 0x0068 (0x0010) [TArray<FDecodeImageRequest>]
  __ImageDecodedDelegate__Delegate: 0x0078n, // 0x0078 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.ImageServer Offsets
 * Size: 0x0080
 * Extends: WebApplication
 */
export const ImageServer = {
  ...WebApplication,
} as const;

/**
 * Engine.Actor Offsets
 * Size: 0x0268
 * Extends: Object_
 */
export const Actor = {
  ActorDependantPSCs: 0x0060n, // 0x0060 (0x0010) [TArray<UParticleSystemComponent*>]
  Components: 0x0070n, // 0x0070 (0x0010) [TArray<UActorComponent*>]
  AllComponents: 0x0080n, // 0x0080 (0x0010) [TArray<UActorComponent*>]
  Location: 0x0090n, // 0x0090 (0x000c) [FVector]
  Rotation: 0x009cn, // 0x009c (0x000c) [FRotator]
  DrawScale: 0x00a8n, // 0x00a8 (0x0004) [float]
  DrawScale3D: 0x00acn, // 0x00ac (0x000c) [FVector]
  PrePivot: 0x00b8n, // 0x00b8 (0x000c) [FVector]
  EditorIconColor: 0x00c4n, // 0x00c4 (0x0004) [FColor]
  HighContrastRenderingMode: 0x00c8n, // 0x00c8 (0x0001) [EHighContrastRenderingMode]
  Physics: 0x00c9n, // 0x00c9 (0x0001) [EPhysics]
  RemoteRole: 0x00can, // 0x00ca (0x0001) [ENetRole]
  Role: 0x00cbn, // 0x00cb (0x0001) [ENetRole]
  CollisionType: 0x00ccn, // 0x00cc (0x0001) [ECollisionType]
  ReplicatedCollisionType: 0x00cdn, // 0x00cd (0x0001) [ECollisionType]
  TickGroup: 0x00cen, // 0x00ce (0x0001) [ETickingGroup]
  DetachFence: 0x00d0n, // 0x00d0 (0x0004) [FRenderCommandFence]
  CustomTimeDilation: 0x00d4n, // 0x00d4 (0x0004) [float]
  Owner: 0x00d8n, // 0x00d8 (0x0008) [UActor*]
  Base: 0x00e0n, // 0x00e0 (0x0008) [UActor*]
  Timers: 0x00e8n, // 0x00e8 (0x0010) [TArray<FTimerData>]
  bStatic: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x1]
  bHidden: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x2]
  bHiddenSelf: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x4]
  bNoDelete: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x8]
  bDeleteMe: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x10]
  bTicked: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x20]
  bOnlyOwnerSee: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x40]
  bTickIsDisabled: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x80]
  bWorldGeometry: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x100]
  bIgnoreRigidBodyPawns: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x200]
  bOrientOnSlope: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x400]
  bIgnoreEncroachers: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x800]
  bPushedByEncroachers: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x1000]
  bDestroyedByInterpActor: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x2000]
  bRouteBeginPlayEvenIfStatic: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x4000]
  bIsMoving: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x8000]
  bAlwaysEncroachCheck: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x10000]
  bHasAlternateTargetLocation: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x20000]
  bCanStepUpOn: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x40000]
  bNetTemporary: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x80000]
  bOnlyRelevantToOwner: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x100000]
  bNetDirty: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x200000]
  bAlwaysRelevant: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x400000]
  bReplicateInstigator: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x800000]
  bReplicateMovement: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x1000000]
  bSkipActorPropertyReplication: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x2000000]
  bUpdateSimulatedPosition: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x4000000]
  bTearOff: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x8000000]
  bOnlyDirtyReplication: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x10000000]
  bAllowFluidSurfaceInteraction: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x20000000]
  bDemoRecording: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x40000000]
  bDemoOwner: 0x00f8n, // 0x00f8 (0x0004) [bool : 0x80000000]
  bForceDemoRelevant: 0x00fcn, // 0x00fc (0x0004) [bool : 0x1]
  bNetInitialRotation: 0x00fcn, // 0x00fc (0x0004) [bool : 0x2]
  bReplicateRigidBodyLocation: 0x00fcn, // 0x00fc (0x0004) [bool : 0x4]
  bKillDuringLevelTransition: 0x00fcn, // 0x00fc (0x0004) [bool : 0x8]
  bExchangedRoles: 0x00fcn, // 0x00fc (0x0004) [bool : 0x10]
  bConsiderAllStaticMeshComponentsForStreaming: 0x00fcn, // 0x00fc (0x0004) [bool : 0x20]
  bDebug: 0x00fcn, // 0x00fc (0x0004) [bool : 0x40]
  bPostRenderIfNotVisible: 0x00fcn, // 0x00fc (0x0004) [bool : 0x80]
  bForceNetUpdate: 0x00fcn, // 0x00fc (0x0004) [bool : 0x100]
  bForcePacketUpdate: 0x00fcn, // 0x00fc (0x0004) [bool : 0x200]
  bPendingNetUpdate: 0x00fcn, // 0x00fc (0x0004) [bool : 0x400]
  bHardAttach: 0x00fcn, // 0x00fc (0x0004) [bool : 0x800]
  bIgnoreBaseRotation: 0x00fcn, // 0x00fc (0x0004) [bool : 0x1000]
  bShadowParented: 0x00fcn, // 0x00fc (0x0004) [bool : 0x2000]
  bSkipAttachedMoves: 0x00fcn, // 0x00fc (0x0004) [bool : 0x4000]
  bCanBeAdheredTo: 0x00fcn, // 0x00fc (0x0004) [bool : 0x8000]
  bCanBeFrictionedTo: 0x00fcn, // 0x00fc (0x0004) [bool : 0x10000]
  bGameRelevant: 0x00fcn, // 0x00fc (0x0004) [bool : 0x20000]
  bMovable: 0x00fcn, // 0x00fc (0x0004) [bool : 0x40000]
  bShouldBaseAtStartup: 0x00fcn, // 0x00fc (0x0004) [bool : 0x80000]
  bPendingDelete: 0x00fcn, // 0x00fc (0x0004) [bool : 0x100000]
  bCanTeleport: 0x00fcn, // 0x00fc (0x0004) [bool : 0x200000]
  bAlwaysTick: 0x00fcn, // 0x00fc (0x0004) [bool : 0x400000]
  bBlocksNavigation: 0x00fcn, // 0x00fc (0x0004) [bool : 0x800000]
  BlockRigidBody: 0x00fcn, // 0x00fc (0x0004) [bool : 0x1000000]
  bCollideWhenPlacing: 0x00fcn, // 0x00fc (0x0004) [bool : 0x2000000]
  bCollideActors: 0x00fcn, // 0x00fc (0x0004) [bool : 0x4000000]
  bCollideWorld: 0x00fcn, // 0x00fc (0x0004) [bool : 0x8000000]
  bCollideComplex: 0x00fcn, // 0x00fc (0x0004) [bool : 0x10000000]
  bBlockActors: 0x00fcn, // 0x00fc (0x0004) [bool : 0x20000000]
  bBlocksTeleport: 0x00fcn, // 0x00fc (0x0004) [bool : 0x40000000]
  bMoveIgnoresDestruction: 0x00fcn, // 0x00fc (0x0004) [bool : 0x80000000]
  bProjectileMoveSingleBlocking: 0x0100n, // 0x0100 (0x0004) [bool : 0x1]
  bNoEncroachCheck: 0x0100n, // 0x0100 (0x0004) [bool : 0x2]
  bCollideAsEncroacher: 0x0100n, // 0x0100 (0x0004) [bool : 0x4]
  bPhysRigidBodyOutOfWorldCheck: 0x0100n, // 0x0100 (0x0004) [bool : 0x8]
  bComponentOutsideWorld: 0x0100n, // 0x0100 (0x0004) [bool : 0x10]
  bForceOctreeSNFilter: 0x0100n, // 0x0100 (0x0004) [bool : 0x20]
  bForceOctreeMNFilter: 0x0100n, // 0x0100 (0x0004) [bool : 0x40]
  bRigidBodyWasAwake: 0x0100n, // 0x0100 (0x0004) [bool : 0x80]
  bCallRigidBodyWakeEvents: 0x0100n, // 0x0100 (0x0004) [bool : 0x100]
  bBounce: 0x0100n, // 0x0100 (0x0004) [bool : 0x200]
  bJustTeleported: 0x0100n, // 0x0100 (0x0004) [bool : 0x400]
  bEnableMobileTouch: 0x0100n, // 0x0100 (0x0004) [bool : 0x800]
  bNetInitial: 0x0100n, // 0x0100 (0x0004) [bool : 0x1000]
  bNetOwner: 0x0100n, // 0x0100 (0x0004) [bool : 0x2000]
  bHiddenEd: 0x0100n, // 0x0100 (0x0004) [bool : 0x4000]
  bEditable: 0x0100n, // 0x0100 (0x0004) [bool : 0x8000]
  bHiddenEdGroup: 0x0100n, // 0x0100 (0x0004) [bool : 0x10000]
  bHiddenEdLayer: 0x0100n, // 0x0100 (0x0004) [bool : 0x20000]
  bHiddenEdCustom: 0x0100n, // 0x0100 (0x0004) [bool : 0x40000]
  bHiddenEdTemporary: 0x0100n, // 0x0100 (0x0004) [bool : 0x80000]
  bHiddenEdLevel: 0x0100n, // 0x0100 (0x0004) [bool : 0x100000]
  bHiddenEdScene: 0x0100n, // 0x0100 (0x0004) [bool : 0x200000]
  bHiddenEdNoPhysics: 0x0100n, // 0x0100 (0x0004) [bool : 0x400000]
  bEdShouldSnap: 0x0100n, // 0x0100 (0x0004) [bool : 0x800000]
  bTempEditor: 0x0100n, // 0x0100 (0x0004) [bool : 0x1000000]
  bPathColliding: 0x0100n, // 0x0100 (0x0004) [bool : 0x2000000]
  bPathTemp: 0x0100n, // 0x0100 (0x0004) [bool : 0x4000000]
  bScriptInitialized: 0x0100n, // 0x0100 (0x0004) [bool : 0x8000000]
  bLockLocation: 0x0100n, // 0x0100 (0x0004) [bool : 0x10000000]
  bForceAllowKismetModification: 0x0100n, // 0x0100 (0x0004) [bool : 0x20000000]
  bDedicatedServerRelevant: 0x0100n, // 0x0100 (0x0004) [bool : 0x40000000]
  bLockedFromEditorDeletion: 0x0100n, // 0x0100 (0x0004) [bool : 0x80000000]
  bComponentsDirty: 0x0104n, // 0x0104 (0x0004) [bool : 0x1]
  bUpdateComponentsIfEmpty: 0x0104n, // 0x0104 (0x0004) [bool : 0x2]
  bDebugEffectIsRelevant: 0x0104n, // 0x0104 (0x0004) [bool : 0x4]
  SkelMeshCompTickTag: 0x0108n, // 0x0108 (0x0004) [int32]
  NetTag: 0x010cn, // 0x010c (0x0004) [int32]
  NetUpdateTime: 0x0110n, // 0x0110 (0x0004) [float]
  NetUpdateFrequency: 0x0114n, // 0x0114 (0x0004) [float]
  NetPriority: 0x0118n, // 0x0118 (0x0004) [float]
  LastNetUpdateTime: 0x011cn, // 0x011c (0x0004) [float]
  LastForcePacketUpdateTime: 0x0120n, // 0x0120 (0x0004) [float]
  TimeSinceLastTick: 0x0124n, // 0x0124 (0x0004) [float]
  Instigator: 0x0128n, // 0x0128 (0x0008) [UPawn*]
  WorldInfo: 0x0130n, // 0x0130 (0x0008) [UWorldInfo*]
  LifeSpan: 0x0138n, // 0x0138 (0x0004) [float]
  CreationTime: 0x013cn, // 0x013c (0x0004) [float]
  LastRenderTime: 0x0140n, // 0x0140 (0x0004) [float]
  Tag: 0x0144n, // 0x0144 (0x0008) [FName]
  InitialState: 0x014cn, // 0x014c (0x0008) [FName]
  Layer: 0x0154n, // 0x0154 (0x0008) [FName]
  Group: 0x015cn, // 0x015c (0x0008) [FName]
  HiddenEditorViews: 0x0168n, // 0x0168 (0x0008) [uint64]
  Touching: 0x0170n, // 0x0170 (0x0010) [TArray<UActor*>]
  Children: 0x0180n, // 0x0180 (0x0010) [TArray<UActor*>]
  LatentFloat: 0x0190n, // 0x0190 (0x0004) [float]
  LatentSeqNode: 0x0198n, // 0x0198 (0x0008) [UAnimNodeSequence*]
  PhysicsVolume: 0x01a0n, // 0x01a0 (0x0008) [UPhysicsVolume*]
  Velocity: 0x01a8n, // 0x01a8 (0x000c) [FVector]
  Acceleration: 0x01b4n, // 0x01b4 (0x000c) [FVector]
  AngularVelocity: 0x01c0n, // 0x01c0 (0x000c) [FVector]
  BaseSkelComponent: 0x01d0n, // 0x01d0 (0x0008) [USkeletalMeshComponent*]
  BaseBoneName: 0x01d8n, // 0x01d8 (0x0008) [FName]
  Attached: 0x01e0n, // 0x01e0 (0x0010) [TArray<UActor*>]
  RelativeLocation: 0x01f0n, // 0x01f0 (0x000c) [FVector]
  RelativeRotation: 0x01fcn, // 0x01fc (0x000c) [FRotator]
  CollisionComponent: 0x0208n, // 0x0208 (0x0008) [UPrimitiveComponent*]
  OverlapTag: 0x0210n, // 0x0210 (0x0004) [int32]
  RotationRate: 0x0214n, // 0x0214 (0x000c) [FRotator]
  PendingTouch: 0x0220n, // 0x0220 (0x0008) [UActor*]
  SupportedEvents: 0x0228n, // 0x0228 (0x0010) [TArray<USequenceEvent*>]
  GeneratedEvents: 0x0238n, // 0x0238 (0x0010) [TArray<USequenceEvent*>]
  LatentActions: 0x0248n, // 0x0248 (0x0010) [TArray<USeqAct_Latent*>]
  IgnoredTouchClasses: 0x0258n, // 0x0258 (0x0010) [TArray<UActor*>]
  ...Object_,
} as const;

/**
 * Engine.Info Offsets
 * Size: 0x0268
 * Extends: Actor
 */
export const Info = {
  ...Actor,
} as const;

/**
 * IpDrv.InternetLink Offsets
 * Size: 0x0294
 * Extends: Info
 */
export const InternetLink = {
  LinkMode: 0x0268n, // 0x0268 (0x0001) [ELinkMode]
  InLineMode: 0x0269n, // 0x0269 (0x0001) [ELineMode]
  OutLineMode: 0x026an, // 0x026a (0x0001) [ELineMode]
  ReceiveMode: 0x026bn, // 0x026b (0x0001) [EReceiveMode]
  Socket: 0x0270n, // 0x0270 (0x0008) [FPointer]
  Port: 0x0278n, // 0x0278 (0x0004) [int32]
  RemoteSocket: 0x0280n, // 0x0280 (0x0008) [FPointer]
  PrivateResolveInfo: 0x0288n, // 0x0288 (0x0008) [FPointer]
  DataPending: 0x0290n, // 0x0290 (0x0004) [int32]
  ...Info,
} as const;

/**
 * IpDrv.McpServiceBase Offsets
 * Size: 0x0078
 * Extends: Object_
 */
export const McpServiceBase = {
  McpConfigClassName: 0x0060n, // 0x0060 (0x0010) [FString]
  McpConfig: 0x0070n, // 0x0070 (0x0008) [UMcpServiceConfig*]
  ...Object_,
} as const;

/**
 * IpDrv.MCPBase Offsets
 * Size: 0x0080
 * Extends: McpServiceBase
 */
export const MCPBase = {
  VfTable_FTickableObject: 0x0078n, // 0x0078 (0x0008) [FPointer]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpClashMobBase Offsets
 * Size: 0x0118
 * Extends: McpServiceBase
 */
export const McpClashMobBase = {
  McpClashMobClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  __OnQueryChallengeListComplete__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __OnDownloadChallengeFileComplete__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  __OnAcceptChallengeComplete__Delegate: 0x00b8n, // 0x00b8 (0x0018) [FScriptDelegate]
  __OnQueryChallengeUserStatusComplete__Delegate: 0x00d0n, // 0x00d0 (0x0018) [FScriptDelegate]
  __OnUpdateChallengeUserProgressComplete__Delegate: 0x00e8n, // 0x00e8 (0x0018) [FScriptDelegate]
  __OnUpdateChallengeUserRewardComplete__Delegate: 0x0100n, // 0x0100 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.OnlineTitleFileDownloadBase Offsets
 * Size: 0x0118
 * Extends: MCPBase
 */
export const OnlineTitleFileDownloadBase = {
  ReadTitleFileCompleteDelegates: 0x0080n, // 0x0080 (0x0010) [TArray<FScriptDelegate>]
  RequestTitleFileListCompleteDelegates: 0x0090n, // 0x0090 (0x0010) [TArray<FScriptDelegate>]
  BaseUrl: 0x00a0n, // 0x00a0 (0x0010) [FString]
  RequestFileListURL: 0x00b0n, // 0x00b0 (0x0010) [FString]
  RequestFileURL: 0x00c0n, // 0x00c0 (0x0010) [FString]
  Timeout: 0x00d0n, // 0x00d0 (0x0004) [float]
  FilesToUrls: 0x00d8n, // 0x00d8 (0x0010) [TArray<FFileNameToURLMapping>]
  __OnReadTitleFileComplete__Delegate: 0x00e8n, // 0x00e8 (0x0018) [FScriptDelegate]
  __OnRequestTitleFileListComplete__Delegate: 0x0100n, // 0x0100 (0x0018) [FScriptDelegate]
  ...MCPBase,
} as const;

/**
 * IpDrv.OnlineTitleFileDownloadWeb Offsets
 * Size: 0x0128
 * Extends: OnlineTitleFileDownloadBase
 */
export const OnlineTitleFileDownloadWeb = {
  TitleFiles: 0x0118n, // 0x0118 (0x0010) [TArray<FTitleFileWeb>]
  ...OnlineTitleFileDownloadBase,
} as const;

/**
 * IpDrv.McpClashMobFileDownload Offsets
 * Size: 0x0128
 * Extends: OnlineTitleFileDownloadWeb
 */
export const McpClashMobFileDownload = {
  ...OnlineTitleFileDownloadWeb,
} as const;

/**
 * IpDrv.McpClashMobManager Offsets
 * Size: 0x0268
 * Extends: McpClashMobBase
 */
export const McpClashMobManager = {
  ChallengeListUrl: 0x0118n, // 0x0118 (0x0010) [FString]
  ChallengeStatusUrl: 0x0128n, // 0x0128 (0x0010) [FString]
  ChallengeMultiStatusUrl: 0x0138n, // 0x0138 (0x0010) [FString]
  AcceptChallengeUrl: 0x0148n, // 0x0148 (0x0010) [FString]
  UpdateChallengeProgressUrl: 0x0158n, // 0x0158 (0x0010) [FString]
  UpdateRewardProgressUrl: 0x0168n, // 0x0168 (0x0010) [FString]
  HTTPRequestChallengeList: 0x0178n, // 0x0178 (0x0008) [UHttpRequestInterface*]
  ChallengeUserRequests: 0x0180n, // 0x0180 (0x0010) [TArray<FMcpChallengeUserRequest>]
  ChallengeEvents: 0x0190n, // 0x0190 (0x0010) [TArray<FMcpClashMobChallengeEvent>]
  ChallengeUserStatus: 0x01a0n, // 0x01a0 (0x0010) [TArray<FMcpClashMobChallengeUserStatus>]
  TempChallengeUserStatus: 0x01b0n, // 0x01b0 (0x0090) [FMcpClashMobChallengeUserStatus]
  TempChallengeUserStatusArray: 0x0240n, // 0x0240 (0x0010) [TArray<FMcpClashMobChallengeUserStatus>]
  FileCache: 0x0250n, // 0x0250 (0x0010) [UOnlineTitleFileCacheInterface*]
  FileDownloader: 0x0260n, // 0x0260 (0x0008) [UMcpClashMobFileDownload*]
  ...McpClashMobBase,
} as const;

/**
 * IpDrv.McpGroupsBase Offsets
 * Size: 0x0170
 * Extends: McpServiceBase
 */
export const McpGroupsBase = {
  McpGroupsManagerClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  GroupLists: 0x0088n, // 0x0088 (0x0010) [TArray<FMcpGroupList>]
  __OnCreateGroupComplete__Delegate: 0x0098n, // 0x0098 (0x0018) [FScriptDelegate]
  __OnDeleteGroupComplete__Delegate: 0x00b0n, // 0x00b0 (0x0018) [FScriptDelegate]
  __OnQueryGroupsComplete__Delegate: 0x00c8n, // 0x00c8 (0x0018) [FScriptDelegate]
  __OnQueryGroupMembersComplete__Delegate: 0x00e0n, // 0x00e0 (0x0018) [FScriptDelegate]
  __OnAddGroupMembersComplete__Delegate: 0x00f8n, // 0x00f8 (0x0018) [FScriptDelegate]
  __OnRemoveGroupMembersComplete__Delegate: 0x0110n, // 0x0110 (0x0018) [FScriptDelegate]
  __OnDeleteAllGroupsComplete__Delegate: 0x0128n, // 0x0128 (0x0018) [FScriptDelegate]
  __OnQueryGroupInvitesComplete__Delegate: 0x0140n, // 0x0140 (0x0018) [FScriptDelegate]
  __OnAcceptGroupInviteComplete__Delegate: 0x0158n, // 0x0158 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpGroupsManager Offsets
 * Size: 0x0260
 * Extends: McpGroupsBase
 */
export const McpGroupsManager = {
  CreateGroupUrl: 0x0170n, // 0x0170 (0x0010) [FString]
  DeleteGroupUrl: 0x0180n, // 0x0180 (0x0010) [FString]
  QueryGroupsUrl: 0x0190n, // 0x0190 (0x0010) [FString]
  QueryGroupMembersUrl: 0x01a0n, // 0x01a0 (0x0010) [FString]
  AddGroupMembersUrl: 0x01b0n, // 0x01b0 (0x0010) [FString]
  RemoveGroupMembersUrl: 0x01c0n, // 0x01c0 (0x0010) [FString]
  DeleteAllGroupsUrl: 0x01d0n, // 0x01d0 (0x0010) [FString]
  AcceptGroupInviteUrl: 0x01e0n, // 0x01e0 (0x0010) [FString]
  RejectGroupInviteUrl: 0x01f0n, // 0x01f0 (0x0010) [FString]
  __OnQueryGroupsRequestComplete__Delegate: 0x0200n, // 0x0200 (0x0018) [FScriptDelegate]
  __OnQueryGroupMembersRequestComplete__Delegate: 0x0218n, // 0x0218 (0x0018) [FScriptDelegate]
  __OnAddGroupMembersRequestComplete__Delegate: 0x0230n, // 0x0230 (0x0018) [FScriptDelegate]
  __OnAcceptGroupInviteRequestComplete__Delegate: 0x0248n, // 0x0248 (0x0018) [FScriptDelegate]
  ...McpGroupsBase,
} as const;

/**
 * IpDrv.McpIdMappingBase Offsets
 * Size: 0x00b8
 * Extends: McpServiceBase
 */
export const McpIdMappingBase = {
  McpIdMappingClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  __OnAddMappingComplete__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __OnQueryMappingsComplete__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpIdMappingManager Offsets
 * Size: 0x0108
 * Extends: McpIdMappingBase
 */
export const McpIdMappingManager = {
  AccountMappings: 0x00b8n, // 0x00b8 (0x0010) [TArray<FMcpIdMapping>]
  AddMappingUrl: 0x00c8n, // 0x00c8 (0x0010) [FString]
  QueryMappingUrl: 0x00d8n, // 0x00d8 (0x0010) [FString]
  AddMappingRequests: 0x00e8n, // 0x00e8 (0x0010) [TArray<FAddMappingRequest>]
  QueryMappingRequests: 0x00f8n, // 0x00f8 (0x0010) [TArray<FQueryMappingRequest>]
  ...McpIdMappingBase,
} as const;

/**
 * IpDrv.McpManagedValueManagerBase Offsets
 * Size: 0x00e8
 * Extends: McpServiceBase
 */
export const McpManagedValueManagerBase = {
  McpManagedValueManagerClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  __OnCreateSaveSlotComplete__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __OnReadSaveSlotComplete__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  __OnUpdateValueComplete__Delegate: 0x00b8n, // 0x00b8 (0x0018) [FScriptDelegate]
  __OnDeleteValueComplete__Delegate: 0x00d0n, // 0x00d0 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpManagedValueManager Offsets
 * Size: 0x0178
 * Extends: McpManagedValueManagerBase
 */
export const McpManagedValueManager = {
  CreateSaveSlotUrl: 0x00e8n, // 0x00e8 (0x0010) [FString]
  ReadSaveSlotUrl: 0x00f8n, // 0x00f8 (0x0010) [FString]
  UpdateValueUrl: 0x0108n, // 0x0108 (0x0010) [FString]
  DeleteValueUrl: 0x0118n, // 0x0118 (0x0010) [FString]
  SaveSlots: 0x0128n, // 0x0128 (0x0010) [TArray<FManagedValueSaveSlot>]
  CreateSaveSlotRequests: 0x0138n, // 0x0138 (0x0010) [TArray<FSaveSlotRequestState>]
  ReadSaveSlotRequests: 0x0148n, // 0x0148 (0x0010) [TArray<FSaveSlotRequestState>]
  UpdateValueRequests: 0x0158n, // 0x0158 (0x0010) [TArray<FValueRequestState>]
  DeleteValueRequests: 0x0168n, // 0x0168 (0x0010) [TArray<FValueRequestState>]
  ...McpManagedValueManagerBase,
} as const;

/**
 * IpDrv.McpMessageBase Offsets
 * Size: 0x0110
 * Extends: McpServiceBase
 */
export const McpMessageBase = {
  McpMessageManagerClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  CompressionType: 0x0088n, // 0x0088 (0x0001) [EMcpMessageCompressionType]
  MessageContentsList: 0x0090n, // 0x0090 (0x0010) [TArray<FMcpMessageContents>]
  MessageLists: 0x00a0n, // 0x00a0 (0x0010) [TArray<FMcpMessageList>]
  __OnCreateMessageComplete__Delegate: 0x00b0n, // 0x00b0 (0x0018) [FScriptDelegate]
  __OnDeleteMessageComplete__Delegate: 0x00c8n, // 0x00c8 (0x0018) [FScriptDelegate]
  __OnQueryMessagesComplete__Delegate: 0x00e0n, // 0x00e0 (0x0018) [FScriptDelegate]
  __OnQueryMessageContentsComplete__Delegate: 0x00f8n, // 0x00f8 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpMessageManager Offsets
 * Size: 0x0188
 * Extends: McpMessageBase
 */
export const McpMessageManager = {
  VfTable_FTickableObject: 0x0110n, // 0x0110 (0x0008) [FPointer]
  CreateMessageUrl: 0x0118n, // 0x0118 (0x0010) [FString]
  DeleteMessageUrl: 0x0128n, // 0x0128 (0x0010) [FString]
  QueryMessagesUrl: 0x0138n, // 0x0138 (0x0010) [FString]
  QueryMessageContentsUrl: 0x0148n, // 0x0148 (0x0010) [FString]
  DeleteAllMessagesUrl: 0x0158n, // 0x0158 (0x0010) [FString]
  CompressMessageRequests: 0x0168n, // 0x0168 (0x0010) [TArray<FMcpCompressMessageRequest>]
  UncompressMessageRequests: 0x0178n, // 0x0178 (0x0010) [TArray<FMcpUncompressMessageRequest>]
  ...McpMessageBase,
} as const;

/**
 * IpDrv.McpServerTimeBase Offsets
 * Size: 0x00a0
 * Extends: McpServiceBase
 */
export const McpServerTimeBase = {
  McpServerTimeClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  __OnQueryServerTimeComplete__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpServerTimeManager Offsets
 * Size: 0x00c8
 * Extends: McpServerTimeBase
 */
export const McpServerTimeManager = {
  TimeStampUrl: 0x00a0n, // 0x00a0 (0x0010) [FString]
  LastTimeStamp: 0x00b0n, // 0x00b0 (0x0010) [FString]
  HTTPRequestServerTime: 0x00c0n, // 0x00c0 (0x0008) [UHttpRequestInterface*]
  ...McpServerTimeBase,
} as const;

/**
 * IpDrv.McpServiceConfig Offsets
 * Size: 0x00a0
 * Extends: Object_
 */
export const McpServiceConfig = {
  Protocol: 0x0060n, // 0x0060 (0x0010) [FString]
  Domain: 0x0070n, // 0x0070 (0x0010) [FString]
  AppKey: 0x0080n, // 0x0080 (0x0010) [FString]
  AppSecret: 0x0090n, // 0x0090 (0x0010) [FString]
  ...Object_,
} as const;

/**
 * IpDrv.McpUserCloudFileDownload Offsets
 * Size: 0x0168
 * Extends: McpServiceBase
 */
export const McpUserCloudFileDownload = {
  EnumerateCloudFilesUrl: 0x0078n, // 0x0078 (0x0010) [FString]
  ReadCloudFileUrl: 0x0088n, // 0x0088 (0x0010) [FString]
  WriteCloudFileUrl: 0x0098n, // 0x0098 (0x0010) [FString]
  DeleteCloudFileUrl: 0x00a8n, // 0x00a8 (0x0010) [FString]
  UserCloudFileRequests: 0x00b8n, // 0x00b8 (0x0010) [TArray<FMcpUserCloudFilesEntry>]
  EnumerateUserFilesCompleteDelegates: 0x00c8n, // 0x00c8 (0x0010) [TArray<FScriptDelegate>]
  ReadUserFileCompleteDelegates: 0x00d8n, // 0x00d8 (0x0010) [TArray<FScriptDelegate>]
  WriteUserFileCompleteDelegates: 0x00e8n, // 0x00e8 (0x0010) [TArray<FScriptDelegate>]
  DeleteUserFileCompleteDelegates: 0x00f8n, // 0x00f8 (0x0010) [TArray<FScriptDelegate>]
  __OnEnumerateUserFilesComplete__Delegate: 0x0108n, // 0x0108 (0x0018) [FScriptDelegate]
  __OnReadUserFileComplete__Delegate: 0x0120n, // 0x0120 (0x0018) [FScriptDelegate]
  __OnWriteUserFileComplete__Delegate: 0x0138n, // 0x0138 (0x0018) [FScriptDelegate]
  __OnDeleteUserFileComplete__Delegate: 0x0150n, // 0x0150 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpUserInventoryBase Offsets
 * Size: 0x0178
 * Extends: McpServiceBase
 */
export const McpUserInventoryBase = {
  McpUserInventoryClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  __OnCreateSaveSlotComplete__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __OnDeleteSaveSlotComplete__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  __OnQuerySaveSlotListComplete__Delegate: 0x00b8n, // 0x00b8 (0x0018) [FScriptDelegate]
  __OnQueryInventoryItemsComplete__Delegate: 0x00d0n, // 0x00d0 (0x0018) [FScriptDelegate]
  __OnPurchaseItemComplete__Delegate: 0x00e8n, // 0x00e8 (0x0018) [FScriptDelegate]
  __OnSellItemComplete__Delegate: 0x0100n, // 0x0100 (0x0018) [FScriptDelegate]
  __OnEarnItemComplete__Delegate: 0x0118n, // 0x0118 (0x0018) [FScriptDelegate]
  __OnConsumeItemComplete__Delegate: 0x0130n, // 0x0130 (0x0018) [FScriptDelegate]
  __OnDeleteItemComplete__Delegate: 0x0148n, // 0x0148 (0x0018) [FScriptDelegate]
  __OnRecordIapComplete__Delegate: 0x0160n, // 0x0160 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpUserInventoryManager Offsets
 * Size: 0x0268
 * Extends: McpUserInventoryBase
 */
export const McpUserInventoryManager = {
  CreateSaveSlotUrl: 0x0178n, // 0x0178 (0x0010) [FString]
  DeleteSaveSlotUrl: 0x0188n, // 0x0188 (0x0010) [FString]
  ListSaveSlotUrl: 0x0198n, // 0x0198 (0x0010) [FString]
  ListItemsUrl: 0x01a8n, // 0x01a8 (0x0010) [FString]
  PurchaseItemUrl: 0x01b8n, // 0x01b8 (0x0010) [FString]
  SellItemUrl: 0x01c8n, // 0x01c8 (0x0010) [FString]
  EarnItemUrl: 0x01d8n, // 0x01d8 (0x0010) [FString]
  ConsumeItemUrl: 0x01e8n, // 0x01e8 (0x0010) [FString]
  DeleteItemUrl: 0x01f8n, // 0x01f8 (0x0010) [FString]
  IapRecordUrl: 0x0208n, // 0x0208 (0x0010) [FString]
  SaveSlots: 0x0218n, // 0x0218 (0x0010) [TArray<FMcpInventorySaveSlot>]
  SaveSlotRequests: 0x0228n, // 0x0228 (0x0010) [TArray<FSaveSlotRequestState>]
  ListSaveSlotRequests: 0x0238n, // 0x0238 (0x0010) [TArray<FSaveSlotRequestState>]
  ListItemsRequests: 0x0248n, // 0x0248 (0x0010) [TArray<FSaveSlotRequestState>]
  ItemRequests: 0x0258n, // 0x0258 (0x0010) [TArray<FInventoryItemRequestState>]
  ...McpUserInventoryBase,
} as const;

/**
 * IpDrv.McpUserManagerBase Offsets
 * Size: 0x00e8
 * Extends: McpServiceBase
 */
export const McpUserManagerBase = {
  McpUserManagerClassName: 0x0078n, // 0x0078 (0x0010) [FString]
  __OnRegisterUserComplete__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __OnAuthenticateUserComplete__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  __OnQueryUsersComplete__Delegate: 0x00b8n, // 0x00b8 (0x0018) [FScriptDelegate]
  __OnDeleteUserComplete__Delegate: 0x00d0n, // 0x00d0 (0x0018) [FScriptDelegate]
  ...McpServiceBase,
} as const;

/**
 * IpDrv.McpUserManager Offsets
 * Size: 0x01a8
 * Extends: McpUserManagerBase
 */
export const McpUserManager = {
  UserStatuses: 0x00e8n, // 0x00e8 (0x0010) [TArray<FMcpUserStatus>]
  RegisterUserMcpUrl: 0x00f8n, // 0x00f8 (0x0010) [FString]
  RegisterUserFacebookUrl: 0x0108n, // 0x0108 (0x0010) [FString]
  QueryUserUrl: 0x0118n, // 0x0118 (0x0010) [FString]
  QueryUsersUrl: 0x0128n, // 0x0128 (0x0010) [FString]
  DeleteUserUrl: 0x0138n, // 0x0138 (0x0010) [FString]
  FacebookAuthUrl: 0x0148n, // 0x0148 (0x0010) [FString]
  McpAuthUrl: 0x0158n, // 0x0158 (0x0010) [FString]
  RegisterUserRequests: 0x0168n, // 0x0168 (0x0010) [TArray<UHttpRequestInterface*>]
  QueryUsersRequests: 0x0178n, // 0x0178 (0x0010) [TArray<UHttpRequestInterface*>]
  DeleteUserRequests: 0x0188n, // 0x0188 (0x0010) [TArray<FUserRequest>]
  AuthUserRequests: 0x0198n, // 0x0198 (0x0010) [TArray<UHttpRequestInterface*>]
  ...McpUserManagerBase,
} as const;

/**
 * IpDrv.MeshBeacon Offsets
 * Size: 0x00a8
 * Extends: Object_
 */
export const MeshBeacon = {
  VfTable_FTickableObject: 0x0060n, // 0x0060 (0x0008) [FPointer]
  MeshBeaconPort: 0x0068n, // 0x0068 (0x0004) [int32]
  Socket: 0x0070n, // 0x0070 (0x0008) [FPointer]
  bIsInTick: 0x0078n, // 0x0078 (0x0004) [bool : 0x1]
  bWantsDeferredDestroy: 0x0078n, // 0x0078 (0x0004) [bool : 0x2]
  bShouldTick: 0x0078n, // 0x0078 (0x0004) [bool : 0x4]
  HeartbeatTimeout: 0x007cn, // 0x007c (0x0004) [float]
  ElapsedHeartbeatTime: 0x0080n, // 0x0080 (0x0004) [float]
  BeaconName: 0x0084n, // 0x0084 (0x0008) [FName]
  SocketSendBufferSize: 0x008cn, // 0x008c (0x0004) [int32]
  SocketReceiveBufferSize: 0x0090n, // 0x0090 (0x0004) [int32]
  MaxBandwidthTestBufferSize: 0x0094n, // 0x0094 (0x0004) [int32]
  MinBandwidthTestBufferSize: 0x0098n, // 0x0098 (0x0004) [int32]
  MaxBandwidthTestSendTime: 0x009cn, // 0x009c (0x0004) [float]
  MaxBandwidthTestReceiveTime: 0x00a0n, // 0x00a0 (0x0004) [float]
  MaxBandwidthHistoryEntries: 0x00a4n, // 0x00a4 (0x0004) [int32]
  ...Object_,
} as const;

/**
 * IpDrv.MeshBeaconClient Offsets
 * Size: 0x01e8
 * Extends: MeshBeacon
 */
export const MeshBeaconClient = {
  HostPendingRequest: 0x00a8n, // 0x00a8 (0x0010) [FOnlineGameSearchResult]
  ClientPendingRequest: 0x00b8n, // 0x00b8 (0x0070) [FClientConnectionRequest]
  CurrentBandwidthTest: 0x0128n, // 0x0128 (0x0014) [FClientBandwidthTestData]
  ClientBeaconState: 0x013cn, // 0x013c (0x0001) [EMeshBeaconClientState]
  ClientBeaconRequestType: 0x013dn, // 0x013d (0x0001) [EMeshBeaconPacketType]
  ConnectionRequestTimeout: 0x0140n, // 0x0140 (0x0004) [float]
  ConnectionRequestElapsedTime: 0x0144n, // 0x0144 (0x0004) [float]
  ResolverClassName: 0x0148n, // 0x0148 (0x0010) [FString]
  ResolverClass: 0x0158n, // 0x0158 (0x0008) [UClientBeaconAddressResolver*]
  Resolver: 0x0160n, // 0x0160 (0x0008) [UClientBeaconAddressResolver*]
  bUsingRegisteredAddr: 0x0168n, // 0x0168 (0x0004) [bool : 0x1]
  __OnConnectionRequestResult__Delegate: 0x0170n, // 0x0170 (0x0018) [FScriptDelegate]
  __OnReceivedBandwidthTestRequest__Delegate: 0x0188n, // 0x0188 (0x0018) [FScriptDelegate]
  __OnReceivedBandwidthTestResults__Delegate: 0x01a0n, // 0x01a0 (0x0018) [FScriptDelegate]
  __OnTravelRequestReceived__Delegate: 0x01b8n, // 0x01b8 (0x0018) [FScriptDelegate]
  __OnCreateNewSessionRequestReceived__Delegate: 0x01d0n, // 0x01d0 (0x0018) [FScriptDelegate]
  ...MeshBeacon,
} as const;

/**
 * IpDrv.MeshBeaconHost Offsets
 * Size: 0x0190
 * Extends: MeshBeacon
 */
export const MeshBeaconHost = {
  ClientConnections: 0x00a8n, // 0x00a8 (0x0010) [TArray<FClientMeshBeaconConnection>]
  PendingPlayerConnections: 0x00b8n, // 0x00b8 (0x0010) [TArray<FUniqueNetId>]
  OwningPlayerId: 0x00c8n, // 0x00c8 (0x0048) [FUniqueNetId]
  bAllowBandwidthTesting: 0x0110n, // 0x0110 (0x0004) [bool : 0x1]
  ConnectionBacklog: 0x0114n, // 0x0114 (0x0004) [int32]
  __OnReceivedClientConnectionRequest__Delegate: 0x0118n, // 0x0118 (0x0018) [FScriptDelegate]
  __OnStartedBandwidthTest__Delegate: 0x0130n, // 0x0130 (0x0018) [FScriptDelegate]
  __OnFinishedBandwidthTest__Delegate: 0x0148n, // 0x0148 (0x0018) [FScriptDelegate]
  __OnAllPendingPlayersConnected__Delegate: 0x0160n, // 0x0160 (0x0018) [FScriptDelegate]
  __OnReceivedClientCreateNewSessionResult__Delegate: 0x0178n, // 0x0178 (0x0018) [FScriptDelegate]
  ...MeshBeacon,
} as const;

/**
 * IpDrv.OnlineAuthInterfaceImpl Offsets
 * Size: 0x03c8
 * Extends: Object_
 */
export const OnlineAuthInterfaceImpl = {
  VfTable_IOnlineAuthInterface: 0x0060n, // 0x0060 (0x0008) [FPointer]
  AuthCodeRequests: 0x0068n, // 0x0068 (0x0010) [TArray<FAuthCodeRequest>]
  NextAuthCodeID: 0x0078n, // 0x0078 (0x0004) [int32]
  OwningSubsystem: 0x0080n, // 0x0080 (0x0008) [UOnlineSubsystemCommonImpl*]
  bAuthReady: 0x0088n, // 0x0088 (0x0004) [bool : 0x1]
  ClientAuthSessions: 0x0090n, // 0x0090 (0x0038) [FSparseArray_Mirror]
  ServerAuthSessions: 0x00c8n, // 0x00c8 (0x0038) [FSparseArray_Mirror]
  PeerAuthSessions: 0x0100n, // 0x0100 (0x0038) [FSparseArray_Mirror]
  LocalClientAuthSessions: 0x0138n, // 0x0138 (0x0038) [FSparseArray_Mirror]
  LocalServerAuthSessions: 0x0170n, // 0x0170 (0x0038) [FSparseArray_Mirror]
  LocalPeerAuthSessions: 0x01a8n, // 0x01a8 (0x0038) [FSparseArray_Mirror]
  AuthReadyDelegates: 0x01e0n, // 0x01e0 (0x0010) [TArray<FScriptDelegate>]
  ClientAuthRequestDelegates: 0x01f0n, // 0x01f0 (0x0010) [TArray<FScriptDelegate>]
  ServerAuthRequestDelegates: 0x0200n, // 0x0200 (0x0010) [TArray<FScriptDelegate>]
  ClientAuthResponseDelegates: 0x0210n, // 0x0210 (0x0010) [TArray<FScriptDelegate>]
  ServerAuthResponseDelegates: 0x0220n, // 0x0220 (0x0010) [TArray<FScriptDelegate>]
  ClientAuthCompleteDelegates: 0x0230n, // 0x0230 (0x0010) [TArray<FScriptDelegate>]
  ServerAuthCompleteDelegates: 0x0240n, // 0x0240 (0x0010) [TArray<FScriptDelegate>]
  ClientAuthEndSessionRequestDelegates: 0x0250n, // 0x0250 (0x0010) [TArray<FScriptDelegate>]
  ServerAuthRetryRequestDelegates: 0x0260n, // 0x0260 (0x0010) [TArray<FScriptDelegate>]
  ClientConnectionCloseDelegates: 0x0270n, // 0x0270 (0x0010) [TArray<FScriptDelegate>]
  ServerConnectionCloseDelegates: 0x0280n, // 0x0280 (0x0010) [TArray<FScriptDelegate>]
  __OnAuthReady__Delegate: 0x0290n, // 0x0290 (0x0018) [FScriptDelegate]
  __OnClientAuthRequest__Delegate: 0x02a8n, // 0x02a8 (0x0018) [FScriptDelegate]
  __OnServerAuthRequest__Delegate: 0x02c0n, // 0x02c0 (0x0018) [FScriptDelegate]
  __OnClientAuthResponse__Delegate: 0x02d8n, // 0x02d8 (0x0018) [FScriptDelegate]
  __OnServerAuthResponse__Delegate: 0x02f0n, // 0x02f0 (0x0018) [FScriptDelegate]
  __OnClientAuthComplete__Delegate: 0x0308n, // 0x0308 (0x0018) [FScriptDelegate]
  __OnServerAuthComplete__Delegate: 0x0320n, // 0x0320 (0x0018) [FScriptDelegate]
  __OnClientAuthEndSessionRequest__Delegate: 0x0338n, // 0x0338 (0x0018) [FScriptDelegate]
  __OnServerAuthRetryRequest__Delegate: 0x0350n, // 0x0350 (0x0018) [FScriptDelegate]
  __OnClientConnectionClose__Delegate: 0x0368n, // 0x0368 (0x0018) [FScriptDelegate]
  __OnServerConnectionClose__Delegate: 0x0380n, // 0x0380 (0x0018) [FScriptDelegate]
  __OnReceivedAuthCode__Delegate: 0x0398n, // 0x0398 (0x0018) [FScriptDelegate]
  __OnAccountAuthorization__Delegate: 0x03b0n, // 0x03b0 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlineEventsInterfaceMcp Offsets
 * Size: 0x00b4
 * Extends: MCPBase
 */
export const OnlineEventsInterfaceMcp = {
  EventUploadConfigs: 0x0080n, // 0x0080 (0x0010) [TArray<FEventUploadConfig>]
  MCPEventPostObjects: 0x0090n, // 0x0090 (0x0010) [TArray<FPointer>]
  DisabledUploadTypes: 0x00a0n, // 0x00a0 (0x0010) [TArray<EEventUploadType>]
  bBinaryStats: 0x00b0n, // 0x00b0 (0x0004) [bool : 0x1]
  ...MCPBase,
} as const;

/**
 * IpDrv.OnlineFriendsInterfaceImpl Offsets
 * Size: 0x0080
 * Extends: Object_
 */
export const OnlineFriendsInterfaceImpl = {
  VfTable_IOnlineFriendsInterface: 0x0060n, // 0x0060 (0x0008) [FPointer]
  __OnReceivedLinkedAccount__Delegate: 0x0068n, // 0x0068 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlineGameInterfaceImpl Offsets
 * Size: 0x0318
 * Extends: Object_
 */
export const OnlineGameInterfaceImpl = {
  OwningSubsystem: 0x0060n, // 0x0060 (0x0008) [UOnlineSubsystemCommonImpl*]
  GameSettings: 0x0068n, // 0x0068 (0x0008) [UOnlineGameSettings*]
  GameSearch: 0x0070n, // 0x0070 (0x0008) [UOnlineGameSearch*]
  CreateOnlineGameCompleteDelegates: 0x0078n, // 0x0078 (0x0010) [TArray<FScriptDelegate>]
  UpdateOnlineGameCompleteDelegates: 0x0088n, // 0x0088 (0x0010) [TArray<FScriptDelegate>]
  DestroyOnlineGameCompleteDelegates: 0x0098n, // 0x0098 (0x0010) [TArray<FScriptDelegate>]
  JoinOnlineGameCompleteDelegates: 0x00a8n, // 0x00a8 (0x0010) [TArray<FScriptDelegate>]
  MigrateOnlineGameCompleteDelegates: 0x00b8n, // 0x00b8 (0x0010) [TArray<FScriptDelegate>]
  JoinMigratedOnlineGameCompleteDelegates: 0x00c8n, // 0x00c8 (0x0010) [TArray<FScriptDelegate>]
  RecalculateSkillRatingCompleteDelegates: 0x00d8n, // 0x00d8 (0x0010) [TArray<FScriptDelegate>]
  StartOnlineGameCompleteDelegates: 0x00e8n, // 0x00e8 (0x0010) [TArray<FScriptDelegate>]
  EndOnlineGameCompleteDelegates: 0x00f8n, // 0x00f8 (0x0010) [TArray<FScriptDelegate>]
  FindOnlineGamesCompleteDelegates: 0x0108n, // 0x0108 (0x0010) [TArray<FScriptDelegate>]
  CancelFindOnlineGamesCompleteDelegates: 0x0118n, // 0x0118 (0x0010) [TArray<FScriptDelegate>]
  LanBeaconState: 0x0128n, // 0x0128 (0x0001) [ELanBeaconState]
  LanNonce: 0x0129n, // 0x0129 (0x0008) [uint8]
  LanAnnouncePort: 0x0134n, // 0x0134 (0x0004) [int32]
  LanGameUniqueId: 0x0138n, // 0x0138 (0x0004) [int32]
  LanPacketPlatformMask: 0x013cn, // 0x013c (0x0004) [int32]
  LanQueryTimeLeft: 0x0140n, // 0x0140 (0x0004) [float]
  LanQueryTimeout: 0x0144n, // 0x0144 (0x0004) [float]
  LanBeacon: 0x0148n, // 0x0148 (0x0008) [FPointer]
  SessionInfo: 0x0150n, // 0x0150 (0x0008) [FPointer]
  GameInviteAcceptedDelegates: 0x0158n, // 0x0158 (0x0010) [TArray<FScriptDelegate>]
  __OnFindOnlineGamesComplete__Delegate: 0x0168n, // 0x0168 (0x0018) [FScriptDelegate]
  __OnCreateOnlineGameComplete__Delegate: 0x0180n, // 0x0180 (0x0018) [FScriptDelegate]
  __OnUpdateOnlineGameComplete__Delegate: 0x0198n, // 0x0198 (0x0018) [FScriptDelegate]
  __OnDestroyOnlineGameComplete__Delegate: 0x01b0n, // 0x01b0 (0x0018) [FScriptDelegate]
  __OnCancelFindOnlineGamesComplete__Delegate: 0x01c8n, // 0x01c8 (0x0018) [FScriptDelegate]
  __OnJoinOnlineGameComplete__Delegate: 0x01e0n, // 0x01e0 (0x0018) [FScriptDelegate]
  __OnRegisterPlayerComplete__Delegate: 0x01f8n, // 0x01f8 (0x0018) [FScriptDelegate]
  __OnUnregisterPlayerComplete__Delegate: 0x0210n, // 0x0210 (0x0018) [FScriptDelegate]
  __OnStartOnlineGameComplete__Delegate: 0x0228n, // 0x0228 (0x0018) [FScriptDelegate]
  __OnEndOnlineGameComplete__Delegate: 0x0240n, // 0x0240 (0x0018) [FScriptDelegate]
  __OnArbitrationRegistrationComplete__Delegate: 0x0258n, // 0x0258 (0x0018) [FScriptDelegate]
  __OnGameInviteAccepted__Delegate: 0x0270n, // 0x0270 (0x0018) [FScriptDelegate]
  __OnRecalculateSkillRatingComplete__Delegate: 0x0288n, // 0x0288 (0x0018) [FScriptDelegate]
  __OnMigrateOnlineGameComplete__Delegate: 0x02a0n, // 0x02a0 (0x0018) [FScriptDelegate]
  __OnJoinMigratedOnlineGameComplete__Delegate: 0x02b8n, // 0x02b8 (0x0018) [FScriptDelegate]
  __OnQosStatusChanged__Delegate: 0x02d0n, // 0x02d0 (0x0018) [FScriptDelegate]
  __EventReportMatchmakingInfo__Delegate: 0x02e8n, // 0x02e8 (0x0018) [FScriptDelegate]
  __OnGamePlayersChanged__Delegate: 0x0300n, // 0x0300 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlineImageDownloaderWeb Offsets
 * Size: 0x0110
 * Extends: Object_
 */
export const OnlineImageDownloaderWeb = {
  MaxSimultaneousDownloads: 0x0060n, // 0x0060 (0x0004) [int32]
  Downloads: 0x0068n, // 0x0068 (0x0050) [FMap_Mirror]
  URLQueue: 0x00b8n, // 0x00b8 (0x0010) [TArray<FString>]
  Decoder: 0x00c8n, // 0x00c8 (0x0008) [UImageDecoder*]
  PendingDownloadCount: 0x00d0n, // 0x00d0 (0x0004) [int32]
  ActiveDownloadCount: 0x00d4n, // 0x00d4 (0x0004) [int32]
  SucceededDownloadCount: 0x00d8n, // 0x00d8 (0x0004) [int32]
  FailedDownloadCount: 0x00dcn, // 0x00dc (0x0004) [int32]
  __OnOnlineImageFinished__Delegate: 0x00e0n, // 0x00e0 (0x0018) [FScriptDelegate]
  __EventImageDecoded__Delegate: 0x00f8n, // 0x00f8 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlineLobbyInterfaceImpl Offsets
 * Size: 0x02c0
 * Extends: Object_
 */
export const OnlineLobbyInterfaceImpl = {
  CreateLobbyCompleteDelegates: 0x0060n, // 0x0060 (0x0010) [TArray<FScriptDelegate>]
  FindLobbiesCompleteDelegates: 0x0070n, // 0x0070 (0x0010) [TArray<FScriptDelegate>]
  JoinLobbyCompleteDelegates: 0x0080n, // 0x0080 (0x0010) [TArray<FScriptDelegate>]
  LobbySettingsUpdateDelegates: 0x0090n, // 0x0090 (0x0010) [TArray<FScriptDelegate>]
  LobbyMemberSettingsUpdateDelegates: 0x00a0n, // 0x00a0 (0x0010) [TArray<FScriptDelegate>]
  LobbyMemberStatusUpdateDelegates: 0x00b0n, // 0x00b0 (0x0010) [TArray<FScriptDelegate>]
  LobbyReceiveMessageDelegates: 0x00c0n, // 0x00c0 (0x0010) [TArray<FScriptDelegate>]
  LobbyReceiveBinaryDataDelegates: 0x00d0n, // 0x00d0 (0x0010) [TArray<FScriptDelegate>]
  LobbyJoinGameDelegates: 0x00e0n, // 0x00e0 (0x0010) [TArray<FScriptDelegate>]
  LobbyInviteDelegates: 0x00f0n, // 0x00f0 (0x0010) [TArray<FScriptDelegate>]
  LobbyErrorDelegates: 0x0100n, // 0x0100 (0x0010) [TArray<FScriptDelegate>]
  LobbyDestroyedDelegates: 0x0110n, // 0x0110 (0x0010) [TArray<FScriptDelegate>]
  LobbySessionCreatedDelegates: 0x0120n, // 0x0120 (0x0010) [TArray<FScriptDelegate>]
  HostStartPlayTogetherDelegates: 0x0130n, // 0x0130 (0x0010) [TArray<FScriptDelegate>]
  ActiveLobbies: 0x0140n, // 0x0140 (0x0010) [TArray<FActiveLobbyInfo>]
  CachedFindLobbyResults: 0x0150n, // 0x0150 (0x0010) [TArray<FBasicLobbyInfo>]
  CachedBinaryData: 0x0160n, // 0x0160 (0x0010) [TArray<uint8>]
  __OnCreateLobbyComplete__Delegate: 0x0170n, // 0x0170 (0x0018) [FScriptDelegate]
  __OnFindLobbiesComplete__Delegate: 0x0188n, // 0x0188 (0x0018) [FScriptDelegate]
  __OnJoinLobbyComplete__Delegate: 0x01a0n, // 0x01a0 (0x0018) [FScriptDelegate]
  __OnLobbySettingsUpdate__Delegate: 0x01b8n, // 0x01b8 (0x0018) [FScriptDelegate]
  __OnLobbyMemberSettingsUpdate__Delegate: 0x01d0n, // 0x01d0 (0x0018) [FScriptDelegate]
  __OnLobbyMemberStatusUpdate__Delegate: 0x01e8n, // 0x01e8 (0x0018) [FScriptDelegate]
  __OnLobbyReceiveMessage__Delegate: 0x0200n, // 0x0200 (0x0018) [FScriptDelegate]
  __OnLobbyReceiveBinaryData__Delegate: 0x0218n, // 0x0218 (0x0018) [FScriptDelegate]
  __OnLobbyJoinGame__Delegate: 0x0230n, // 0x0230 (0x0018) [FScriptDelegate]
  __OnLobbyInvite__Delegate: 0x0248n, // 0x0248 (0x0018) [FScriptDelegate]
  __OnLobbyDestroyed__Delegate: 0x0260n, // 0x0260 (0x0018) [FScriptDelegate]
  __OnLobbySessionCreated__Delegate: 0x0278n, // 0x0278 (0x0018) [FScriptDelegate]
  __OnLobbyError__Delegate: 0x0290n, // 0x0290 (0x0018) [FScriptDelegate]
  __OnHostStartPlayTogether__Delegate: 0x02a8n, // 0x02a8 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlineNewsInterfaceMcp Offsets
 * Size: 0x00c0
 * Extends: MCPBase
 */
export const OnlineNewsInterfaceMcp = {
  NewsItems: 0x0080n, // 0x0080 (0x0010) [TArray<FNewsCacheEntry>]
  ReadNewsDelegates: 0x0090n, // 0x0090 (0x0010) [TArray<FScriptDelegate>]
  bNeedsTicking: 0x00a0n, // 0x00a0 (0x0004) [bool : 0x1]
  __OnReadNewsCompleted__Delegate: 0x00a8n, // 0x00a8 (0x0018) [FScriptDelegate]
  ...MCPBase,
} as const;

/**
 * IpDrv.OnlinePersistentAuthInterfaceImpl Offsets
 * Size: 0x00b8
 * Extends: Object_
 */
export const OnlinePersistentAuthInterfaceImpl = {
  VfTable_IOnlinePersistentAuthInterface: 0x0060n, // 0x0060 (0x0008) [FPointer]
  RequestPinGrantCodeDelegates: 0x0068n, // 0x0068 (0x0010) [TArray<FScriptDelegate>]
  UnderageUserDetectedDelegates: 0x0078n, // 0x0078 (0x0010) [TArray<FScriptDelegate>]
  __OnReceievedPinGrantCode__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  __OnUnderageUserDetected__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlinePlaylistManager Offsets
 * Size: 0x0148
 * Extends: Object_
 */
export const OnlinePlaylistManager = {
  VfTable_FTickableObject: 0x0060n, // 0x0060 (0x0008) [FPointer]
  Playlists: 0x0068n, // 0x0068 (0x0010) [TArray<FPlaylist>]
  PlaylistFileNames: 0x0078n, // 0x0078 (0x0010) [TArray<FString>]
  DatastoresToRefresh: 0x0088n, // 0x0088 (0x0010) [TArray<FName>]
  DownloadCount: 0x0098n, // 0x0098 (0x0004) [int32]
  SuccessfulCount: 0x009cn, // 0x009c (0x0004) [int32]
  VersionNumber: 0x00a0n, // 0x00a0 (0x0004) [int32]
  PopulationData: 0x00a8n, // 0x00a8 (0x0010) [TArray<FPlaylistPopulation>]
  WorldwideTotalPlayers: 0x00b8n, // 0x00b8 (0x0004) [int32]
  RegionTotalPlayers: 0x00bcn, // 0x00bc (0x0004) [int32]
  TitleFileInterface: 0x00c0n, // 0x00c0 (0x0010) [UOnlineTitleFileInterface*]
  PopulationFileName: 0x00d0n, // 0x00d0 (0x0010) [FString]
  NextPlaylistPopulationUpdateTime: 0x00e0n, // 0x00e0 (0x0004) [float]
  PlaylistPopulationUpdateInterval: 0x00e4n, // 0x00e4 (0x0004) [float]
  MinPlaylistIdToReport: 0x00e8n, // 0x00e8 (0x0004) [int32]
  CurrentPlaylistId: 0x00ecn, // 0x00ec (0x0004) [int32]
  EventsInterfaceName: 0x00f0n, // 0x00f0 (0x0008) [FName]
  DataCenterId: 0x00f8n, // 0x00f8 (0x0004) [int32]
  DataCenterFileName: 0x0100n, // 0x0100 (0x0010) [FString]
  LastPlaylistDownloadTime: 0x0110n, // 0x0110 (0x0004) [float]
  PlaylistRefreshInterval: 0x0114n, // 0x0114 (0x0004) [float]
  __OnReadPlaylistComplete__Delegate: 0x0118n, // 0x0118 (0x0018) [FScriptDelegate]
  __OnPlaylistPopulationDataUpdated__Delegate: 0x0130n, // 0x0130 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Engine.UIRoot Offsets
 * Size: 0x0070
 * Extends: Object_
 */
export const UIRoot = {
  BadCapsLocContexts: 0x0060n, // 0x0060 (0x0010) [TArray<FString>]
  ...Object_,
} as const;

/**
 * Engine.UIDataProvider Offsets
 * Size: 0x0070
 * Extends: UIRoot
 */
export const UIDataProvider = {
  ...UIRoot,
} as const;

/**
 * Engine.UIPropertyDataProvider Offsets
 * Size: 0x0098
 * Extends: UIDataProvider
 */
export const UIPropertyDataProvider = {
  ComplexPropertyTypes: 0x0070n, // 0x0070 (0x0010) [TArray<UProperty*>]
  __CanSupportComplexPropertyType__Delegate: 0x0080n, // 0x0080 (0x0018) [FScriptDelegate]
  ...UIDataProvider,
} as const;

/**
 * Engine.UIResourceDataProvider Offsets
 * Size: 0x009c
 * Extends: UIPropertyDataProvider
 */
export const UIResourceDataProvider = {
  bSkipDuringEnumeration: 0x0098n, // 0x0098 (0x0004) [bool : 0x1]
  ...UIPropertyDataProvider,
} as const;

/**
 * IpDrv.OnlinePlaylistProvider Offsets
 * Size: 0x00cc
 * Extends: UIResourceDataProvider
 */
export const OnlinePlaylistProvider = {
  PlaylistId: 0x00a0n, // 0x00a0 (0x0004) [int32]
  PlaylistGameTypeNames: 0x00a8n, // 0x00a8 (0x0010) [TArray<FName>]
  DisplayName: 0x00b8n, // 0x00b8 (0x0010) [FString]
  Priority: 0x00c8n, // 0x00c8 (0x0004) [int32]
  ...UIResourceDataProvider,
} as const;

/**
 * IpDrv.OnlinePurchaseInterfaceImpl Offsets
 * Size: 0x0090
 * Extends: Object_
 */
export const OnlinePurchaseInterfaceImpl = {
  __EventGetAppPriceInfoComplete__Delegate: 0x0060n, // 0x0060 (0x0018) [FScriptDelegate]
  __OnMicroTxnResponse__Delegate: 0x0078n, // 0x0078 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Engine.OnlineSubsystem Offsets
 * Size: 0x0378
 * Extends: Object_
 */
export const OnlineSubsystem = {
  VfTable_FTickableObject: 0x0060n, // 0x0060 (0x0008) [FPointer]
  AccountInterface: 0x0068n, // 0x0068 (0x0010) [UOnlineAccountInterface*]
  PlayerInterface: 0x0078n, // 0x0078 (0x0010) [UOnlinePlayerInterface*]
  PlayerInterfaceEx: 0x0088n, // 0x0088 (0x0010) [UOnlinePlayerInterfaceEx*]
  MarketplaceInterface: 0x0098n, // 0x0098 (0x0010) [UOnlineMarketplaceInterface*]
  SystemInterface: 0x00a8n, // 0x00a8 (0x0010) [UOnlineSystemInterface*]
  GameInterface: 0x00b8n, // 0x00b8 (0x0010) [UOnlineGameInterface*]
  ContentInterface: 0x00c8n, // 0x00c8 (0x0010) [UOnlineContentInterface*]
  VoiceInterface: 0x00d8n, // 0x00d8 (0x0010) [UOnlineVoiceInterface*]
  StatsInterface: 0x00e8n, // 0x00e8 (0x0010) [UOnlineStatsInterface*]
  NewsInterface: 0x00f8n, // 0x00f8 (0x0010) [UOnlineNewsInterface*]
  PartyChatInterface: 0x0108n, // 0x0108 (0x0010) [UOnlinePartyChatInterface*]
  TitleFileInterface: 0x0118n, // 0x0118 (0x0010) [UOnlineTitleFileInterface*]
  TitleFileCacheInterface: 0x0128n, // 0x0128 (0x0010) [UOnlineTitleFileCacheInterface*]
  UserCloudInterface: 0x0138n, // 0x0138 (0x0010) [UUserCloudFileInterface*]
  SharedCloudInterface: 0x0148n, // 0x0148 (0x0010) [USharedCloudFileInterface*]
  SocialInterface: 0x0158n, // 0x0158 (0x0010) [UOnlineSocialInterface*]
  AuthInterface: 0x0168n, // 0x0168 (0x0010) [UOnlineAuthInterface*]
  PersistentAuthInterface: 0x0178n, // 0x0178 (0x0010) [UOnlinePersistentAuthInterface*]
  GameDVRInterface: 0x0188n, // 0x0188 (0x0010) [UOnlineGameDVRInterface*]
  CommunityContentInterface: 0x0198n, // 0x0198 (0x0010) [UOnlineCommunityContentInterface*]
  PurchaseInterface: 0x01a8n, // 0x01a8 (0x0010) [UOnlinePurchaseInterface*]
  LobbyInterface: 0x01b8n, // 0x01b8 (0x0010) [UOnlineLobbyInterface*]
  FriendsInterface: 0x01c8n, // 0x01c8 (0x0010) [UOnlineFriendsInterface*]
  GameClipsInterface: 0x01d8n, // 0x01d8 (0x0010) [UOnlineGameClipsInterface*]
  SearchClass: 0x01e8n, // 0x01e8 (0x0008) [UOnlineGameSearch*]
  bSupportsMultiSignin: 0x01f0n, // 0x01f0 (0x0004) [bool : 0x1]
  bSupportsMultiVoice: 0x01f0n, // 0x01f0 (0x0004) [bool : 0x2]
  bShowPrivilegeCheckErrors: 0x01f0n, // 0x01f0 (0x0004) [bool : 0x4]
  AccountSettings: 0x01f8n, // 0x01f8 (0x0010) [TArray<UPlatformAccountSettings*>]
  BlockListStatuses: 0x0208n, // 0x0208 (0x0010) [TArray<UPlatformBlockListStatus*>]
  UnsupportedCorrectiveActionURLs: 0x0218n, // 0x0218 (0x0010) [TArray<UPlatformURL*>]
  SessionManager: 0x0228n, // 0x0228 (0x0008) [UOnlineSessionManager*]
  SteamDLC: 0x0230n, // 0x0230 (0x0010) [TArray<FSteamDLCInfo>]
  PS4DLC: 0x0240n, // 0x0240 (0x0010) [TArray<FPS4DLCInfo>]
  XboxOneDLC: 0x0250n, // 0x0250 (0x0010) [TArray<FXboxOneDLCInfo>]
  SwitchDLC: 0x0260n, // 0x0260 (0x0010) [TArray<FSwitchDLCInfo>]
  EpicDLC: 0x0270n, // 0x0270 (0x0010) [TArray<FEpicDLCInfo>]
  OnlinePlatformType: 0x0280n, // 0x0280 (0x0001) [OnlinePlatform]
  CurrentConnectionStatus: 0x0281n, // 0x0281 (0x0001) [EOnlineServerConnectionStatus]
  OnlineSubsystemNames: 0x0288n, // 0x0288 (0x0010) [TArray<FString>]
  NamedInterfaces: 0x0298n, // 0x0298 (0x0010) [TArray<FNamedInterface>]
  NamedInterfaceDefs: 0x02a8n, // 0x02a8 (0x0010) [TArray<FNamedInterfaceDef>]
  Sessions: 0x02b8n, // 0x02b8 (0x0010) [TArray<FNamedSession>]
  IniLocPatcherClassName: 0x02c8n, // 0x02c8 (0x0010) [FString]
  Patcher: 0x02d8n, // 0x02d8 (0x0008) [UIniLocPatcher*]
  AsyncMinCompletionTime: 0x02e0n, // 0x02e0 (0x0004) [float]
  __FeaturePrivilegeLevelUpdated__Delegate: 0x02e8n, // 0x02e8 (0x0018) [FScriptDelegate]
  __EventPlatformAccountSettingsCreated__Delegate: 0x0300n, // 0x0300 (0x0018) [FScriptDelegate]
  __EventPlatformBlockListStatusCreated__Delegate: 0x0318n, // 0x0318 (0x0018) [FScriptDelegate]
  __OnDeviceSuspend__Delegate: 0x0330n, // 0x0330 (0x0018) [FScriptDelegate]
  __OnReadOnlineAvatarComplete__Delegate: 0x0348n, // 0x0348 (0x0018) [FScriptDelegate]
  __OnSystemUserControllerPairingChanged__Delegate: 0x0360n, // 0x0360 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.OnlineSubsystemCommonImpl Offsets
 * Size: 0x03c0
 * Extends: OnlineSubsystem
 */
export const OnlineSubsystemCommonImpl = {
  VoiceEngine: 0x0378n, // 0x0378 (0x0008) [FPointer]
  MaxLocalTalkers: 0x0380n, // 0x0380 (0x0004) [int32]
  MaxRemoteTalkers: 0x0384n, // 0x0384 (0x0004) [int32]
  bIsUsingSpeechRecognition: 0x0388n, // 0x0388 (0x0004) [bool : 0x1]
  GameInterfaceImpl: 0x0390n, // 0x0390 (0x0008) [UOnlineGameInterfaceImpl*]
  AuthInterfaceImpl: 0x0398n, // 0x0398 (0x0008) [UOnlineAuthInterfaceImpl*]
  PurchaseInterfaceImpl: 0x03a0n, // 0x03a0 (0x0008) [UOnlinePurchaseInterfaceImpl*]
  __OnSanitizeStringComplete__Delegate: 0x03a8n, // 0x03a8 (0x0018) [FScriptDelegate]
  ...OnlineSubsystem,
} as const;

/**
 * IpDrv.OnlineTitleFileDownloadMcp Offsets
 * Size: 0x012c
 * Extends: OnlineTitleFileDownloadBase
 */
export const OnlineTitleFileDownloadMcp = {
  TitleFiles: 0x0118n, // 0x0118 (0x0010) [TArray<FTitleFileMcp>]
  DownloadCount: 0x0128n, // 0x0128 (0x0004) [int32]
  ...OnlineTitleFileDownloadBase,
} as const;

/**
 * IpDrv.PartyBeacon Offsets
 * Size: 0x00a8
 * Extends: Object_
 */
export const PartyBeacon = {
  VfTable_FTickableObject: 0x0060n, // 0x0060 (0x0008) [FPointer]
  PartyBeaconPort: 0x0068n, // 0x0068 (0x0004) [int32]
  Socket: 0x0070n, // 0x0070 (0x0008) [FPointer]
  bIsInTick: 0x0078n, // 0x0078 (0x0004) [bool : 0x1]
  bWantsDeferredDestroy: 0x0078n, // 0x0078 (0x0004) [bool : 0x2]
  bShouldTick: 0x0078n, // 0x0078 (0x0004) [bool : 0x4]
  HeartbeatTimeout: 0x007cn, // 0x007c (0x0004) [float]
  ElapsedHeartbeatTime: 0x0080n, // 0x0080 (0x0004) [float]
  BeaconName: 0x0084n, // 0x0084 (0x0008) [FName]
  __OnDestroyComplete__Delegate: 0x0090n, // 0x0090 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * IpDrv.PartyBeaconClient Offsets
 * Size: 0x01c0
 * Extends: PartyBeacon
 */
export const PartyBeaconClient = {
  HostPendingRequest: 0x00a8n, // 0x00a8 (0x0010) [FOnlineGameSearchResult]
  PendingRequest: 0x00b8n, // 0x00b8 (0x0060) [FPartyReservation]
  ClientBeaconState: 0x0118n, // 0x0118 (0x0001) [EPartyBeaconClientState]
  ClientBeaconRequestType: 0x0119n, // 0x0119 (0x0001) [EPartyBeaconClientRequest]
  ReservationRequestTimeout: 0x011cn, // 0x011c (0x0004) [float]
  ReservationRequestElapsedTime: 0x0120n, // 0x0120 (0x0004) [float]
  ResolverClassName: 0x0128n, // 0x0128 (0x0010) [FString]
  ResolverClass: 0x0138n, // 0x0138 (0x0008) [UClientBeaconAddressResolver*]
  Resolver: 0x0140n, // 0x0140 (0x0008) [UClientBeaconAddressResolver*]
  __OnReservationRequestComplete__Delegate: 0x0148n, // 0x0148 (0x0018) [FScriptDelegate]
  __OnReservationCountUpdated__Delegate: 0x0160n, // 0x0160 (0x0018) [FScriptDelegate]
  __OnTravelRequestReceived__Delegate: 0x0178n, // 0x0178 (0x0018) [FScriptDelegate]
  __OnHostIsReady__Delegate: 0x0190n, // 0x0190 (0x0018) [FScriptDelegate]
  __OnHostHasCancelled__Delegate: 0x01a8n, // 0x01a8 (0x0018) [FScriptDelegate]
  ...PartyBeacon,
} as const;

/**
 * IpDrv.PartyBeaconHost Offsets
 * Size: 0x0140
 * Extends: PartyBeacon
 */
export const PartyBeaconHost = {
  Clients: 0x00a8n, // 0x00a8 (0x0010) [TArray<FClientBeaconConnection>]
  NumTeams: 0x00b8n, // 0x00b8 (0x0004) [int32]
  NumPlayersPerTeam: 0x00bcn, // 0x00bc (0x0004) [int32]
  NumReservations: 0x00c0n, // 0x00c0 (0x0004) [int32]
  NumConsumedReservations: 0x00c4n, // 0x00c4 (0x0004) [int32]
  Reservations: 0x00c8n, // 0x00c8 (0x0010) [TArray<FPartyReservation>]
  OnlineSessionName: 0x00d8n, // 0x00d8 (0x0008) [FName]
  ConnectionBacklog: 0x00e0n, // 0x00e0 (0x0004) [int32]
  ForceTeamNum: 0x00e4n, // 0x00e4 (0x0004) [int32]
  ReservedHostTeamNum: 0x00e8n, // 0x00e8 (0x0004) [int32]
  bBestFitTeamAssignment: 0x00ecn, // 0x00ec (0x0004) [bool : 0x1]
  BeaconState: 0x00f0n, // 0x00f0 (0x0001) [EPartyBeaconHostState]
  __OnReservationChange__Delegate: 0x00f8n, // 0x00f8 (0x0018) [FScriptDelegate]
  __OnReservationsFull__Delegate: 0x0110n, // 0x0110 (0x0018) [FScriptDelegate]
  __OnClientCancellationReceived__Delegate: 0x0128n, // 0x0128 (0x0018) [FScriptDelegate]
  ...PartyBeacon,
} as const;

/**
 * IpDrv.TargetUserChatPermChangedEvent Offsets
 * Size: 0x00f4
 * Extends: Object_
 */
export const TargetUserChatPermChangedEvent = {
  PlayerID: 0x0060n, // 0x0060 (0x0048) [FUniqueNetId]
  TargetId: 0x00a8n, // 0x00a8 (0x0048) [FUniqueNetId]
  bAllowed: 0x00f0n, // 0x00f0 (0x0004) [bool : 0x1]
  ...Object_,
} as const;

/**
 * Engine.Player Offsets
 * Size: 0x00b8
 * Extends: Object_
 */
export const Player = {
  VfTable_FExec: 0x0060n, // 0x0060 (0x0008) [FPointer]
  ObjectProvider: 0x0068n, // 0x0068 (0x0008) [UObjectProvider*]
  RegistryGroup: 0x0070n, // 0x0070 (0x0008) [UGroupComponent_ORS*]
  Actor: 0x0078n, // 0x0078 (0x0008) [UPlayerController*]
  CurrentNetSpeed: 0x0080n, // 0x0080 (0x0004) [int32]
  ConfiguredInternetSpeed: 0x0084n, // 0x0084 (0x0004) [int32]
  ConfiguredReplicationRate: 0x0088n, // 0x0088 (0x0004) [int32]
  PP_DesaturationMultiplier: 0x008cn, // 0x008c (0x0004) [float]
  PP_HighlightsMultiplier: 0x0090n, // 0x0090 (0x0004) [float]
  PP_MidTonesMultiplier: 0x0094n, // 0x0094 (0x0004) [float]
  PP_ShadowsMultiplier: 0x0098n, // 0x0098 (0x0004) [float]
  __EventReceivedController__Delegate: 0x00a0n, // 0x00a0 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * Engine.NetConnection Offsets
 * Size: 0xb1f0
 * Extends: Player
 */
export const NetConnection = {
  Children: 0xb1b0n, // 0xb1b0 (0x0010) [TArray<UChildConnection*>]
  bUseSessionUID: 0xb1dcn, // 0xb1dc (0x0004) [bool : 0x1]
  BadConnectionPingThreshold: 0xb1e8n, // 0xb1e8 (0x0004) [float]
  BadConnectionReceiveTimeThreshold: 0xb1ecn, // 0xb1ec (0x0004) [float]
  ...Player,
} as const;

/**
 * IpDrv.TcpipConnection Offsets
 * Size: 0xb218
 * Extends: NetConnection
 */
export const TcpipConnection = {
  ...NetConnection,
} as const;

/**
 * IpDrv.TcpLink Offsets
 * Size: 0x02d8
 * Extends: InternetLink
 */
export const TcpLink = {
  LinkState: 0x0298n, // 0x0298 (0x0001) [ELinkState]
  RemoteAddr: 0x029cn, // 0x029c (0x0014) [FIpAddr]
  AcceptClass: 0x02b0n, // 0x02b0 (0x0008) [UTcpLink*]
  SendFIFO: 0x02b8n, // 0x02b8 (0x0010) [TArray<uint8>]
  RecvBuf: 0x02c8n, // 0x02c8 (0x0010) [FString]
  ...InternetLink,
} as const;

/**
 * Core.Subsystem Offsets
 * Size: 0x0068
 * Extends: Object_
 */
export const Subsystem = {
  VfTable_FExec: 0x0060n, // 0x0060 (0x0008) [FPointer]
  ...Object_,
} as const;

/**
 * Engine.NetDriver Offsets
 * Size: 0x02a0
 * Extends: Subsystem
 */
export const NetDriver = {
  MatchFailureSeconds: 0x0070n, // 0x0070 (0x0004) [float]
  ConnectionTimeout: 0x00ecn, // 0x00ec (0x0004) [float]
  KeepAliveTime: 0x00f0n, // 0x00f0 (0x0004) [float]
  RelevantTimeout: 0x00f4n, // 0x00f4 (0x0004) [float]
  SpawnPrioritySeconds: 0x00f8n, // 0x00f8 (0x0004) [float]
  ServerTravelPause: 0x00fcn, // 0x00fc (0x0004) [float]
  MinClientRate: 0x0100n, // 0x0100 (0x0004) [int32]
  MaxClientRate: 0x0104n, // 0x0104 (0x0004) [int32]
  MedianClientRate: 0x0108n, // 0x0108 (0x0004) [int32]
  MinReplicationRate: 0x010cn, // 0x010c (0x0004) [int32]
  MaxReplicationRate: 0x0110n, // 0x0110 (0x0004) [int32]
  MedianReplicationRate: 0x0114n, // 0x0114 (0x0004) [int32]
  NetServerMaxTickRate: 0x0118n, // 0x0118 (0x0004) [int32]
  bClampListenServerTickRate: 0x011cn, // 0x011c (0x0004) [bool : 0x1]
  AllowDownloads: 0x0120n, // 0x0120 (0x0004) [bool : 0x1]
  AllowPeerConnections: 0x0124n, // 0x0124 (0x0004) [bool : 0x1]
  AllowPeerVoice: 0x0128n, // 0x0128 (0x0004) [bool : 0x1]
  MaxDownloadSize: 0x0150n, // 0x0150 (0x0004) [int32]
  DownloadManagers: 0x0158n, // 0x0158 (0x0010) [TArray<FString>]
  NetConnectionClassName: 0x0210n, // 0x0210 (0x0010) [FString]
  ...Subsystem,
} as const;

/**
 * IpDrv.TcpNetDriver Offsets
 * Size: 0x0320
 * Extends: NetDriver
 */
export const TcpNetDriver = {
  AllowPlayerPortUnreach: 0x02f8n, // 0x02f8 (0x0004) [bool : 0x1]
  LogPortUnreach: 0x02fcn, // 0x02fc (0x0004) [bool : 0x1]
  ...NetDriver,
} as const;

/**
 * IpDrv.TitleFileDownloadCache Offsets
 * Size: 0x00e0
 * Extends: MCPBase
 */
export const TitleFileDownloadCache = {
  TitleFiles: 0x0080n, // 0x0080 (0x0010) [TArray<FTitleFileCacheEntry>]
  LoadCompleteDelegates: 0x0090n, // 0x0090 (0x0010) [TArray<FScriptDelegate>]
  SaveCompleteDelegates: 0x00a0n, // 0x00a0 (0x0010) [TArray<FScriptDelegate>]
  __OnLoadTitleFileComplete__Delegate: 0x00b0n, // 0x00b0 (0x0018) [FScriptDelegate]
  __OnSaveTitleFileComplete__Delegate: 0x00c8n, // 0x00c8 (0x0018) [FScriptDelegate]
  ...MCPBase,
} as const;

/**
 * Engine.UIDataStore Offsets
 * Size: 0x00a0
 * Extends: UIDataProvider
 */
export const UIDataStore = {
  Tag: 0x0070n, // 0x0070 (0x0008) [FName]
  RefreshSubscriberNotifies: 0x0078n, // 0x0078 (0x0010) [TArray<FScriptDelegate>]
  __OnDataStoreValueUpdated__Delegate: 0x0088n, // 0x0088 (0x0018) [FScriptDelegate]
  ...UIDataProvider,
} as const;

/**
 * IpDrv.UIDataStore_OnlinePlaylists Offsets
 * Size: 0x0100
 * Extends: UIDataStore
 */
export const UIDataStore_OnlinePlaylists = {
  ProviderClassName: 0x00a0n, // 0x00a0 (0x0010) [FString]
  ProviderClass: 0x00b0n, // 0x00b0 (0x0008) [UUIResourceDataProvider*]
  RankedDataProviders: 0x00b8n, // 0x00b8 (0x0010) [TArray<UUIResourceDataProvider*>]
  UnrankedDataProviders: 0x00c8n, // 0x00c8 (0x0010) [TArray<UUIResourceDataProvider*>]
  RecModeDataProviders: 0x00d8n, // 0x00d8 (0x0010) [TArray<UUIResourceDataProvider*>]
  PrivateDataProviders: 0x00e8n, // 0x00e8 (0x0010) [TArray<UUIResourceDataProvider*>]
  PlaylistMan: 0x00f8n, // 0x00f8 (0x0008) [UOnlinePlaylistManager*]
  ...UIDataStore,
} as const;

/**
 * IpDrv.WebConnection Offsets
 * Size: 0x031c
 * Extends: TcpLink
 */
export const WebConnection = {
  WebServer: 0x02d8n, // 0x02d8 (0x0008) [UWebServer*]
  ReceivedData: 0x02e0n, // 0x02e0 (0x0010) [FString]
  Request: 0x02f0n, // 0x02f0 (0x0008) [UWebRequest*]
  Response: 0x02f8n, // 0x02f8 (0x0008) [UWebResponse*]
  Application: 0x0300n, // 0x0300 (0x0008) [UWebApplication*]
  bDelayCleanup: 0x0308n, // 0x0308 (0x0004) [bool : 0x1]
  RawBytesExpecting: 0x030cn, // 0x030c (0x0004) [int32]
  MaxValueLength: 0x0310n, // 0x0310 (0x0004) [int32]
  MaxLineLength: 0x0314n, // 0x0314 (0x0004) [int32]
  ConnID: 0x0318n, // 0x0318 (0x0004) [int32]
  ...TcpLink,
} as const;

/**
 * IpDrv.WebRequest Offsets
 * Size: 0x0160
 * Extends: Object_
 */
export const WebRequest = {
  RemoteAddr: 0x0060n, // 0x0060 (0x0010) [FString]
  URI: 0x0070n, // 0x0070 (0x0010) [FString]
  Username: 0x0080n, // 0x0080 (0x0010) [FString]
  Password: 0x0090n, // 0x0090 (0x0010) [FString]
  ContentLength: 0x00a0n, // 0x00a0 (0x0004) [int32]
  ContentType: 0x00a8n, // 0x00a8 (0x0010) [FString]
  RequestType: 0x00b8n, // 0x00b8 (0x0001) [ERequestType]
  HeaderMap: 0x00c0n, // 0x00c0 (0x0050) [FMap_Mirror]
  VariableMap: 0x0110n, // 0x0110 (0x0050) [FMap_Mirror]
  ...Object_,
} as const;

/**
 * IpDrv.WebResponse Offsets
 * Size: 0x00ec
 * Extends: Object_
 */
export const WebResponse = {
  Headers: 0x0060n, // 0x0060 (0x0010) [TArray<FString>]
  ReplacementMap: 0x0070n, // 0x0070 (0x0050) [FMap_Mirror]
  IncludePath: 0x00c0n, // 0x00c0 (0x0010) [FString]
  CharSet: 0x00d0n, // 0x00d0 (0x0010) [FString]
  Connection: 0x00e0n, // 0x00e0 (0x0008) [UWebConnection*]
  bSentText: 0x00e8n, // 0x00e8 (0x0004) [bool : 0x1]
  bSentResponse: 0x00e8n, // 0x00e8 (0x0004) [bool : 0x2]
  ...Object_,
} as const;

/**
 * IpDrv.WebServer Offsets
 * Size: 0x04a8
 * Extends: TcpLink
 */
export const WebServer = {
  ServerName: 0x02d8n, // 0x02d8 (0x0010) [FString]
  Applications: 0x02e8n, // 0x02e8 (0x00a0) [FString]
  ApplicationPaths: 0x0388n, // 0x0388 (0x00a0) [FString]
  bEnabled: 0x0428n, // 0x0428 (0x0004) [bool : 0x1]
  ListenPort: 0x042cn, // 0x042c (0x0004) [int32]
  MaxConnections: 0x0430n, // 0x0430 (0x0004) [int32]
  DefaultApplication: 0x0434n, // 0x0434 (0x0004) [int32]
  ExpirationSeconds: 0x0438n, // 0x0438 (0x0004) [int32]
  ServerURL: 0x0440n, // 0x0440 (0x0010) [FString]
  ApplicationObjects: 0x0450n, // 0x0450 (0x0050) [UWebApplication*]
  ConnectionCount: 0x04a0n, // 0x04a0 (0x0004) [int32]
  ConnID: 0x04a4n, // 0x04a4 (0x0004) [int32]
  ...TcpLink,
} as const;
